// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyModelCube : VoxelBlockyModel
{
	public VoxelBlockyModelCube() : base(NativeName)
	{
	}
	protected VoxelBlockyModelCube(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyModelCube(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyModelCube([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelBlockyModelCube self) => self?._object;
	public static implicit operator Variant(VoxelBlockyModelCube self) => self?._object;
	public static explicit operator VoxelBlockyModelCube(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelBlockyModel.PropertyName
	{
		public static readonly StringName Height = "height";
		public static readonly StringName AtlasSizeInTiles = "atlas_size_in_tiles";
		public static readonly StringName MeshOrthoRotationIndex = "mesh_ortho_rotation_index";
	}

	public new class MethodName : VoxelBlockyModel.MethodName
	{
		public static readonly StringName SetHeight = "set_height";
		public static readonly StringName GetHeight = "get_height";
		public static readonly StringName SetTile = "set_tile";
		public static readonly StringName GetTile = "get_tile";
		public static readonly StringName SetAtlasSizeInTiles = "set_atlas_size_in_tiles";
		public static readonly StringName GetAtlasSizeInTiles = "get_atlas_size_in_tiles";
	}

	public new class SignalName : VoxelBlockyModel.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyModelCube";

	#region Properties

	public float Height
	{
		get => (float)_object.Get(PropertyName.Height);
		set => _object.Set(PropertyName.Height, value);
	}

	public Godot.Vector2I AtlasSizeInTiles
	{
		get => (Godot.Vector2I)_object.Get(PropertyName.AtlasSizeInTiles);
		set => _object.Set(PropertyName.AtlasSizeInTiles, value);
	}

	public int MeshOrthoRotationIndex
	{
		get => (int)_object.Get(PropertyName.MeshOrthoRotationIndex);
		set => _object.Set(PropertyName.MeshOrthoRotationIndex, value);
	}

	#endregion

	#region Methods

	public void SetHeight(float @h)
	{
		_object.Call(MethodName.SetHeight, @h);
	}

	public float GetHeight()
	{
		return (float)_object.Call(MethodName.GetHeight);
	}

	public void SetTile(VoxelBlockyModel.Side @side, Godot.Vector2I @position)
	{
		_object.Call(MethodName.SetTile, (int)@side, @position);
	}

	public Godot.Vector2I GetTile(VoxelBlockyModel.Side @side)
	{
		return (Godot.Vector2I)_object.Call(MethodName.GetTile, (int)@side);
	}

	public void SetAtlasSizeInTiles(Godot.Vector2I @ts)
	{
		_object.Call(MethodName.SetAtlasSizeInTiles, @ts);
	}

	public Godot.Vector2I GetAtlasSizeInTiles()
	{
		return (Godot.Vector2I)_object.Call(MethodName.GetAtlasSizeInTiles);
	}

	#endregion
}
























