// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyAttributeRotation : VoxelBlockyAttribute
{
	public VoxelBlockyAttributeRotation() : base(NativeName)
	{
	}
	protected VoxelBlockyAttributeRotation(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyAttributeRotation(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyAttributeRotation([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelBlockyAttributeRotation self) => self?._object;
	public static implicit operator Variant(VoxelBlockyAttributeRotation self) => self?._object;
	public static explicit operator VoxelBlockyAttributeRotation(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelBlockyAttribute.PropertyName
	{
		public static readonly StringName HorizontalOnly = "horizontal_only";
	}

	public new class MethodName : VoxelBlockyAttribute.MethodName
	{
		public static readonly StringName IsHorizontalRollEnabled = "is_horizontal_roll_enabled";
		public static readonly StringName SetHorizontalRollEnabled = "set_horizontal_roll_enabled";
	}

	public new class SignalName : VoxelBlockyAttribute.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyAttributeRotation";

	#region Properties

	public bool HorizontalOnly
	{
		get => (bool)_object.Get(PropertyName.HorizontalOnly);
		set => _object.Set(PropertyName.HorizontalOnly, value);
	}

	#endregion

	#region Methods

	public bool IsHorizontalRollEnabled()
	{
		return (bool)_object.Call(MethodName.IsHorizontalRollEnabled);
	}

	public void SetHorizontalRollEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetHorizontalRollEnabled, @enabled);
	}

	#endregion
}
























