// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelTerrain : VoxelNode
{
	public VoxelTerrain() : base(NativeName)
	{
	}
	protected VoxelTerrain(StringName @class) : base(@class)
	{
	}
	protected VoxelTerrain(Variant variant) : base(variant)
	{
	}
	protected VoxelTerrain([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(VoxelTerrain self) => self?._object;
	public static implicit operator Variant(VoxelTerrain self) => self?._object;
	public static explicit operator VoxelTerrain(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelNode.PropertyName
	{
		public static readonly StringName Bounds = "bounds";
		public static readonly StringName MaxViewDistance = "max_view_distance";
		public static readonly StringName GenerateCollisions = "generate_collisions";
		public static readonly StringName CollisionLayer = "collision_layer";
		public static readonly StringName CollisionMask = "collision_mask";
		public static readonly StringName CollisionMargin = "collision_margin";
		public static readonly StringName MaterialOverride = "material_override";
		public static readonly StringName BlockEnterNotificationEnabled = "block_enter_notification_enabled";
		public static readonly StringName AreaEditNotificationEnabled = "area_edit_notification_enabled";
		public static readonly StringName AutomaticLoadingEnabled = "automatic_loading_enabled";
		public static readonly StringName RunStreamInEditor = "run_stream_in_editor";
		public static readonly StringName MeshBlockSize = "mesh_block_size";
		public static readonly StringName UseGpuGeneration = "use_gpu_generation";
		public static readonly StringName DebugDrawEnabled = "debug_draw_enabled";
		public static readonly StringName DebugDrawVolumeBounds = "debug_draw_volume_bounds";
		public static readonly StringName DebugDrawVisualAndCollisionBlocks = "debug_draw_visual_and_collision_blocks";
		public static readonly StringName DebugDrawVoxelMetadata = "debug_draw_voxel_metadata";
		public static readonly StringName DebugDrawShadowOccluders = "debug_draw_shadow_occluders";
	}

	public new class MethodName : VoxelNode.MethodName
	{
		public static readonly StringName SetMaterialOverride = "set_material_override";
		public static readonly StringName GetMaterialOverride = "get_material_override";
		public static readonly StringName SetMaxViewDistance = "set_max_view_distance";
		public static readonly StringName GetMaxViewDistance = "get_max_view_distance";
		public static readonly StringName SetBlockEnterNotificationEnabled = "set_block_enter_notification_enabled";
		public static readonly StringName IsBlockEnterNotificationEnabled = "is_block_enter_notification_enabled";
		public static readonly StringName SetAreaEditNotificationEnabled = "set_area_edit_notification_enabled";
		public static readonly StringName IsAreaEditNotificationEnabled = "is_area_edit_notification_enabled";
		public static readonly StringName GetGenerateCollisions = "get_generate_collisions";
		public static readonly StringName SetGenerateCollisions = "set_generate_collisions";
		public static readonly StringName GetCollisionLayer = "get_collision_layer";
		public static readonly StringName SetCollisionLayer = "set_collision_layer";
		public static readonly StringName GetCollisionMask = "get_collision_mask";
		public static readonly StringName SetCollisionMask = "set_collision_mask";
		public static readonly StringName GetCollisionMargin = "get_collision_margin";
		public static readonly StringName SetCollisionMargin = "set_collision_margin";
		public static readonly StringName VoxelToDataBlock = "voxel_to_data_block";
		public static readonly StringName DataBlockToVoxel = "data_block_to_voxel";
		public static readonly StringName GetDataBlockSize = "get_data_block_size";
		public static readonly StringName GetMeshBlockSize = "get_mesh_block_size";
		public static readonly StringName SetMeshBlockSize = "set_mesh_block_size";
		public static readonly StringName GetStatistics = "get_statistics";
		public static readonly StringName GetVoxelTool = "get_voxel_tool";
		public static readonly StringName SaveModifiedBlocks = "save_modified_blocks";
		public static readonly StringName SaveBlock = "save_block";
		public static readonly StringName SetRunStreamInEditor = "set_run_stream_in_editor";
		public static readonly StringName IsStreamRunningInEditor = "is_stream_running_in_editor";
		public static readonly StringName SetAutomaticLoadingEnabled = "set_automatic_loading_enabled";
		public static readonly StringName IsAutomaticLoadingEnabled = "is_automatic_loading_enabled";
		public static readonly StringName SetGeneratorUseGpu = "set_generator_use_gpu";
		public static readonly StringName GetGeneratorUseGpu = "get_generator_use_gpu";
		public static readonly StringName SetBounds = "set_bounds";
		public static readonly StringName GetBounds = "get_bounds";
		public static readonly StringName TrySetBlockData = "try_set_block_data";
		public static readonly StringName GetViewerNetworkPeerIdsInArea = "get_viewer_network_peer_ids_in_area";
		public static readonly StringName HasDataBlock = "has_data_block";
		public static readonly StringName IsAreaMeshed = "is_area_meshed";
		public static readonly StringName DebugSetDrawEnabled = "debug_set_draw_enabled";
		public static readonly StringName DebugIsDrawEnabled = "debug_is_draw_enabled";
		public static readonly StringName DebugSetDrawFlag = "debug_set_draw_flag";
		public static readonly StringName DebugGetDrawFlag = "debug_get_draw_flag";
		public static readonly StringName DebugSetDrawShadowOccluders = "debug_set_draw_shadow_occluders";
		public static readonly StringName DebugGetDrawShadowOccluders = "debug_get_draw_shadow_occluders";
	}

	public new class SignalName : VoxelNode.SignalName
	{
		public static readonly StringName BlockLoaded = "block_loaded";
		public static readonly StringName BlockUnloaded = "block_unloaded";
		public static readonly StringName MeshBlockEntered = "mesh_block_entered";
		public static readonly StringName MeshBlockExited = "mesh_block_exited";
	}

	private static readonly StringName NativeName = "VoxelTerrain";

	#region Enums

	public enum DebugDrawFlag : long
	{
		VolumeBounds = 0L,
		VisualAndCollisionBlocks = 1L,
		VoxelMetadata = 2L,
		FlagsCount = 3L,
	}

	#endregion

	#region Properties

	public Godot.Aabb Bounds
	{
		get => (Godot.Aabb)_object.Get(PropertyName.Bounds);
		set => _object.Set(PropertyName.Bounds, value);
	}

	public int MaxViewDistance
	{
		get => (int)_object.Get(PropertyName.MaxViewDistance);
		set => _object.Set(PropertyName.MaxViewDistance, value);
	}

	public bool GenerateCollisions
	{
		get => (bool)_object.Get(PropertyName.GenerateCollisions);
		set => _object.Set(PropertyName.GenerateCollisions, value);
	}

	public int CollisionLayer
	{
		get => (int)_object.Get(PropertyName.CollisionLayer);
		set => _object.Set(PropertyName.CollisionLayer, value);
	}

	public int CollisionMask
	{
		get => (int)_object.Get(PropertyName.CollisionMask);
		set => _object.Set(PropertyName.CollisionMask, value);
	}

	public float CollisionMargin
	{
		get => (float)_object.Get(PropertyName.CollisionMargin);
		set => _object.Set(PropertyName.CollisionMargin, value);
	}

	public Material MaterialOverride
	{
		get => (Material)_object.Get(PropertyName.MaterialOverride);
		set => _object.Set(PropertyName.MaterialOverride, value);
	}

	public bool BlockEnterNotificationEnabled
	{
		get => (bool)_object.Get(PropertyName.BlockEnterNotificationEnabled);
		set => _object.Set(PropertyName.BlockEnterNotificationEnabled, value);
	}

	public bool AreaEditNotificationEnabled
	{
		get => (bool)_object.Get(PropertyName.AreaEditNotificationEnabled);
		set => _object.Set(PropertyName.AreaEditNotificationEnabled, value);
	}

	public bool AutomaticLoadingEnabled
	{
		get => (bool)_object.Get(PropertyName.AutomaticLoadingEnabled);
		set => _object.Set(PropertyName.AutomaticLoadingEnabled, value);
	}

	public bool RunStreamInEditor
	{
		get => (bool)_object.Get(PropertyName.RunStreamInEditor);
		set => _object.Set(PropertyName.RunStreamInEditor, value);
	}

	public int MeshBlockSize
	{
		get => (int)_object.Get(PropertyName.MeshBlockSize);
		set => _object.Set(PropertyName.MeshBlockSize, value);
	}

	public bool UseGpuGeneration
	{
		get => (bool)_object.Get(PropertyName.UseGpuGeneration);
		set => _object.Set(PropertyName.UseGpuGeneration, value);
	}

	public bool DebugDrawEnabled
	{
		get => (bool)_object.Get(PropertyName.DebugDrawEnabled);
		set => _object.Set(PropertyName.DebugDrawEnabled, value);
	}

	public bool DebugDrawVolumeBounds
	{
		get => (bool)_object.Get(PropertyName.DebugDrawVolumeBounds);
		set => _object.Set(PropertyName.DebugDrawVolumeBounds, value);
	}

	public bool DebugDrawVisualAndCollisionBlocks
	{
		get => (bool)_object.Get(PropertyName.DebugDrawVisualAndCollisionBlocks);
		set => _object.Set(PropertyName.DebugDrawVisualAndCollisionBlocks, value);
	}

	public bool DebugDrawVoxelMetadata
	{
		get => (bool)_object.Get(PropertyName.DebugDrawVoxelMetadata);
		set => _object.Set(PropertyName.DebugDrawVoxelMetadata, value);
	}

	public bool DebugDrawShadowOccluders
	{
		get => (bool)_object.Get(PropertyName.DebugDrawShadowOccluders);
		set => _object.Set(PropertyName.DebugDrawShadowOccluders, value);
	}

	#endregion

	#region Methods

	public void SetMaterialOverride(Material @material)
	{
		_object.Call(MethodName.SetMaterialOverride, @material);
	}

	public Material GetMaterialOverride()
	{
		return (Material)_object.Call(MethodName.GetMaterialOverride);
	}

	public void SetMaxViewDistance(int @distance_in_voxels)
	{
		_object.Call(MethodName.SetMaxViewDistance, @distance_in_voxels);
	}

	public int GetMaxViewDistance()
	{
		return (int)_object.Call(MethodName.GetMaxViewDistance);
	}

	public void SetBlockEnterNotificationEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetBlockEnterNotificationEnabled, @enabled);
	}

	public bool IsBlockEnterNotificationEnabled()
	{
		return (bool)_object.Call(MethodName.IsBlockEnterNotificationEnabled);
	}

	public void SetAreaEditNotificationEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAreaEditNotificationEnabled, @enabled);
	}

	public bool IsAreaEditNotificationEnabled()
	{
		return (bool)_object.Call(MethodName.IsAreaEditNotificationEnabled);
	}

	public bool GetGenerateCollisions()
	{
		return (bool)_object.Call(MethodName.GetGenerateCollisions);
	}

	public void SetGenerateCollisions(bool @enabled)
	{
		_object.Call(MethodName.SetGenerateCollisions, @enabled);
	}

	public int GetCollisionLayer()
	{
		return (int)_object.Call(MethodName.GetCollisionLayer);
	}

	public void SetCollisionLayer(int @layer)
	{
		_object.Call(MethodName.SetCollisionLayer, @layer);
	}

	public int GetCollisionMask()
	{
		return (int)_object.Call(MethodName.GetCollisionMask);
	}

	public void SetCollisionMask(int @mask)
	{
		_object.Call(MethodName.SetCollisionMask, @mask);
	}

	public float GetCollisionMargin()
	{
		return (float)_object.Call(MethodName.GetCollisionMargin);
	}

	public void SetCollisionMargin(float @margin)
	{
		_object.Call(MethodName.SetCollisionMargin, @margin);
	}

	public Godot.Vector3I VoxelToDataBlock(Godot.Vector3 @voxel_pos)
	{
		return (Godot.Vector3I)_object.Call(MethodName.VoxelToDataBlock, @voxel_pos);
	}

	public Godot.Vector3I DataBlockToVoxel(Godot.Vector3I @block_pos)
	{
		return (Godot.Vector3I)_object.Call(MethodName.DataBlockToVoxel, @block_pos);
	}

	public int GetDataBlockSize()
	{
		return (int)_object.Call(MethodName.GetDataBlockSize);
	}

	public int GetMeshBlockSize()
	{
		return (int)_object.Call(MethodName.GetMeshBlockSize);
	}

	public void SetMeshBlockSize(int @size)
	{
		_object.Call(MethodName.SetMeshBlockSize, @size);
	}

	public Godot.Collections.Dictionary GetStatistics()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetStatistics);
	}

	public VoxelTool GetVoxelTool()
	{
		return (VoxelTool)_object.Call(MethodName.GetVoxelTool);
	}

	public VoxelSaveCompletionTracker SaveModifiedBlocks()
	{
		return (VoxelSaveCompletionTracker)_object.Call(MethodName.SaveModifiedBlocks);
	}

	public void SaveBlock(Godot.Vector3I @position)
	{
		_object.Call(MethodName.SaveBlock, @position);
	}

	public void SetRunStreamInEditor(bool @enable)
	{
		_object.Call(MethodName.SetRunStreamInEditor, @enable);
	}

	public bool IsStreamRunningInEditor()
	{
		return (bool)_object.Call(MethodName.IsStreamRunningInEditor);
	}

	public void SetAutomaticLoadingEnabled(bool @enable)
	{
		_object.Call(MethodName.SetAutomaticLoadingEnabled, @enable);
	}

	public bool IsAutomaticLoadingEnabled()
	{
		return (bool)_object.Call(MethodName.IsAutomaticLoadingEnabled);
	}

	public void SetGeneratorUseGpu(bool @enable)
	{
		_object.Call(MethodName.SetGeneratorUseGpu, @enable);
	}

	public bool GetGeneratorUseGpu()
	{
		return (bool)_object.Call(MethodName.GetGeneratorUseGpu);
	}

	public void SetBounds(Godot.Aabb @bounds)
	{
		_object.Call(MethodName.SetBounds, @bounds);
	}

	public Godot.Aabb GetBounds()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetBounds);
	}

	public bool TrySetBlockData(Godot.Vector3I @position, VoxelBuffer @voxels)
	{
		return (bool)_object.Call(MethodName.TrySetBlockData, @position, @voxels);
	}

	public int[] GetViewerNetworkPeerIdsInArea(Godot.Vector3I @area_origin, Godot.Vector3I @area_size)
	{
		return (int[])_object.Call(MethodName.GetViewerNetworkPeerIdsInArea, @area_origin, @area_size);
	}

	public bool HasDataBlock(Godot.Vector3I @block_position)
	{
		return (bool)_object.Call(MethodName.HasDataBlock, @block_position);
	}

	public bool IsAreaMeshed(Godot.Aabb @area_in_voxels)
	{
		return (bool)_object.Call(MethodName.IsAreaMeshed, @area_in_voxels);
	}

	public void DebugSetDrawEnabled(bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawEnabled, @enabled);
	}

	public bool DebugIsDrawEnabled()
	{
		return (bool)_object.Call(MethodName.DebugIsDrawEnabled);
	}

	public void DebugSetDrawFlag(VoxelTerrain.DebugDrawFlag @flag_index, bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawFlag, (int)@flag_index, @enabled);
	}

	public bool DebugGetDrawFlag(VoxelTerrain.DebugDrawFlag @flag_index)
	{
		return (bool)_object.Call(MethodName.DebugGetDrawFlag, (int)@flag_index);
	}

	public void DebugSetDrawShadowOccluders(bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawShadowOccluders, @enabled);
	}

	public bool DebugGetDrawShadowOccluders()
	{
		return (bool)_object.Call(MethodName.DebugGetDrawShadowOccluders);
	}

	#endregion

	#region Signals

	public event Action<Godot.Vector3I> BlockLoaded
	{
		add
		{
			Connect(SignalName.BlockLoaded, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.BlockLoaded, Callable.From(value));
		}
	}

	public event Action<Godot.Vector3I> BlockUnloaded
	{
		add
		{
			Connect(SignalName.BlockUnloaded, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.BlockUnloaded, Callable.From(value));
		}
	}

	public event Action<Godot.Vector3I> MeshBlockEntered
	{
		add
		{
			Connect(SignalName.MeshBlockEntered, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.MeshBlockEntered, Callable.From(value));
		}
	}

	public event Action<Godot.Vector3I> MeshBlockExited
	{
		add
		{
			Connect(SignalName.MeshBlockExited, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.MeshBlockExited, Callable.From(value));
		}
	}

	#endregion
}
























