// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorMultipassCB : VoxelGenerator
{
	public VoxelGeneratorMultipassCB() : base(NativeName)
	{
	}
	protected VoxelGeneratorMultipassCB(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorMultipassCB(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorMultipassCB([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorMultipassCB self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorMultipassCB self) => self?._object;
	public static explicit operator VoxelGeneratorMultipassCB(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGenerator.PropertyName
	{
		public static readonly StringName ColumnBaseYBlocks = "column_base_y_blocks";
		public static readonly StringName ColumnHeightBlocks = "column_height_blocks";
		public static readonly StringName PassCount = "pass_count";
	}

	public new class MethodName : VoxelGenerator.MethodName
	{
		public static readonly StringName GetPassCount = "get_pass_count";
		public static readonly StringName SetPassCount = "set_pass_count";
		public static readonly StringName GetPassExtentBlocks = "get_pass_extent_blocks";
		public static readonly StringName SetPassExtentBlocks = "set_pass_extent_blocks";
		public static readonly StringName GetColumnBaseYBlocks = "get_column_base_y_blocks";
		public static readonly StringName SetColumnBaseYBlocks = "set_column_base_y_blocks";
		public static readonly StringName GetColumnHeightBlocks = "get_column_height_blocks";
		public static readonly StringName SetColumnHeightBlocks = "set_column_height_blocks";
		public static readonly StringName DebugGenerateTestColumn = "debug_generate_test_column";
	}

	public new class SignalName : VoxelGenerator.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorMultipassCB";

	#region Integer Constants

	public const long MaxPasses = 4L;

	public const long MaxPassExtent = 2L;

	#endregion

	#region Properties

	public int ColumnBaseYBlocks
	{
		get => (int)_object.Get(PropertyName.ColumnBaseYBlocks);
		set => _object.Set(PropertyName.ColumnBaseYBlocks, value);
	}

	public int ColumnHeightBlocks
	{
		get => (int)_object.Get(PropertyName.ColumnHeightBlocks);
		set => _object.Set(PropertyName.ColumnHeightBlocks, value);
	}

	public int PassCount
	{
		get => (int)_object.Get(PropertyName.PassCount);
		set => _object.Set(PropertyName.PassCount, value);
	}

	#endregion

	#region Methods

	public int GetPassCount()
	{
		return (int)_object.Call(MethodName.GetPassCount);
	}

	public void SetPassCount(int @count)
	{
		_object.Call(MethodName.SetPassCount, @count);
	}

	public int GetPassExtentBlocks(int @pass_index)
	{
		return (int)_object.Call(MethodName.GetPassExtentBlocks, @pass_index);
	}

	public void SetPassExtentBlocks(int @pass_index, int @extent)
	{
		_object.Call(MethodName.SetPassExtentBlocks, @pass_index, @extent);
	}

	public int GetColumnBaseYBlocks()
	{
		return (int)_object.Call(MethodName.GetColumnBaseYBlocks);
	}

	public void SetColumnBaseYBlocks(int @y)
	{
		_object.Call(MethodName.SetColumnBaseYBlocks, @y);
	}

	public int GetColumnHeightBlocks()
	{
		return (int)_object.Call(MethodName.GetColumnHeightBlocks);
	}

	public void SetColumnHeightBlocks(int @y)
	{
		_object.Call(MethodName.SetColumnHeightBlocks, @y);
	}

	public Godot.Collections.Array DebugGenerateTestColumn(Godot.Vector2I @column_position_blocks)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.DebugGenerateTestColumn, @column_position_blocks);
	}

	#endregion
}
























