#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelInstanceLibraryEditorPlugin : ZN_EditorPlugin
{
	public VoxelInstanceLibraryEditorPlugin() : base(NativeName)
	{
	}
	protected VoxelInstanceLibraryEditorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelInstanceLibraryEditorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelInstanceLibraryEditorPlugin([NotNull] EditorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorPlugin(VoxelInstanceLibraryEditorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelInstanceLibraryEditorPlugin self) => self?._object;
	public static explicit operator VoxelInstanceLibraryEditorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelInstanceLibraryEditorPlugin";
}
#endif
























