// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelModifierMesh : VoxelModifier
{
	public VoxelModifierMesh() : base(NativeName)
	{
	}
	protected VoxelModifierMesh(StringName @class) : base(@class)
	{
	}
	protected VoxelModifierMesh(Variant variant) : base(variant)
	{
	}
	protected VoxelModifierMesh([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(VoxelModifierMesh self) => self?._object;
	public static implicit operator Variant(VoxelModifierMesh self) => self?._object;
	public static explicit operator VoxelModifierMesh(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelModifier.PropertyName
	{
		public static readonly StringName MeshSdf = "mesh_sdf";
		public static readonly StringName Isolevel = "isolevel";
	}

	public new class MethodName : VoxelModifier.MethodName
	{
		public static readonly StringName SetMeshSdf = "set_mesh_sdf";
		public static readonly StringName GetMeshSdf = "get_mesh_sdf";
		public static readonly StringName SetIsolevel = "set_isolevel";
		public static readonly StringName GetIsolevel = "get_isolevel";
	}

	public new class SignalName : VoxelModifier.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelModifierMesh";

	#region Properties

	public VoxelMeshSDF MeshSdf
	{
		get => (VoxelMeshSDF)_object.Get(PropertyName.MeshSdf);
		set => _object.Set(PropertyName.MeshSdf, value);
	}

	public float Isolevel
	{
		get => (float)_object.Get(PropertyName.Isolevel);
		set => _object.Set(PropertyName.Isolevel, value);
	}

	#endregion

	#region Methods

	public void SetMeshSdf(VoxelMeshSDF @mesh_sdf)
	{
		_object.Call(MethodName.SetMeshSdf, @mesh_sdf);
	}

	public VoxelMeshSDF GetMeshSdf()
	{
		return (VoxelMeshSDF)_object.Call(MethodName.GetMeshSdf);
	}

	public void SetIsolevel(float @isolevel)
	{
		_object.Call(MethodName.SetIsolevel, @isolevel);
	}

	public float GetIsolevel()
	{
		return (float)_object.Call(MethodName.GetIsolevel);
	}

	#endregion
}
























