// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyAttributeCustom : VoxelBlockyAttribute
{
	public VoxelBlockyAttributeCustom() : base(NativeName)
	{
	}
	protected VoxelBlockyAttributeCustom(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyAttributeCustom(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyAttributeCustom([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelBlockyAttributeCustom self) => self?._object;
	public static implicit operator Variant(VoxelBlockyAttributeCustom self) => self?._object;
	public static explicit operator VoxelBlockyAttributeCustom(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelBlockyAttribute.PropertyName
	{
		public static readonly StringName AttributeName = "attribute_name";
		public static readonly StringName ValueCount = "value_count";
		public static readonly StringName DefaultValue = "default_value";
	}

	public new class MethodName : VoxelBlockyAttribute.MethodName
	{
		public static readonly StringName SetAttributeName = "set_attribute_name";
		public static readonly StringName SetValueCount = "set_value_count";
		public static readonly StringName SetValueName = "set_value_name";
		public static readonly StringName SetDefaultValue = "set_default_value";
	}

	public new class SignalName : VoxelBlockyAttribute.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyAttributeCustom";

	#region Properties

	public Godot.StringName AttributeName
	{
		get => (Godot.StringName)_object.Get(PropertyName.AttributeName);
		set => _object.Set(PropertyName.AttributeName, value);
	}

	public int ValueCount
	{
		get => (int)_object.Get(PropertyName.ValueCount);
		set => _object.Set(PropertyName.ValueCount, value);
	}

	public int DefaultValue
	{
		get => (int)_object.Get(PropertyName.DefaultValue);
		set => _object.Set(PropertyName.DefaultValue, value);
	}

	#endregion

	#region Methods

	public void SetAttributeName(Godot.StringName @name)
	{
		_object.Call(MethodName.SetAttributeName, @name);
	}

	public void SetValueCount(int @count)
	{
		_object.Call(MethodName.SetValueCount, @count);
	}

	public void SetValueName(int @value, Godot.StringName @value_name)
	{
		_object.Call(MethodName.SetValueName, @value, @value_name);
	}

	public void SetDefaultValue(int @value)
	{
		_object.Call(MethodName.SetDefaultValue, @value);
	}

	#endregion
}
























