#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyTypeLibraryEditorInspectorPlugin : ZN_EditorInspectorPlugin
{
	public VoxelBlockyTypeLibraryEditorInspectorPlugin() : base(NativeName)
	{
	}
	protected VoxelBlockyTypeLibraryEditorInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyTypeLibraryEditorInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyTypeLibraryEditorInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(VoxelBlockyTypeLibraryEditorInspectorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelBlockyTypeLibraryEditorInspectorPlugin self) => self?._object;
	public static explicit operator VoxelBlockyTypeLibraryEditorInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyTypeLibraryEditorInspectorPlugin";
}
#endif
























