// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelToolLodTerrain : VoxelTool
{
	public VoxelToolLodTerrain() : base(NativeName)
	{
	}
	protected VoxelToolLodTerrain(StringName @class) : base(@class)
	{
	}
	protected VoxelToolLodTerrain(Variant variant) : base(variant)
	{
	}
	protected VoxelToolLodTerrain([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(VoxelToolLodTerrain self) => self?._object;
	public static implicit operator Variant(VoxelToolLodTerrain self) => self?._object;
	public static explicit operator VoxelToolLodTerrain(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelTool.PropertyName
	{

	}

	public new class MethodName : VoxelTool.MethodName
	{
		public static readonly StringName SetRaycastBinarySearchIterations = "set_raycast_binary_search_iterations";
		public static readonly StringName GetRaycastBinarySearchIterations = "get_raycast_binary_search_iterations";
		public static readonly StringName GetVoxelFInterpolated = "get_voxel_f_interpolated";
		public static readonly StringName SeparateFloatingChunks = "separate_floating_chunks";
		public static readonly StringName DoSphereAsync = "do_sphere_async";
		public static readonly StringName StampSdf = "stamp_sdf";
		public static readonly StringName DoGraph = "do_graph";
		public static readonly StringName DoHemisphere = "do_hemisphere";
		public static readonly StringName RunBlockyRandomTick = "run_blocky_random_tick";
	}

	public new class SignalName : VoxelTool.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelToolLodTerrain";

	#region Methods

	public void SetRaycastBinarySearchIterations(int @iterations)
	{
		_object.Call(MethodName.SetRaycastBinarySearchIterations, @iterations);
	}

	public int GetRaycastBinarySearchIterations()
	{
		return (int)_object.Call(MethodName.GetRaycastBinarySearchIterations);
	}

	public float GetVoxelFInterpolated(Godot.Vector3 @position)
	{
		return (float)_object.Call(MethodName.GetVoxelFInterpolated, @position);
	}

	public Godot.Collections.Array SeparateFloatingChunks(Godot.Aabb @box, GodotObject @parent_node)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.SeparateFloatingChunks, @box, @parent_node);
	}

	public void DoSphereAsync(Godot.Vector3 @center, float @radius)
	{
		_object.Call(MethodName.DoSphereAsync, @center, @radius);
	}

	public void StampSdf(VoxelMeshSDF @mesh_sdf, Godot.Transform3D @transform, float @isolevel, float @sdf_scale)
	{
		_object.Call(MethodName.StampSdf, @mesh_sdf, @transform, @isolevel, @sdf_scale);
	}

	public void DoGraph(VoxelGeneratorGraph @graph, Godot.Transform3D @transform, Godot.Vector3 @area_size)
	{
		_object.Call(MethodName.DoGraph, @graph, @transform, @area_size);
	}

	public void DoHemisphere(Godot.Vector3 @center, float @radius, Godot.Vector3 @flat_direction, float @smoothness = 0.0f)
	{
		_object.Call(MethodName.DoHemisphere, @center, @radius, @flat_direction, @smoothness);
	}

	public void RunBlockyRandomTick(Godot.Aabb @area, int @voxel_count, Godot.Callable @callback, int @batch_count = 16, int @tags_mask = -1)
	{
		_object.Call(MethodName.RunBlockyRandomTick, @area, @voxel_count, @callback, @batch_count, @tags_mask);
	}

	#endregion
}
























