// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelStreamRegionFiles : VoxelStream
{
	public VoxelStreamRegionFiles() : base(NativeName)
	{
	}
	protected VoxelStreamRegionFiles(StringName @class) : base(@class)
	{
	}
	protected VoxelStreamRegionFiles(Variant variant) : base(variant)
	{
	}
	protected VoxelStreamRegionFiles([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelStreamRegionFiles self) => self?._object;
	public static implicit operator Variant(VoxelStreamRegionFiles self) => self?._object;
	public static explicit operator VoxelStreamRegionFiles(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelStream.PropertyName
	{
		public static readonly StringName Directory = "directory";
		public static readonly StringName RegionSizePo2 = "region_size_po2";
		public static readonly StringName BlockSizePo2 = "block_size_po2";
		public static readonly StringName SectorSize = "sector_size";
	}

	public new class MethodName : VoxelStream.MethodName
	{
		public static readonly StringName SetDirectory = "set_directory";
		public static readonly StringName GetDirectory = "get_directory";
		public static readonly StringName GetBlockSizePo2 = "get_block_size_po2";
		public static readonly StringName GetRegionSize = "get_region_size";
		public static readonly StringName GetRegionSizePo2 = "get_region_size_po2";
		public static readonly StringName GetSectorSize = "get_sector_size";
		public static readonly StringName SetBlockSizePo2 = "set_block_size_po2";
		public static readonly StringName SetRegionSizePo2 = "set_region_size_po2";
		public static readonly StringName SetSectorSize = "set_sector_size";
		public static readonly StringName ConvertFiles = "convert_files";
	}

	public new class SignalName : VoxelStream.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelStreamRegionFiles";

	#region Properties

	public string Directory
	{
		get => (string)_object.Get(PropertyName.Directory);
		set => _object.Set(PropertyName.Directory, value);
	}

	public int RegionSizePo2
	{
		get => (int)_object.Get(PropertyName.RegionSizePo2);
		set => _object.Set(PropertyName.RegionSizePo2, value);
	}

	public int BlockSizePo2
	{
		get => (int)_object.Get(PropertyName.BlockSizePo2);
		set => _object.Set(PropertyName.BlockSizePo2, value);
	}

	public int SectorSize
	{
		get => (int)_object.Get(PropertyName.SectorSize);
		set => _object.Set(PropertyName.SectorSize, value);
	}

	#endregion

	#region Methods

	public void SetDirectory(string @directory)
	{
		_object.Call(MethodName.SetDirectory, @directory);
	}

	public string GetDirectory()
	{
		return (string)_object.Call(MethodName.GetDirectory);
	}

	public int GetBlockSizePo2()
	{
		return (int)_object.Call(MethodName.GetBlockSizePo2);
	}

	public Godot.Vector3 GetRegionSize()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetRegionSize);
	}

	public int GetRegionSizePo2()
	{
		return (int)_object.Call(MethodName.GetRegionSizePo2);
	}

	public int GetSectorSize()
	{
		return (int)_object.Call(MethodName.GetSectorSize);
	}

	public void SetBlockSizePo2(int @_unnamed_arg0)
	{
		_object.Call(MethodName.SetBlockSizePo2, @_unnamed_arg0);
	}

	public void SetRegionSizePo2(int @_unnamed_arg0)
	{
		_object.Call(MethodName.SetRegionSizePo2, @_unnamed_arg0);
	}

	public void SetSectorSize(int @_unnamed_arg0)
	{
		_object.Call(MethodName.SetSectorSize, @_unnamed_arg0);
	}

	public void ConvertFiles(Godot.Collections.Dictionary @new_settings)
	{
		_object.Call(MethodName.ConvertFiles, @new_settings);
	}

	#endregion
}
























