// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyAttributeDirection : VoxelBlockyAttribute
{
	public VoxelBlockyAttributeDirection() : base(NativeName)
	{
	}
	protected VoxelBlockyAttributeDirection(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyAttributeDirection(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyAttributeDirection([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelBlockyAttributeDirection self) => self?._object;
	public static implicit operator Variant(VoxelBlockyAttributeDirection self) => self?._object;
	public static explicit operator VoxelBlockyAttributeDirection(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelBlockyAttribute.PropertyName
	{
		public static readonly StringName HorizontalOnly = "horizontal_only";
	}

	public new class MethodName : VoxelBlockyAttribute.MethodName
	{
		public static readonly StringName IsHorizontalOnly = "is_horizontal_only";
		public static readonly StringName SetHorizontalOnly = "set_horizontal_only";
		public static readonly StringName FromVec3 = "from_vec3";
	}

	public new class SignalName : VoxelBlockyAttribute.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyAttributeDirection";

	#region Enums

	public enum Direction : long
	{
		NegativeX = 0L,
		PositiveX = 1L,
		NegativeY = 2L,
		PositiveY = 3L,
		NegativeZ = 4L,
		PositiveZ = 5L,
		Count = 6L,
	}

	#endregion

	#region Properties

	public bool HorizontalOnly
	{
		get => (bool)_object.Get(PropertyName.HorizontalOnly);
		set => _object.Set(PropertyName.HorizontalOnly, value);
	}

	#endregion

	#region Methods

	public bool IsHorizontalOnly()
	{
		return (bool)_object.Call(MethodName.IsHorizontalOnly);
	}

	public void SetHorizontalOnly(bool @enabled)
	{
		_object.Call(MethodName.SetHorizontalOnly, @enabled);
	}

	public int FromVec3(Godot.Vector3 @v)
	{
		return (int)_object.Call(MethodName.FromVec3, @v);
	}

	#endregion
}
























