#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelVoxSceneImporter : ZN_EditorImportPlugin
{
	public VoxelVoxSceneImporter() : base(NativeName)
	{
	}
	protected VoxelVoxSceneImporter(StringName @class) : base(@class)
	{
	}
	protected VoxelVoxSceneImporter(Variant variant) : base(variant)
	{
	}
	protected VoxelVoxSceneImporter([NotNull] EditorImportPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorImportPlugin(VoxelVoxSceneImporter self) => self?._object;
	public static implicit operator Variant(VoxelVoxSceneImporter self) => self?._object;
	public static explicit operator VoxelVoxSceneImporter(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorImportPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorImportPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorImportPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelVoxSceneImporter";
}
#endif
























