#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelTerrainEditorInspectorPlugin : ZN_EditorInspectorPlugin
{
	public VoxelTerrainEditorInspectorPlugin() : base(NativeName)
	{
	}
	protected VoxelTerrainEditorInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelTerrainEditorInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelTerrainEditorInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(VoxelTerrainEditorInspectorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelTerrainEditorInspectorPlugin self) => self?._object;
	public static explicit operator VoxelTerrainEditorInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelTerrainEditorInspectorPlugin";
}
#endif
























