// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorFlat : VoxelGenerator
{
	public VoxelGeneratorFlat() : base(NativeName)
	{
	}
	protected VoxelGeneratorFlat(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorFlat(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorFlat([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorFlat self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorFlat self) => self?._object;
	public static explicit operator VoxelGeneratorFlat(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGenerator.PropertyName
	{
		public static readonly StringName Channel = "channel";
		public static readonly StringName Height = "height";
		public static readonly StringName VoxelType = "voxel_type";
	}

	public new class MethodName : VoxelGenerator.MethodName
	{
		public static readonly StringName SetChannel = "set_channel";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName SetVoxelType = "set_voxel_type";
		public static readonly StringName GetVoxelType = "get_voxel_type";
		public static readonly StringName SetHeight = "set_height";
		public static readonly StringName GetHeight = "get_height";
	}

	public new class SignalName : VoxelGenerator.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorFlat";

	#region Properties

	public int Channel
	{
		get => (int)_object.Get(PropertyName.Channel);
		set => _object.Set(PropertyName.Channel, value);
	}

	public float Height
	{
		get => (float)_object.Get(PropertyName.Height);
		set => _object.Set(PropertyName.Height, value);
	}

	public int VoxelType
	{
		get => (int)_object.Get(PropertyName.VoxelType);
		set => _object.Set(PropertyName.VoxelType, value);
	}

	#endregion

	#region Methods

	public void SetChannel(VoxelBuffer.ChannelId @channel)
	{
		_object.Call(MethodName.SetChannel, (int)@channel);
	}

	public VoxelBuffer.ChannelId GetChannel()
	{
		return (VoxelBuffer.ChannelId)(int)_object.Call(MethodName.GetChannel);
	}

	public void SetVoxelType(int @id)
	{
		_object.Call(MethodName.SetVoxelType, @id);
	}

	public int GetVoxelType()
	{
		return (int)_object.Call(MethodName.GetVoxelType);
	}

	public void SetHeight(float @h)
	{
		_object.Call(MethodName.SetHeight, @h);
	}

	public float GetHeight()
	{
		return (float)_object.Call(MethodName.GetHeight);
	}

	#endregion
}
























