// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorHeightmap : VoxelGenerator
{
	public VoxelGeneratorHeightmap() : base(NativeName)
	{
	}
	protected VoxelGeneratorHeightmap(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorHeightmap(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorHeightmap([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorHeightmap self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorHeightmap self) => self?._object;
	public static explicit operator VoxelGeneratorHeightmap(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGenerator.PropertyName
	{
		public static readonly StringName Channel = "channel";
		public static readonly StringName HeightStart = "height_start";
		public static readonly StringName HeightRange = "height_range";
		public static readonly StringName Offset = "offset";
		public static readonly StringName IsoScale = "iso_scale";
	}

	public new class MethodName : VoxelGenerator.MethodName
	{
		public static readonly StringName SetChannel = "set_channel";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName SetHeightStart = "set_height_start";
		public static readonly StringName GetHeightStart = "get_height_start";
		public static readonly StringName SetHeightRange = "set_height_range";
		public static readonly StringName GetHeightRange = "get_height_range";
		public static readonly StringName SetIsoScale = "set_iso_scale";
		public static readonly StringName GetIsoScale = "get_iso_scale";
		public static readonly StringName SetOffset = "set_offset";
		public static readonly StringName GetOffset = "get_offset";
	}

	public new class SignalName : VoxelGenerator.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorHeightmap";

	#region Properties

	public int Channel
	{
		get => (int)_object.Get(PropertyName.Channel);
		set => _object.Set(PropertyName.Channel, value);
	}

	public float HeightStart
	{
		get => (float)_object.Get(PropertyName.HeightStart);
		set => _object.Set(PropertyName.HeightStart, value);
	}

	public float HeightRange
	{
		get => (float)_object.Get(PropertyName.HeightRange);
		set => _object.Set(PropertyName.HeightRange, value);
	}

	public Godot.Vector2I Offset
	{
		get => (Godot.Vector2I)_object.Get(PropertyName.Offset);
		set => _object.Set(PropertyName.Offset, value);
	}

	public float IsoScale
	{
		get => (float)_object.Get(PropertyName.IsoScale);
		set => _object.Set(PropertyName.IsoScale, value);
	}

	#endregion

	#region Methods

	public void SetChannel(VoxelBuffer.ChannelId @channel)
	{
		_object.Call(MethodName.SetChannel, (int)@channel);
	}

	public VoxelBuffer.ChannelId GetChannel()
	{
		return (VoxelBuffer.ChannelId)(int)_object.Call(MethodName.GetChannel);
	}

	public void SetHeightStart(float @start)
	{
		_object.Call(MethodName.SetHeightStart, @start);
	}

	public float GetHeightStart()
	{
		return (float)_object.Call(MethodName.GetHeightStart);
	}

	public void SetHeightRange(float @range)
	{
		_object.Call(MethodName.SetHeightRange, @range);
	}

	public float GetHeightRange()
	{
		return (float)_object.Call(MethodName.GetHeightRange);
	}

	public void SetIsoScale(float @scale)
	{
		_object.Call(MethodName.SetIsoScale, @scale);
	}

	public float GetIsoScale()
	{
		return (float)_object.Call(MethodName.GetIsoScale);
	}

	public void SetOffset(Godot.Vector2I @offset)
	{
		_object.Call(MethodName.SetOffset, @offset);
	}

	public Godot.Vector2I GetOffset()
	{
		return (Godot.Vector2I)_object.Call(MethodName.GetOffset);
	}

	#endregion
}
























