#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelMeshSDFEditorPlugin : ZN_EditorPlugin
{
	public VoxelMeshSDFEditorPlugin() : base(NativeName)
	{
	}
	protected VoxelMeshSDFEditorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelMeshSDFEditorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelMeshSDFEditorPlugin([NotNull] EditorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorPlugin(VoxelMeshSDFEditorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelMeshSDFEditorPlugin self) => self?._object;
	public static explicit operator VoxelMeshSDFEditorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelMeshSDFEditorPlugin";
}
#endif
























