// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyTypeLibrary : VoxelBlockyLibraryBase
{
	public VoxelBlockyTypeLibrary() : base(NativeName)
	{
	}
	protected VoxelBlockyTypeLibrary(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyTypeLibrary(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyTypeLibrary([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelBlockyTypeLibrary self) => self?._object;
	public static implicit operator Variant(VoxelBlockyTypeLibrary self) => self?._object;
	public static explicit operator VoxelBlockyTypeLibrary(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelBlockyLibraryBase.PropertyName
	{
		public static readonly StringName Types = "types";
		public static readonly StringName IdMapData = "_id_map_data";
	}

	public new class MethodName : VoxelBlockyLibraryBase.MethodName
	{
		public static readonly StringName GetTypes = "get_types";
		public static readonly StringName SetTypes = "set_types";
		public static readonly StringName GetModelIndexDefault = "get_model_index_default";
		public static readonly StringName GetModelIndexSingleAttribute = "get_model_index_single_attribute";
		public static readonly StringName GetModelIndexWithAttributes = "get_model_index_with_attributes";
		public static readonly StringName GetTypeNameAndAttributesFromModelIndex = "get_type_name_and_attributes_from_model_index";
		public static readonly StringName LoadIdMapFromJson = "load_id_map_from_json";
		public static readonly StringName SerializeIdMapToJson = "serialize_id_map_to_json";
		public static readonly StringName LoadIdMapFromStringArray = "load_id_map_from_string_array";
		public static readonly StringName SerializeIdMapToStringArray = "serialize_id_map_to_string_array";
		public static readonly StringName GetTypeFromName = "get_type_from_name";
	}

	public new class SignalName : VoxelBlockyLibraryBase.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyTypeLibrary";

	#region Properties

	public Godot.Collections.Array Types
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Types);
		set => _object.Set(PropertyName.Types, value);
	}

	public string[] IdMapData
	{
		get => (string[])_object.Get(PropertyName.IdMapData);
		set => _object.Set(PropertyName.IdMapData, value);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetTypes()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetTypes);
	}

	public void SetTypes(Godot.Collections.Array @_unnamed_arg0)
	{
		_object.Call(MethodName.SetTypes, @_unnamed_arg0);
	}

	public int GetModelIndexDefault(Godot.StringName @type_name)
	{
		return (int)_object.Call(MethodName.GetModelIndexDefault, @type_name);
	}

	public int GetModelIndexSingleAttribute(Godot.StringName @type_name, Variant @attrib_value)
	{
		return (int)_object.Call(MethodName.GetModelIndexSingleAttribute, @type_name, @attrib_value);
	}

	public int GetModelIndexWithAttributes(Godot.StringName @type_name, Godot.Collections.Dictionary @attribs_dict)
	{
		return (int)_object.Call(MethodName.GetModelIndexWithAttributes, @type_name, @attribs_dict);
	}

	public Godot.Collections.Array GetTypeNameAndAttributesFromModelIndex(int @model_index)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetTypeNameAndAttributesFromModelIndex, @model_index);
	}

	public bool LoadIdMapFromJson(string @json)
	{
		return (bool)_object.Call(MethodName.LoadIdMapFromJson, @json);
	}

	public string SerializeIdMapToJson()
	{
		return (string)_object.Call(MethodName.SerializeIdMapToJson);
	}

	public bool LoadIdMapFromStringArray(string[] @str_array)
	{
		return (bool)_object.Call(MethodName.LoadIdMapFromStringArray, @str_array);
	}

	public string[] SerializeIdMapToStringArray()
	{
		return (string[])_object.Call(MethodName.SerializeIdMapToStringArray);
	}

	public VoxelBlockyType GetTypeFromName(Godot.StringName @type_name)
	{
		return (VoxelBlockyType)_object.Call(MethodName.GetTypeFromName, @type_name);
	}

	#endregion
}
























