// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelMesherTransvoxel : VoxelMesher
{
	public VoxelMesherTransvoxel() : base(NativeName)
	{
	}
	protected VoxelMesherTransvoxel(StringName @class) : base(@class)
	{
	}
	protected VoxelMesherTransvoxel(Variant variant) : base(variant)
	{
	}
	protected VoxelMesherTransvoxel([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelMesherTransvoxel self) => self?._object;
	public static implicit operator Variant(VoxelMesherTransvoxel self) => self?._object;
	public static explicit operator VoxelMesherTransvoxel(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelMesher.PropertyName
	{
		public static readonly StringName TexturingMode = "texturing_mode";
		public static readonly StringName TexturesIgnoreAirVoxels = "textures_ignore_air_voxels";
		public static readonly StringName MeshOptimizationEnabled = "mesh_optimization_enabled";
		public static readonly StringName MeshOptimizationErrorThreshold = "mesh_optimization_error_threshold";
		public static readonly StringName MeshOptimizationTargetRatio = "mesh_optimization_target_ratio";
		public static readonly StringName TransitionsEnabled = "transitions_enabled";
		public static readonly StringName EdgeClampMargin = "edge_clamp_margin";
	}

	public new class MethodName : VoxelMesher.MethodName
	{
		public static readonly StringName BuildTransitionMesh = "build_transition_mesh";
		public static readonly StringName SetTexturingMode = "set_texturing_mode";
		public static readonly StringName GetTexturingMode = "get_texturing_mode";
		public static readonly StringName SetTexturesIgnoreAirVoxels = "set_textures_ignore_air_voxels";
		public static readonly StringName GetTexturesIgnoreAirVoxels = "get_textures_ignore_air_voxels";
		public static readonly StringName SetMeshOptimizationEnabled = "set_mesh_optimization_enabled";
		public static readonly StringName IsMeshOptimizationEnabled = "is_mesh_optimization_enabled";
		public static readonly StringName SetMeshOptimizationErrorThreshold = "set_mesh_optimization_error_threshold";
		public static readonly StringName GetMeshOptimizationErrorThreshold = "get_mesh_optimization_error_threshold";
		public static readonly StringName SetMeshOptimizationTargetRatio = "set_mesh_optimization_target_ratio";
		public static readonly StringName GetMeshOptimizationTargetRatio = "get_mesh_optimization_target_ratio";
		public static readonly StringName SetTransitionsEnabled = "set_transitions_enabled";
		public static readonly StringName GetTransitionsEnabled = "get_transitions_enabled";
		public static readonly StringName GetEdgeClampMargin = "get_edge_clamp_margin";
		public static readonly StringName SetEdgeClampMargin = "set_edge_clamp_margin";
	}

	public new class SignalName : VoxelMesher.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelMesherTransvoxel";

	#region Enums

	public enum TexturingModeEnum : long
	{
		None = 0L,
		Mixel4S4 = 1L,
		SingleS4 = 2L,
	}

	#endregion

	#region Integer Constants

	public const long TexturesBlend4Over16 = 1L;

	#endregion

	#region Properties

	public int TexturingMode
	{
		get => (int)_object.Get(PropertyName.TexturingMode);
		set => _object.Set(PropertyName.TexturingMode, value);
	}

	public bool TexturesIgnoreAirVoxels
	{
		get => (bool)_object.Get(PropertyName.TexturesIgnoreAirVoxels);
		set => _object.Set(PropertyName.TexturesIgnoreAirVoxels, value);
	}

	public bool MeshOptimizationEnabled
	{
		get => (bool)_object.Get(PropertyName.MeshOptimizationEnabled);
		set => _object.Set(PropertyName.MeshOptimizationEnabled, value);
	}

	public float MeshOptimizationErrorThreshold
	{
		get => (float)_object.Get(PropertyName.MeshOptimizationErrorThreshold);
		set => _object.Set(PropertyName.MeshOptimizationErrorThreshold, value);
	}

	public float MeshOptimizationTargetRatio
	{
		get => (float)_object.Get(PropertyName.MeshOptimizationTargetRatio);
		set => _object.Set(PropertyName.MeshOptimizationTargetRatio, value);
	}

	public bool TransitionsEnabled
	{
		get => (bool)_object.Get(PropertyName.TransitionsEnabled);
		set => _object.Set(PropertyName.TransitionsEnabled, value);
	}

	public float EdgeClampMargin
	{
		get => (float)_object.Get(PropertyName.EdgeClampMargin);
		set => _object.Set(PropertyName.EdgeClampMargin, value);
	}

	#endregion

	#region Methods

	public ArrayMesh BuildTransitionMesh(VoxelBuffer @voxel_buffer, int @direction)
	{
		return (ArrayMesh)_object.Call(MethodName.BuildTransitionMesh, @voxel_buffer, @direction);
	}

	public void SetTexturingMode(VoxelMesherTransvoxel.TexturingModeEnum @mode)
	{
		_object.Call(MethodName.SetTexturingMode, (int)@mode);
	}

	public VoxelMesherTransvoxel.TexturingModeEnum GetTexturingMode()
	{
		return (VoxelMesherTransvoxel.TexturingModeEnum)(int)_object.Call(MethodName.GetTexturingMode);
	}

	public void SetTexturesIgnoreAirVoxels(bool @enabled)
	{
		_object.Call(MethodName.SetTexturesIgnoreAirVoxels, @enabled);
	}

	public bool GetTexturesIgnoreAirVoxels()
	{
		return (bool)_object.Call(MethodName.GetTexturesIgnoreAirVoxels);
	}

	public void SetMeshOptimizationEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetMeshOptimizationEnabled, @enabled);
	}

	public bool IsMeshOptimizationEnabled()
	{
		return (bool)_object.Call(MethodName.IsMeshOptimizationEnabled);
	}

	public void SetMeshOptimizationErrorThreshold(float @threshold)
	{
		_object.Call(MethodName.SetMeshOptimizationErrorThreshold, @threshold);
	}

	public float GetMeshOptimizationErrorThreshold()
	{
		return (float)_object.Call(MethodName.GetMeshOptimizationErrorThreshold);
	}

	public void SetMeshOptimizationTargetRatio(float @ratio)
	{
		_object.Call(MethodName.SetMeshOptimizationTargetRatio, @ratio);
	}

	public float GetMeshOptimizationTargetRatio()
	{
		return (float)_object.Call(MethodName.GetMeshOptimizationTargetRatio);
	}

	public void SetTransitionsEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetTransitionsEnabled, @enabled);
	}

	public bool GetTransitionsEnabled()
	{
		return (bool)_object.Call(MethodName.GetTransitionsEnabled);
	}

	public float GetEdgeClampMargin()
	{
		return (float)_object.Call(MethodName.GetEdgeClampMargin);
	}

	public void SetEdgeClampMargin(float @margin)
	{
		_object.Call(MethodName.SetEdgeClampMargin, @margin);
	}

	#endregion
}
























