// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorNoise : VoxelGenerator
{
	public VoxelGeneratorNoise() : base(NativeName)
	{
	}
	protected VoxelGeneratorNoise(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorNoise(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorNoise([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorNoise self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorNoise self) => self?._object;
	public static explicit operator VoxelGeneratorNoise(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGenerator.PropertyName
	{
		public static readonly StringName Channel = "channel";
		public static readonly StringName Noise = "noise";
		public static readonly StringName HeightStart = "height_start";
		public static readonly StringName HeightRange = "height_range";
	}

	public new class MethodName : VoxelGenerator.MethodName
	{
		public static readonly StringName SetChannel = "set_channel";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName SetNoise = "set_noise";
		public static readonly StringName GetNoise = "get_noise";
		public static readonly StringName SetHeightStart = "set_height_start";
		public static readonly StringName GetHeightStart = "get_height_start";
		public static readonly StringName SetHeightRange = "set_height_range";
		public static readonly StringName GetHeightRange = "get_height_range";
	}

	public new class SignalName : VoxelGenerator.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorNoise";

	#region Properties

	public int Channel
	{
		get => (int)_object.Get(PropertyName.Channel);
		set => _object.Set(PropertyName.Channel, value);
	}

	public FastNoiseLite Noise
	{
		get => (FastNoiseLite)_object.Get(PropertyName.Noise);
		set => _object.Set(PropertyName.Noise, value);
	}

	public float HeightStart
	{
		get => (float)_object.Get(PropertyName.HeightStart);
		set => _object.Set(PropertyName.HeightStart, value);
	}

	public float HeightRange
	{
		get => (float)_object.Get(PropertyName.HeightRange);
		set => _object.Set(PropertyName.HeightRange, value);
	}

	#endregion

	#region Methods

	public void SetChannel(VoxelBuffer.ChannelId @channel)
	{
		_object.Call(MethodName.SetChannel, (int)@channel);
	}

	public VoxelBuffer.ChannelId GetChannel()
	{
		return (VoxelBuffer.ChannelId)(int)_object.Call(MethodName.GetChannel);
	}

	public void SetNoise(FastNoiseLite @noise)
	{
		_object.Call(MethodName.SetNoise, @noise);
	}

	public FastNoiseLite GetNoise()
	{
		return (FastNoiseLite)_object.Call(MethodName.GetNoise);
	}

	public void SetHeightStart(float @hstart)
	{
		_object.Call(MethodName.SetHeightStart, @hstart);
	}

	public float GetHeightStart()
	{
		return (float)_object.Call(MethodName.GetHeightStart);
	}

	public void SetHeightRange(float @hrange)
	{
		_object.Call(MethodName.SetHeightRange, @hrange);
	}

	public float GetHeightRange()
	{
		return (float)_object.Call(MethodName.GetHeightRange);
	}

	#endregion
}
























