// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelMesherBlocky : VoxelMesher
{
	public VoxelMesherBlocky() : base(NativeName)
	{
	}
	protected VoxelMesherBlocky(StringName @class) : base(@class)
	{
	}
	protected VoxelMesherBlocky(Variant variant) : base(variant)
	{
	}
	protected VoxelMesherBlocky([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelMesherBlocky self) => self?._object;
	public static implicit operator Variant(VoxelMesherBlocky self) => self?._object;
	public static explicit operator VoxelMesherBlocky(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelMesher.PropertyName
	{
		public static readonly StringName Library = "library";
		public static readonly StringName OcclusionEnabled = "occlusion_enabled";
		public static readonly StringName OcclusionDarkness = "occlusion_darkness";
		public static readonly StringName TintMode = "tint_mode";
		public static readonly StringName ShadowOccluderNegativeX = "shadow_occluder_negative_x";
		public static readonly StringName ShadowOccluderPositiveX = "shadow_occluder_positive_x";
		public static readonly StringName ShadowOccluderNegativeY = "shadow_occluder_negative_y";
		public static readonly StringName ShadowOccluderPositiveY = "shadow_occluder_positive_y";
		public static readonly StringName ShadowOccluderNegativeZ = "shadow_occluder_negative_z";
		public static readonly StringName ShadowOccluderPositiveZ = "shadow_occluder_positive_z";
	}

	public new class MethodName : VoxelMesher.MethodName
	{
		public static readonly StringName SetLibrary = "set_library";
		public static readonly StringName GetLibrary = "get_library";
		public static readonly StringName SetOcclusionEnabled = "set_occlusion_enabled";
		public static readonly StringName GetOcclusionEnabled = "get_occlusion_enabled";
		public static readonly StringName SetOcclusionDarkness = "set_occlusion_darkness";
		public static readonly StringName GetOcclusionDarkness = "get_occlusion_darkness";
		public static readonly StringName SetShadowOccluderSide = "set_shadow_occluder_side";
		public static readonly StringName GetShadowOccluderSide = "get_shadow_occluder_side";
		public static readonly StringName SetTintMode = "set_tint_mode";
		public static readonly StringName GetTintMode = "get_tint_mode";
	}

	public new class SignalName : VoxelMesher.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelMesherBlocky";

	#region Enums

	public enum Side : long
	{
		NegativeX = 0L,
		PositiveX = 1L,
		NegativeY = 2L,
		PositiveY = 3L,
		NegativeZ = 4L,
		PositiveZ = 5L,
	}

	public enum TintModeEnum : long
	{
		None = 0L,
		RawColor = 1L,
	}

	#endregion

	#region Properties

	public VoxelBlockyLibraryBase Library
	{
		get => (VoxelBlockyLibraryBase)_object.Get(PropertyName.Library);
		set => _object.Set(PropertyName.Library, value);
	}

	public bool OcclusionEnabled
	{
		get => (bool)_object.Get(PropertyName.OcclusionEnabled);
		set => _object.Set(PropertyName.OcclusionEnabled, value);
	}

	public float OcclusionDarkness
	{
		get => (float)_object.Get(PropertyName.OcclusionDarkness);
		set => _object.Set(PropertyName.OcclusionDarkness, value);
	}

	public int TintMode
	{
		get => (int)_object.Get(PropertyName.TintMode);
		set => _object.Set(PropertyName.TintMode, value);
	}

	public bool ShadowOccluderNegativeX
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderNegativeX);
		set => _object.Set(PropertyName.ShadowOccluderNegativeX, value);
	}

	public bool ShadowOccluderPositiveX
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderPositiveX);
		set => _object.Set(PropertyName.ShadowOccluderPositiveX, value);
	}

	public bool ShadowOccluderNegativeY
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderNegativeY);
		set => _object.Set(PropertyName.ShadowOccluderNegativeY, value);
	}

	public bool ShadowOccluderPositiveY
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderPositiveY);
		set => _object.Set(PropertyName.ShadowOccluderPositiveY, value);
	}

	public bool ShadowOccluderNegativeZ
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderNegativeZ);
		set => _object.Set(PropertyName.ShadowOccluderNegativeZ, value);
	}

	public bool ShadowOccluderPositiveZ
	{
		get => (bool)_object.Get(PropertyName.ShadowOccluderPositiveZ);
		set => _object.Set(PropertyName.ShadowOccluderPositiveZ, value);
	}

	#endregion

	#region Methods

	public void SetLibrary(VoxelBlockyLibraryBase @voxel_library)
	{
		_object.Call(MethodName.SetLibrary, @voxel_library);
	}

	public VoxelBlockyLibraryBase GetLibrary()
	{
		return (VoxelBlockyLibraryBase)_object.Call(MethodName.GetLibrary);
	}

	public void SetOcclusionEnabled(bool @enable)
	{
		_object.Call(MethodName.SetOcclusionEnabled, @enable);
	}

	public bool GetOcclusionEnabled()
	{
		return (bool)_object.Call(MethodName.GetOcclusionEnabled);
	}

	public void SetOcclusionDarkness(float @value)
	{
		_object.Call(MethodName.SetOcclusionDarkness, @value);
	}

	public float GetOcclusionDarkness()
	{
		return (float)_object.Call(MethodName.GetOcclusionDarkness);
	}

	public void SetShadowOccluderSide(VoxelMesherBlocky.Side @side, bool @enabled)
	{
		_object.Call(MethodName.SetShadowOccluderSide, (int)@side, @enabled);
	}

	public bool GetShadowOccluderSide(VoxelMesherBlocky.Side @side)
	{
		return (bool)_object.Call(MethodName.GetShadowOccluderSide, (int)@side);
	}

	public void SetTintMode(VoxelMesherBlocky.TintModeEnum @mode)
	{
		_object.Call(MethodName.SetTintMode, (int)@mode);
	}

	public VoxelMesherBlocky.TintModeEnum GetTintMode()
	{
		return (VoxelMesherBlocky.TintModeEnum)(int)_object.Call(MethodName.GetTintMode);
	}

	#endregion
}
























