// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelStreamMemory : VoxelStream
{
	public VoxelStreamMemory() : base(NativeName)
	{
	}
	protected VoxelStreamMemory(StringName @class) : base(@class)
	{
	}
	protected VoxelStreamMemory(Variant variant) : base(variant)
	{
	}
	protected VoxelStreamMemory([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelStreamMemory self) => self?._object;
	public static implicit operator Variant(VoxelStreamMemory self) => self?._object;
	public static explicit operator VoxelStreamMemory(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelStream.PropertyName
	{
		public static readonly StringName ArtificialSaveLatencyUsec = "artificial_save_latency_usec";
	}

	public new class MethodName : VoxelStream.MethodName
	{
		public static readonly StringName SetArtificialSaveLatencyUsec = "set_artificial_save_latency_usec";
		public static readonly StringName GetArtificialSaveLatencyUsec = "get_artificial_save_latency_usec";
	}

	public new class SignalName : VoxelStream.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelStreamMemory";

	#region Properties

	public int ArtificialSaveLatencyUsec
	{
		get => (int)_object.Get(PropertyName.ArtificialSaveLatencyUsec);
		set => _object.Set(PropertyName.ArtificialSaveLatencyUsec, value);
	}

	#endregion

	#region Methods

	public void SetArtificialSaveLatencyUsec(int @usec)
	{
		_object.Call(MethodName.SetArtificialSaveLatencyUsec, @usec);
	}

	public int GetArtificialSaveLatencyUsec()
	{
		return (int)_object.Call(MethodName.GetArtificialSaveLatencyUsec);
	}

	#endregion
}
























