// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelInstanceGenerator
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public VoxelInstanceGenerator() : this(NativeName)
	{
	}
	protected VoxelInstanceGenerator(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected VoxelInstanceGenerator(Variant variant) : this((Resource) variant)
	{
	}
	protected VoxelInstanceGenerator([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(VoxelInstanceGenerator self) => self?._object;
	public static implicit operator Variant(VoxelInstanceGenerator self) => self?._object;
	public static explicit operator VoxelInstanceGenerator(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName EmitMode = "emit_mode";
		public static readonly StringName Density = "density";
		public static readonly StringName Jitter = "jitter";
		public static readonly StringName TriangleAreaThreshold = "triangle_area_threshold";
		public static readonly StringName MinScale = "min_scale";
		public static readonly StringName MaxScale = "max_scale";
		public static readonly StringName ScaleDistribution = "scale_distribution";
		public static readonly StringName VerticalAlignment = "vertical_alignment";
		public static readonly StringName RandomVerticalFlip = "random_vertical_flip";
		public static readonly StringName RandomRotation = "random_rotation";
		public static readonly StringName OffsetAlongNormal = "offset_along_normal";
		public static readonly StringName MinSlopeDegrees = "min_slope_degrees";
		public static readonly StringName MaxSlopeDegrees = "max_slope_degrees";
		public static readonly StringName MinSlopeFalloffDegrees = "min_slope_falloff_degrees";
		public static readonly StringName MaxSlopeFalloffDegrees = "max_slope_falloff_degrees";
		public static readonly StringName MinHeight = "min_height";
		public static readonly StringName MaxHeight = "max_height";
		public static readonly StringName MinHeightFalloff = "min_height_falloff";
		public static readonly StringName MaxHeightFalloff = "max_height_falloff";
		public static readonly StringName Noise = "noise";
		public static readonly StringName NoiseGraph = "noise_graph";
		public static readonly StringName NoiseFalloff = "noise_falloff";
		public static readonly StringName NoiseThreshold = "noise_threshold";
		public static readonly StringName NoiseDimension = "noise_dimension";
		public static readonly StringName NoiseOnScale = "noise_on_scale";
		public static readonly StringName VoxelTextureFilterEnabled = "voxel_texture_filter_enabled";
		public static readonly StringName VoxelTextureFilterArray = "voxel_texture_filter_array";
		public static readonly StringName VoxelTextureFilterThreshold = "voxel_texture_filter_threshold";
		public static readonly StringName SnapToGeneratorSdfEnabled = "snap_to_generator_sdf_enabled";
		public static readonly StringName SnapToGeneratorSdfSearchDistance = "snap_to_generator_sdf_search_distance";
		public static readonly StringName SnapToGeneratorSdfSampleCount = "snap_to_generator_sdf_sample_count";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetDensity = "set_density";
		public static readonly StringName GetDensity = "get_density";
		public static readonly StringName SetEmitMode = "set_emit_mode";
		public static readonly StringName GetEmitMode = "get_emit_mode";
		public static readonly StringName SetJitter = "set_jitter";
		public static readonly StringName GetJitter = "get_jitter";
		public static readonly StringName SetTriangleAreaThreshold = "set_triangle_area_threshold";
		public static readonly StringName GetTriangleAreaThreshold = "get_triangle_area_threshold";
		public static readonly StringName SetMinScale = "set_min_scale";
		public static readonly StringName GetMinScale = "get_min_scale";
		public static readonly StringName SetMaxScale = "set_max_scale";
		public static readonly StringName GetMaxScale = "get_max_scale";
		public static readonly StringName SetScaleDistribution = "set_scale_distribution";
		public static readonly StringName GetScaleDistribution = "get_scale_distribution";
		public static readonly StringName SetVerticalAlignment = "set_vertical_alignment";
		public static readonly StringName GetVerticalAlignment = "get_vertical_alignment";
		public static readonly StringName SetOffsetAlongNormal = "set_offset_along_normal";
		public static readonly StringName GetOffsetAlongNormal = "get_offset_along_normal";
		public static readonly StringName SetMinSlopeDegrees = "set_min_slope_degrees";
		public static readonly StringName GetMinSlopeDegrees = "get_min_slope_degrees";
		public static readonly StringName SetMaxSlopeDegrees = "set_max_slope_degrees";
		public static readonly StringName GetMaxSlopeDegrees = "get_max_slope_degrees";
		public static readonly StringName SetMinSlopeFalloffDegrees = "set_min_slope_falloff_degrees";
		public static readonly StringName GetMinSlopeFalloffDegrees = "get_min_slope_falloff_degrees";
		public static readonly StringName SetMaxSlopeFalloffDegrees = "set_max_slope_falloff_degrees";
		public static readonly StringName GetMaxSlopeFalloffDegrees = "get_max_slope_falloff_degrees";
		public static readonly StringName SetMinHeight = "set_min_height";
		public static readonly StringName GetMinHeight = "get_min_height";
		public static readonly StringName SetMaxHeight = "set_max_height";
		public static readonly StringName GetMaxHeight = "get_max_height";
		public static readonly StringName SetMinHeightFalloff = "set_min_height_falloff";
		public static readonly StringName GetMinHeightFalloff = "get_min_height_falloff";
		public static readonly StringName SetMaxHeightFalloff = "set_max_height_falloff";
		public static readonly StringName GetMaxHeightFalloff = "get_max_height_falloff";
		public static readonly StringName SetRandomVerticalFlip = "set_random_vertical_flip";
		public static readonly StringName GetRandomVerticalFlip = "get_random_vertical_flip";
		public static readonly StringName SetRandomRotation = "set_random_rotation";
		public static readonly StringName GetRandomRotation = "get_random_rotation";
		public static readonly StringName SetNoise = "set_noise";
		public static readonly StringName GetNoise = "get_noise";
		public static readonly StringName SetNoiseGraph = "set_noise_graph";
		public static readonly StringName GetNoiseGraph = "get_noise_graph";
		public static readonly StringName SetNoiseDimension = "set_noise_dimension";
		public static readonly StringName GetNoiseDimension = "get_noise_dimension";
		public static readonly StringName SetNoiseFalloff = "set_noise_falloff";
		public static readonly StringName GetNoiseFalloff = "get_noise_falloff";
		public static readonly StringName SetNoiseThreshold = "set_noise_threshold";
		public static readonly StringName GetNoiseThreshold = "get_noise_threshold";
		public static readonly StringName SetNoiseOnScale = "set_noise_on_scale";
		public static readonly StringName GetNoiseOnScale = "get_noise_on_scale";
		public static readonly StringName SetVoxelTextureFilterEnabled = "set_voxel_texture_filter_enabled";
		public static readonly StringName IsVoxelTextureFilterEnabled = "is_voxel_texture_filter_enabled";
		public static readonly StringName SetVoxelTextureFilterMask = "set_voxel_texture_filter_mask";
		public static readonly StringName GetVoxelTextureFilterMask = "get_voxel_texture_filter_mask";
		public static readonly StringName SetVoxelTextureFilterThreshold = "set_voxel_texture_filter_threshold";
		public static readonly StringName GetVoxelTextureFilterThreshold = "get_voxel_texture_filter_threshold";
		public static readonly StringName SetVoxelTextureFilterArray = "set_voxel_texture_filter_array";
		public static readonly StringName GetVoxelTextureFilterArray = "get_voxel_texture_filter_array";
		public static readonly StringName SetSnapToGeneratorSdfEnabled = "set_snap_to_generator_sdf_enabled";
		public static readonly StringName GetSnapToGeneratorSdfEnabled = "get_snap_to_generator_sdf_enabled";
		public static readonly StringName SetSnapToGeneratorSdfSearchDistance = "set_snap_to_generator_sdf_search_distance";
		public static readonly StringName GetSnapToGeneratorSdfSearchDistance = "get_snap_to_generator_sdf_search_distance";
		public static readonly StringName SetSnapToGeneratorSdfSampleCount = "set_snap_to_generator_sdf_sample_count";
		public static readonly StringName GetSnapToGeneratorSdfSampleCount = "get_snap_to_generator_sdf_sample_count";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelInstanceGenerator";

	#region Enums

	public enum EmitModeEnum : long
	{
		FromVertices = 0L,
		FromFacesFast = 1L,
		FromFaces = 2L,
		OnePerTriangle = 3L,
		ModeCount = 4L,
	}

	public enum Distribution : long
	{
		Linear = 0L,
		Quadratic = 1L,
		Cubic = 2L,
		Quintic = 3L,
		Count = 4L,
	}

	public enum Dimension : long
	{
		Dim2d = 0L,
		Dim3d = 1L,
		Count = 2L,
	}

	#endregion

	#region Properties

	public int EmitMode
	{
		get => (int)_object.Get(PropertyName.EmitMode);
		set => _object.Set(PropertyName.EmitMode, value);
	}

	public float Density
	{
		get => (float)_object.Get(PropertyName.Density);
		set => _object.Set(PropertyName.Density, value);
	}

	public float Jitter
	{
		get => (float)_object.Get(PropertyName.Jitter);
		set => _object.Set(PropertyName.Jitter, value);
	}

	public float TriangleAreaThreshold
	{
		get => (float)_object.Get(PropertyName.TriangleAreaThreshold);
		set => _object.Set(PropertyName.TriangleAreaThreshold, value);
	}

	public float MinScale
	{
		get => (float)_object.Get(PropertyName.MinScale);
		set => _object.Set(PropertyName.MinScale, value);
	}

	public float MaxScale
	{
		get => (float)_object.Get(PropertyName.MaxScale);
		set => _object.Set(PropertyName.MaxScale, value);
	}

	public int ScaleDistribution
	{
		get => (int)_object.Get(PropertyName.ScaleDistribution);
		set => _object.Set(PropertyName.ScaleDistribution, value);
	}

	public float VerticalAlignment
	{
		get => (float)_object.Get(PropertyName.VerticalAlignment);
		set => _object.Set(PropertyName.VerticalAlignment, value);
	}

	public bool RandomVerticalFlip
	{
		get => (bool)_object.Get(PropertyName.RandomVerticalFlip);
		set => _object.Set(PropertyName.RandomVerticalFlip, value);
	}

	public bool RandomRotation
	{
		get => (bool)_object.Get(PropertyName.RandomRotation);
		set => _object.Set(PropertyName.RandomRotation, value);
	}

	public float OffsetAlongNormal
	{
		get => (float)_object.Get(PropertyName.OffsetAlongNormal);
		set => _object.Set(PropertyName.OffsetAlongNormal, value);
	}

	public float MinSlopeDegrees
	{
		get => (float)_object.Get(PropertyName.MinSlopeDegrees);
		set => _object.Set(PropertyName.MinSlopeDegrees, value);
	}

	public float MaxSlopeDegrees
	{
		get => (float)_object.Get(PropertyName.MaxSlopeDegrees);
		set => _object.Set(PropertyName.MaxSlopeDegrees, value);
	}

	public float MinSlopeFalloffDegrees
	{
		get => (float)_object.Get(PropertyName.MinSlopeFalloffDegrees);
		set => _object.Set(PropertyName.MinSlopeFalloffDegrees, value);
	}

	public float MaxSlopeFalloffDegrees
	{
		get => (float)_object.Get(PropertyName.MaxSlopeFalloffDegrees);
		set => _object.Set(PropertyName.MaxSlopeFalloffDegrees, value);
	}

	public float MinHeight
	{
		get => (float)_object.Get(PropertyName.MinHeight);
		set => _object.Set(PropertyName.MinHeight, value);
	}

	public float MaxHeight
	{
		get => (float)_object.Get(PropertyName.MaxHeight);
		set => _object.Set(PropertyName.MaxHeight, value);
	}

	public float MinHeightFalloff
	{
		get => (float)_object.Get(PropertyName.MinHeightFalloff);
		set => _object.Set(PropertyName.MinHeightFalloff, value);
	}

	public float MaxHeightFalloff
	{
		get => (float)_object.Get(PropertyName.MaxHeightFalloff);
		set => _object.Set(PropertyName.MaxHeightFalloff, value);
	}

	public Noise Noise
	{
		get => (Noise)_object.Get(PropertyName.Noise);
		set => _object.Set(PropertyName.Noise, value);
	}

	public VoxelGraphFunction NoiseGraph
	{
		get => (VoxelGraphFunction)_object.Get(PropertyName.NoiseGraph);
		set => _object.Set(PropertyName.NoiseGraph, value);
	}

	public float NoiseFalloff
	{
		get => (float)_object.Get(PropertyName.NoiseFalloff);
		set => _object.Set(PropertyName.NoiseFalloff, value);
	}

	public float NoiseThreshold
	{
		get => (float)_object.Get(PropertyName.NoiseThreshold);
		set => _object.Set(PropertyName.NoiseThreshold, value);
	}

	public int NoiseDimension
	{
		get => (int)_object.Get(PropertyName.NoiseDimension);
		set => _object.Set(PropertyName.NoiseDimension, value);
	}

	public float NoiseOnScale
	{
		get => (float)_object.Get(PropertyName.NoiseOnScale);
		set => _object.Set(PropertyName.NoiseOnScale, value);
	}

	public bool VoxelTextureFilterEnabled
	{
		get => (bool)_object.Get(PropertyName.VoxelTextureFilterEnabled);
		set => _object.Set(PropertyName.VoxelTextureFilterEnabled, value);
	}

	public int[] VoxelTextureFilterArray
	{
		get => (int[])_object.Get(PropertyName.VoxelTextureFilterArray);
		set => _object.Set(PropertyName.VoxelTextureFilterArray, value);
	}

	public float VoxelTextureFilterThreshold
	{
		get => (float)_object.Get(PropertyName.VoxelTextureFilterThreshold);
		set => _object.Set(PropertyName.VoxelTextureFilterThreshold, value);
	}

	public bool SnapToGeneratorSdfEnabled
	{
		get => (bool)_object.Get(PropertyName.SnapToGeneratorSdfEnabled);
		set => _object.Set(PropertyName.SnapToGeneratorSdfEnabled, value);
	}

	public float SnapToGeneratorSdfSearchDistance
	{
		get => (float)_object.Get(PropertyName.SnapToGeneratorSdfSearchDistance);
		set => _object.Set(PropertyName.SnapToGeneratorSdfSearchDistance, value);
	}

	public int SnapToGeneratorSdfSampleCount
	{
		get => (int)_object.Get(PropertyName.SnapToGeneratorSdfSampleCount);
		set => _object.Set(PropertyName.SnapToGeneratorSdfSampleCount, value);
	}

	#endregion

	#region Inherited Properties

	public bool ResourceLocalToScene
	{
		get => _object.ResourceLocalToScene;
		set => _object.ResourceLocalToScene = value;
	}

	public string ResourcePath
	{
		get => _object.ResourcePath;
		set => _object.ResourcePath = value;
	}

	public string ResourceName
	{
		get => _object.ResourceName;
		set => _object.ResourceName = value;
	}

	public string ResourceSceneUniqueId
	{
		get => _object.ResourceSceneUniqueId;
		set => _object.ResourceSceneUniqueId = value;
	}

	#endregion

	#region Methods

	public void SetDensity(float @density)
	{
		_object.Call(MethodName.SetDensity, @density);
	}

	public float GetDensity()
	{
		return (float)_object.Call(MethodName.GetDensity);
	}

	public void SetEmitMode(VoxelInstanceGenerator.EmitModeEnum @density)
	{
		_object.Call(MethodName.SetEmitMode, (int)@density);
	}

	public VoxelInstanceGenerator.EmitModeEnum GetEmitMode()
	{
		return (VoxelInstanceGenerator.EmitModeEnum)(int)_object.Call(MethodName.GetEmitMode);
	}

	public void SetJitter(float @jitter)
	{
		_object.Call(MethodName.SetJitter, @jitter);
	}

	public float GetJitter()
	{
		return (float)_object.Call(MethodName.GetJitter);
	}

	public void SetTriangleAreaThreshold(float @threshold)
	{
		_object.Call(MethodName.SetTriangleAreaThreshold, @threshold);
	}

	public float GetTriangleAreaThreshold()
	{
		return (float)_object.Call(MethodName.GetTriangleAreaThreshold);
	}

	public void SetMinScale(float @min_scale)
	{
		_object.Call(MethodName.SetMinScale, @min_scale);
	}

	public float GetMinScale()
	{
		return (float)_object.Call(MethodName.GetMinScale);
	}

	public void SetMaxScale(float @max_scale)
	{
		_object.Call(MethodName.SetMaxScale, @max_scale);
	}

	public float GetMaxScale()
	{
		return (float)_object.Call(MethodName.GetMaxScale);
	}

	public void SetScaleDistribution(VoxelInstanceGenerator.Distribution @distribution)
	{
		_object.Call(MethodName.SetScaleDistribution, (int)@distribution);
	}

	public VoxelInstanceGenerator.Distribution GetScaleDistribution()
	{
		return (VoxelInstanceGenerator.Distribution)(int)_object.Call(MethodName.GetScaleDistribution);
	}

	public void SetVerticalAlignment(float @amount)
	{
		_object.Call(MethodName.SetVerticalAlignment, @amount);
	}

	public float GetVerticalAlignment()
	{
		return (float)_object.Call(MethodName.GetVerticalAlignment);
	}

	public void SetOffsetAlongNormal(float @offset)
	{
		_object.Call(MethodName.SetOffsetAlongNormal, @offset);
	}

	public float GetOffsetAlongNormal()
	{
		return (float)_object.Call(MethodName.GetOffsetAlongNormal);
	}

	public void SetMinSlopeDegrees(float @degrees)
	{
		_object.Call(MethodName.SetMinSlopeDegrees, @degrees);
	}

	public float GetMinSlopeDegrees()
	{
		return (float)_object.Call(MethodName.GetMinSlopeDegrees);
	}

	public void SetMaxSlopeDegrees(float @degrees)
	{
		_object.Call(MethodName.SetMaxSlopeDegrees, @degrees);
	}

	public float GetMaxSlopeDegrees()
	{
		return (float)_object.Call(MethodName.GetMaxSlopeDegrees);
	}

	public void SetMinSlopeFalloffDegrees(float @degrees)
	{
		_object.Call(MethodName.SetMinSlopeFalloffDegrees, @degrees);
	}

	public float GetMinSlopeFalloffDegrees()
	{
		return (float)_object.Call(MethodName.GetMinSlopeFalloffDegrees);
	}

	public void SetMaxSlopeFalloffDegrees(float @degrees)
	{
		_object.Call(MethodName.SetMaxSlopeFalloffDegrees, @degrees);
	}

	public float GetMaxSlopeFalloffDegrees()
	{
		return (float)_object.Call(MethodName.GetMaxSlopeFalloffDegrees);
	}

	public void SetMinHeight(float @height)
	{
		_object.Call(MethodName.SetMinHeight, @height);
	}

	public float GetMinHeight()
	{
		return (float)_object.Call(MethodName.GetMinHeight);
	}

	public void SetMaxHeight(float @height)
	{
		_object.Call(MethodName.SetMaxHeight, @height);
	}

	public float GetMaxHeight()
	{
		return (float)_object.Call(MethodName.GetMaxHeight);
	}

	public void SetMinHeightFalloff(float @distance)
	{
		_object.Call(MethodName.SetMinHeightFalloff, @distance);
	}

	public float GetMinHeightFalloff()
	{
		return (float)_object.Call(MethodName.GetMinHeightFalloff);
	}

	public void SetMaxHeightFalloff(float @distance)
	{
		_object.Call(MethodName.SetMaxHeightFalloff, @distance);
	}

	public float GetMaxHeightFalloff()
	{
		return (float)_object.Call(MethodName.GetMaxHeightFalloff);
	}

	public void SetRandomVerticalFlip(bool @enabled)
	{
		_object.Call(MethodName.SetRandomVerticalFlip, @enabled);
	}

	public bool GetRandomVerticalFlip()
	{
		return (bool)_object.Call(MethodName.GetRandomVerticalFlip);
	}

	public void SetRandomRotation(bool @enabled)
	{
		_object.Call(MethodName.SetRandomRotation, @enabled);
	}

	public bool GetRandomRotation()
	{
		return (bool)_object.Call(MethodName.GetRandomRotation);
	}

	public void SetNoise(Noise @noise)
	{
		_object.Call(MethodName.SetNoise, @noise);
	}

	public Noise GetNoise()
	{
		return (Noise)_object.Call(MethodName.GetNoise);
	}

	public void SetNoiseGraph(VoxelGraphFunction @graph)
	{
		_object.Call(MethodName.SetNoiseGraph, @graph);
	}

	public VoxelGraphFunction GetNoiseGraph()
	{
		return (VoxelGraphFunction)_object.Call(MethodName.GetNoiseGraph);
	}

	public void SetNoiseDimension(VoxelInstanceGenerator.Dimension @dim)
	{
		_object.Call(MethodName.SetNoiseDimension, (int)@dim);
	}

	public VoxelInstanceGenerator.Dimension GetNoiseDimension()
	{
		return (VoxelInstanceGenerator.Dimension)(int)_object.Call(MethodName.GetNoiseDimension);
	}

	public void SetNoiseFalloff(float @falloff)
	{
		_object.Call(MethodName.SetNoiseFalloff, @falloff);
	}

	public float GetNoiseFalloff()
	{
		return (float)_object.Call(MethodName.GetNoiseFalloff);
	}

	public void SetNoiseThreshold(float @threshold)
	{
		_object.Call(MethodName.SetNoiseThreshold, @threshold);
	}

	public float GetNoiseThreshold()
	{
		return (float)_object.Call(MethodName.GetNoiseThreshold);
	}

	public void SetNoiseOnScale(float @amount)
	{
		_object.Call(MethodName.SetNoiseOnScale, @amount);
	}

	public float GetNoiseOnScale()
	{
		return (float)_object.Call(MethodName.GetNoiseOnScale);
	}

	public void SetVoxelTextureFilterEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetVoxelTextureFilterEnabled, @enabled);
	}

	public bool IsVoxelTextureFilterEnabled()
	{
		return (bool)_object.Call(MethodName.IsVoxelTextureFilterEnabled);
	}

	public void SetVoxelTextureFilterMask(int @mask)
	{
		_object.Call(MethodName.SetVoxelTextureFilterMask, @mask);
	}

	public int GetVoxelTextureFilterMask()
	{
		return (int)_object.Call(MethodName.GetVoxelTextureFilterMask);
	}

	public void SetVoxelTextureFilterThreshold(float @threshold)
	{
		_object.Call(MethodName.SetVoxelTextureFilterThreshold, @threshold);
	}

	public float GetVoxelTextureFilterThreshold()
	{
		return (float)_object.Call(MethodName.GetVoxelTextureFilterThreshold);
	}

	public void SetVoxelTextureFilterArray(int[] @texture_indices)
	{
		_object.Call(MethodName.SetVoxelTextureFilterArray, @texture_indices);
	}

	public int[] GetVoxelTextureFilterArray()
	{
		return (int[])_object.Call(MethodName.GetVoxelTextureFilterArray);
	}

	public void SetSnapToGeneratorSdfEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetSnapToGeneratorSdfEnabled, @enabled);
	}

	public bool GetSnapToGeneratorSdfEnabled()
	{
		return (bool)_object.Call(MethodName.GetSnapToGeneratorSdfEnabled);
	}

	public void SetSnapToGeneratorSdfSearchDistance(float @d)
	{
		_object.Call(MethodName.SetSnapToGeneratorSdfSearchDistance, @d);
	}

	public float GetSnapToGeneratorSdfSearchDistance()
	{
		return (float)_object.Call(MethodName.GetSnapToGeneratorSdfSearchDistance);
	}

	public void SetSnapToGeneratorSdfSampleCount(int @enabled)
	{
		_object.Call(MethodName.SetSnapToGeneratorSdfSampleCount, @enabled);
	}

	public int GetSnapToGeneratorSdfSampleCount()
	{
		return (int)_object.Call(MethodName.GetSnapToGeneratorSdfSampleCount);
	}

	#endregion

	#region Inherited Methods

	public void SetPath(string @path)
	{
		_object.SetPath(@path);
	}

	public void TakeOverPath(string @path)
	{
		_object.TakeOverPath(@path);
	}

	public string GetPath()
	{
		return _object.GetPath();
	}

	public void SetPathCache(string @path)
	{
		_object.SetPathCache(@path);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public string GetName()
	{
		return _object.GetName();
	}

	public Godot.Rid GetRid()
	{
		return _object.GetRid();
	}

	public void SetLocalToScene(bool @enable)
	{
		_object.SetLocalToScene(@enable);
	}

	public bool IsLocalToScene()
	{
		return _object.IsLocalToScene();
	}

	public Node GetLocalScene()
	{
		return _object.GetLocalScene();
	}

	public void SetupLocalToScene()
	{
		_object.SetupLocalToScene();
	}

	public void ResetState()
	{
		_object.ResetState();
	}

	public void SetIdForPath(string @path, string @id)
	{
		_object.SetIdForPath(@path, @id);
	}

	public string GetIdForPath(string @path)
	{
		return _object.GetIdForPath(@path);
	}

	public bool IsBuiltIn()
	{
		return _object.IsBuiltIn();
	}

	public static string GenerateSceneUniqueId()
	{
		return Resource.GenerateSceneUniqueId();
	}

	public void SetSceneUniqueId(string @id)
	{
		_object.SetSceneUniqueId(@id);
	}

	public string GetSceneUniqueId()
	{
		return _object.GetSceneUniqueId();
	}

	public void EmitChanged()
	{
		_object.EmitChanged();
	}

	public Resource Duplicate(bool @deep = false)
	{
		return _object.Duplicate(@deep);
	}

	public Resource DuplicateDeep(Resource.DeepDuplicateMode @deep_subresources_mode = (Resource.DeepDuplicateMode)1)
	{
		return _object.DuplicateDeep(@deep_subresources_mode);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action Changed
	{
		add
		{
			Connect(SignalName.Changed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Changed, Callable.From(value));
		}
	}

	public event Action SetupLocalToSceneRequested
	{
		add
		{
			Connect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
	}

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
























