#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelInstanceLibraryInspectorPlugin : ZN_EditorInspectorPlugin
{
	public VoxelInstanceLibraryInspectorPlugin() : base(NativeName)
	{
	}
	protected VoxelInstanceLibraryInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelInstanceLibraryInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelInstanceLibraryInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(VoxelInstanceLibraryInspectorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelInstanceLibraryInspectorPlugin self) => self?._object;
	public static explicit operator VoxelInstanceLibraryInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelInstanceLibraryInspectorPlugin";
}
#endif
























