// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorScript : VoxelGenerator
{
	public VoxelGeneratorScript() : base(NativeName)
	{
	}
	protected VoxelGeneratorScript(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorScript(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorScript([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorScript self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorScript self) => self?._object;
	public static explicit operator VoxelGeneratorScript(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGenerator.PropertyName
	{

	}

	public new class MethodName : VoxelGenerator.MethodName
	{

	}

	public new class SignalName : VoxelGenerator.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorScript";
}
























