#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorMultipassEditorPlugin : ZN_EditorPlugin
{
	public VoxelGeneratorMultipassEditorPlugin() : base(NativeName)
	{
	}
	protected VoxelGeneratorMultipassEditorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorMultipassEditorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorMultipassEditorPlugin([NotNull] EditorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorPlugin(VoxelGeneratorMultipassEditorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorMultipassEditorPlugin self) => self?._object;
	public static explicit operator VoxelGeneratorMultipassEditorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorMultipassEditorPlugin";
}
#endif
























