#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorMultipassEditorInspectorPlugin : ZN_EditorInspectorPlugin
{
	public VoxelGeneratorMultipassEditorInspectorPlugin() : base(NativeName)
	{
	}
	protected VoxelGeneratorMultipassEditorInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorMultipassEditorInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorMultipassEditorInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(VoxelGeneratorMultipassEditorInspectorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorMultipassEditorInspectorPlugin self) => self?._object;
	public static explicit operator VoxelGeneratorMultipassEditorInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorMultipassEditorInspectorPlugin";
}
#endif
























