#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelVoxMeshImporter : ZN_EditorImportPlugin
{
	public VoxelVoxMeshImporter() : base(NativeName)
	{
	}
	protected VoxelVoxMeshImporter(StringName @class) : base(@class)
	{
	}
	protected VoxelVoxMeshImporter(Variant variant) : base(variant)
	{
	}
	protected VoxelVoxMeshImporter([NotNull] EditorImportPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorImportPlugin(VoxelVoxMeshImporter self) => self?._object;
	public static implicit operator Variant(VoxelVoxMeshImporter self) => self?._object;
	public static explicit operator VoxelVoxMeshImporter(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorImportPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorImportPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorImportPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelVoxMeshImporter";
}
#endif
























