// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGeneratorWaves : VoxelGeneratorHeightmap
{
	public VoxelGeneratorWaves() : base(NativeName)
	{
	}
	protected VoxelGeneratorWaves(StringName @class) : base(@class)
	{
	}
	protected VoxelGeneratorWaves(Variant variant) : base(variant)
	{
	}
	protected VoxelGeneratorWaves([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelGeneratorWaves self) => self?._object;
	public static implicit operator Variant(VoxelGeneratorWaves self) => self?._object;
	public static explicit operator VoxelGeneratorWaves(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelGeneratorHeightmap.PropertyName
	{
		public static readonly StringName PatternSize = "pattern_size";
		public static readonly StringName PatternOffset = "pattern_offset";
	}

	public new class MethodName : VoxelGeneratorHeightmap.MethodName
	{
		public static readonly StringName SetPatternSize = "set_pattern_size";
		public static readonly StringName GetPatternSize = "get_pattern_size";
		public static readonly StringName SetPatternOffset = "set_pattern_offset";
		public static readonly StringName GetPatternOffset = "get_pattern_offset";
	}

	public new class SignalName : VoxelGeneratorHeightmap.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGeneratorWaves";

	#region Properties

	public Godot.Vector2 PatternSize
	{
		get => (Godot.Vector2)_object.Get(PropertyName.PatternSize);
		set => _object.Set(PropertyName.PatternSize, value);
	}

	public Godot.Vector2 PatternOffset
	{
		get => (Godot.Vector2)_object.Get(PropertyName.PatternOffset);
		set => _object.Set(PropertyName.PatternOffset, value);
	}

	#endregion

	#region Methods

	public void SetPatternSize(Godot.Vector2 @size)
	{
		_object.Call(MethodName.SetPatternSize, @size);
	}

	public Godot.Vector2 GetPatternSize()
	{
		return (Godot.Vector2)_object.Call(MethodName.GetPatternSize);
	}

	public void SetPatternOffset(Godot.Vector2 @offset)
	{
		_object.Call(MethodName.SetPatternOffset, @offset);
	}

	public Godot.Vector2 GetPatternOffset()
	{
		return (Godot.Vector2)_object.Call(MethodName.GetPatternOffset);
	}

	#endregion
}
























