#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGraphEditorPlugin : ZN_EditorPlugin
{
	public VoxelGraphEditorPlugin() : base(NativeName)
	{
	}
	protected VoxelGraphEditorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelGraphEditorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelGraphEditorPlugin([NotNull] EditorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorPlugin(VoxelGraphEditorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelGraphEditorPlugin self) => self?._object;
	public static explicit operator VoxelGraphEditorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGraphEditorPlugin";
}
#endif
























