// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelInstanceLibraryMultiMeshItem : VoxelInstanceLibraryItem
{
	public VoxelInstanceLibraryMultiMeshItem() : base(NativeName)
	{
	}
	protected VoxelInstanceLibraryMultiMeshItem(StringName @class) : base(@class)
	{
	}
	protected VoxelInstanceLibraryMultiMeshItem(Variant variant) : base(variant)
	{
	}
	protected VoxelInstanceLibraryMultiMeshItem([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelInstanceLibraryMultiMeshItem self) => self?._object;
	public static implicit operator Variant(VoxelInstanceLibraryMultiMeshItem self) => self?._object;
	public static explicit operator VoxelInstanceLibraryMultiMeshItem(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelInstanceLibraryItem.PropertyName
	{
		public static readonly StringName Scene = "scene";
		public static readonly StringName CollisionDistance = "collision_distance";
		public static readonly StringName Mesh = "mesh";
		public static readonly StringName MeshLod1 = "mesh_lod1";
		public static readonly StringName MeshLod2 = "mesh_lod2";
		public static readonly StringName MeshLod3 = "mesh_lod3";
		public static readonly StringName RenderLayer = "render_layer";
		public static readonly StringName MaterialOverride = "material_override";
		public static readonly StringName CastShadow = "cast_shadow";
		public static readonly StringName GiMode = "gi_mode";
		public static readonly StringName CollisionLayer = "collision_layer";
		public static readonly StringName CollisionMask = "collision_mask";
		public static readonly StringName CollisionShapes = "collision_shapes";
		public static readonly StringName MeshLod0DistanceRatio = "mesh_lod0_distance_ratio";
		public static readonly StringName MeshLod1DistanceRatio = "mesh_lod1_distance_ratio";
		public static readonly StringName MeshLod2DistanceRatio = "mesh_lod2_distance_ratio";
		public static readonly StringName MeshLod3DistanceRatio = "mesh_lod3_distance_ratio";
		public static readonly StringName MeshLodDistanceRatios = "_mesh_lod_distance_ratios";
		public static readonly StringName HideBeyondMaxLod = "hide_beyond_max_lod";
		public static readonly StringName RemovalBehavior = "removal_behavior";
		public static readonly StringName RemovalScene = "removal_scene";
	}

	public new class MethodName : VoxelInstanceLibraryItem.MethodName
	{
		public static readonly StringName SetMesh = "set_mesh";
		public static readonly StringName GetMesh = "get_mesh";
		public static readonly StringName SetHideBeyondMaxLod = "set_hide_beyond_max_lod";
		public static readonly StringName GetHideBeyondMaxLod = "get_hide_beyond_max_lod";
		public static readonly StringName SetRenderLayer = "set_render_layer";
		public static readonly StringName GetRenderLayer = "get_render_layer";
		public static readonly StringName SetMaterialOverride = "set_material_override";
		public static readonly StringName GetMaterialOverride = "get_material_override";
		public static readonly StringName SetCastShadowsSetting = "set_cast_shadows_setting";
		public static readonly StringName GetCastShadowsSetting = "get_cast_shadows_setting";
		public static readonly StringName SetGiMode = "set_gi_mode";
		public static readonly StringName GetGiMode = "get_gi_mode";
		public static readonly StringName SetCollisionLayer = "set_collision_layer";
		public static readonly StringName GetCollisionLayer = "get_collision_layer";
		public static readonly StringName SetCollisionMask = "set_collision_mask";
		public static readonly StringName GetCollisionMask = "get_collision_mask";
		public static readonly StringName SetCollisionShapes = "set_collision_shapes";
		public static readonly StringName GetCollisionShapes = "get_collision_shapes";
		public static readonly StringName SetColliderGroupNames = "set_collider_group_names";
		public static readonly StringName GetColliderGroupNames = "get_collider_group_names";
		public static readonly StringName SetupFromTemplate = "setup_from_template";
		public static readonly StringName GetScene = "get_scene";
		public static readonly StringName SetScene = "set_scene";
		public static readonly StringName GetRemovalBehavior = "get_removal_behavior";
		public static readonly StringName SetRemovalBehavior = "set_removal_behavior";
		public static readonly StringName GetRemovalScene = "get_removal_scene";
		public static readonly StringName SetRemovalScene = "set_removal_scene";
		public static readonly StringName GetCollisionDistance = "get_collision_distance";
		public static readonly StringName SetCollisionDistance = "set_collision_distance";
	}

	public new class SignalName : VoxelInstanceLibraryItem.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelInstanceLibraryMultiMeshItem";

	#region Enums

	public enum RemovalBehaviorEnum : long
	{
		None = 0L,
		Instantiate = 1L,
		Callback = 2L,
	}

	#endregion

	#region Integer Constants

	public const long MaxMeshLods = 4L;

	#endregion

	#region Properties

	public PackedScene Scene
	{
		get => (PackedScene)_object.Get(PropertyName.Scene);
		set => _object.Set(PropertyName.Scene, value);
	}

	public float CollisionDistance
	{
		get => (float)_object.Get(PropertyName.CollisionDistance);
		set => _object.Set(PropertyName.CollisionDistance, value);
	}

	public Mesh Mesh
	{
		get => (Mesh)_object.Get(PropertyName.Mesh);
		set => _object.Set(PropertyName.Mesh, value);
	}

	public Mesh MeshLod1
	{
		get => (Mesh)_object.Get(PropertyName.MeshLod1);
		set => _object.Set(PropertyName.MeshLod1, value);
	}

	public Mesh MeshLod2
	{
		get => (Mesh)_object.Get(PropertyName.MeshLod2);
		set => _object.Set(PropertyName.MeshLod2, value);
	}

	public Mesh MeshLod3
	{
		get => (Mesh)_object.Get(PropertyName.MeshLod3);
		set => _object.Set(PropertyName.MeshLod3, value);
	}

	public int RenderLayer
	{
		get => (int)_object.Get(PropertyName.RenderLayer);
		set => _object.Set(PropertyName.RenderLayer, value);
	}

	public Material MaterialOverride
	{
		get => (Material)_object.Get(PropertyName.MaterialOverride);
		set => _object.Set(PropertyName.MaterialOverride, value);
	}

	public int CastShadow
	{
		get => (int)_object.Get(PropertyName.CastShadow);
		set => _object.Set(PropertyName.CastShadow, value);
	}

	public int GiMode
	{
		get => (int)_object.Get(PropertyName.GiMode);
		set => _object.Set(PropertyName.GiMode, value);
	}

	public int CollisionLayer
	{
		get => (int)_object.Get(PropertyName.CollisionLayer);
		set => _object.Set(PropertyName.CollisionLayer, value);
	}

	public int CollisionMask
	{
		get => (int)_object.Get(PropertyName.CollisionMask);
		set => _object.Set(PropertyName.CollisionMask, value);
	}

	public Godot.Collections.Array CollisionShapes
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.CollisionShapes);
		set => _object.Set(PropertyName.CollisionShapes, value);
	}

	public float MeshLod0DistanceRatio
	{
		get => (float)_object.Get(PropertyName.MeshLod0DistanceRatio);
		set => _object.Set(PropertyName.MeshLod0DistanceRatio, value);
	}

	public float MeshLod1DistanceRatio
	{
		get => (float)_object.Get(PropertyName.MeshLod1DistanceRatio);
		set => _object.Set(PropertyName.MeshLod1DistanceRatio, value);
	}

	public float MeshLod2DistanceRatio
	{
		get => (float)_object.Get(PropertyName.MeshLod2DistanceRatio);
		set => _object.Set(PropertyName.MeshLod2DistanceRatio, value);
	}

	public float MeshLod3DistanceRatio
	{
		get => (float)_object.Get(PropertyName.MeshLod3DistanceRatio);
		set => _object.Set(PropertyName.MeshLod3DistanceRatio, value);
	}

	public float[] MeshLodDistanceRatios
	{
		get => (float[])_object.Get(PropertyName.MeshLodDistanceRatios);
		set => _object.Set(PropertyName.MeshLodDistanceRatios, value);
	}

	public bool HideBeyondMaxLod
	{
		get => (bool)_object.Get(PropertyName.HideBeyondMaxLod);
		set => _object.Set(PropertyName.HideBeyondMaxLod, value);
	}

	public int RemovalBehavior
	{
		get => (int)_object.Get(PropertyName.RemovalBehavior);
		set => _object.Set(PropertyName.RemovalBehavior, value);
	}

	public PackedScene RemovalScene
	{
		get => (PackedScene)_object.Get(PropertyName.RemovalScene);
		set => _object.Set(PropertyName.RemovalScene, value);
	}

	#endregion

	#region Methods

	public void SetMesh(Mesh @mesh, int @mesh_lod_index)
	{
		_object.Call(MethodName.SetMesh, @mesh, @mesh_lod_index);
	}

	public Mesh GetMesh(int @mesh_lod_index)
	{
		return (Mesh)_object.Call(MethodName.GetMesh, @mesh_lod_index);
	}

	public void SetHideBeyondMaxLod(bool @enabled)
	{
		_object.Call(MethodName.SetHideBeyondMaxLod, @enabled);
	}

	public bool GetHideBeyondMaxLod()
	{
		return (bool)_object.Call(MethodName.GetHideBeyondMaxLod);
	}

	public void SetRenderLayer(int @render_layer)
	{
		_object.Call(MethodName.SetRenderLayer, @render_layer);
	}

	public int GetRenderLayer()
	{
		return (int)_object.Call(MethodName.GetRenderLayer);
	}

	public void SetMaterialOverride(Material @material)
	{
		_object.Call(MethodName.SetMaterialOverride, @material);
	}

	public Material GetMaterialOverride()
	{
		return (Material)_object.Call(MethodName.GetMaterialOverride);
	}

	public void SetCastShadowsSetting(RenderingServer.ShadowCastingSetting @mode)
	{
		_object.Call(MethodName.SetCastShadowsSetting, (int)@mode);
	}

	public RenderingServer.ShadowCastingSetting GetCastShadowsSetting()
	{
		return (RenderingServer.ShadowCastingSetting)(int)_object.Call(MethodName.GetCastShadowsSetting);
	}

	public void SetGiMode(GeometryInstance3D.GIModeEnum @mode)
	{
		_object.Call(MethodName.SetGiMode, (int)@mode);
	}

	public GeometryInstance3D.GIModeEnum GetGiMode()
	{
		return (GeometryInstance3D.GIModeEnum)(int)_object.Call(MethodName.GetGiMode);
	}

	public void SetCollisionLayer(int @collision_layer)
	{
		_object.Call(MethodName.SetCollisionLayer, @collision_layer);
	}

	public int GetCollisionLayer()
	{
		return (int)_object.Call(MethodName.GetCollisionLayer);
	}

	public void SetCollisionMask(int @collision_mask)
	{
		_object.Call(MethodName.SetCollisionMask, @collision_mask);
	}

	public int GetCollisionMask()
	{
		return (int)_object.Call(MethodName.GetCollisionMask);
	}

	public void SetCollisionShapes(Godot.Collections.Array @shape_infos)
	{
		_object.Call(MethodName.SetCollisionShapes, @shape_infos);
	}

	public Godot.Collections.Array GetCollisionShapes()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetCollisionShapes);
	}

	public void SetColliderGroupNames(Godot.Collections.Array<StringName> @names)
	{
		_object.Call(MethodName.SetColliderGroupNames, @names);
	}

	public Godot.Collections.Array<StringName> GetColliderGroupNames()
	{
		return (Godot.Collections.Array<StringName>)_object.Call(MethodName.GetColliderGroupNames);
	}

	public void SetupFromTemplate(GodotObject @node)
	{
		_object.Call(MethodName.SetupFromTemplate, @node);
	}

	public PackedScene GetScene()
	{
		return (PackedScene)_object.Call(MethodName.GetScene);
	}

	public void SetScene(PackedScene @scene)
	{
		_object.Call(MethodName.SetScene, @scene);
	}

	public VoxelInstanceLibraryMultiMeshItem.RemovalBehaviorEnum GetRemovalBehavior()
	{
		return (VoxelInstanceLibraryMultiMeshItem.RemovalBehaviorEnum)(int)_object.Call(MethodName.GetRemovalBehavior);
	}

	public void SetRemovalBehavior(VoxelInstanceLibraryMultiMeshItem.RemovalBehaviorEnum @rb)
	{
		_object.Call(MethodName.SetRemovalBehavior, (int)@rb);
	}

	public PackedScene GetRemovalScene()
	{
		return (PackedScene)_object.Call(MethodName.GetRemovalScene);
	}

	public void SetRemovalScene(PackedScene @scene)
	{
		_object.Call(MethodName.SetRemovalScene, @scene);
	}

	public float GetCollisionDistance()
	{
		return (float)_object.Call(MethodName.GetCollisionDistance);
	}

	public void SetCollisionDistance(float @distance)
	{
		_object.Call(MethodName.SetCollisionDistance, @distance);
	}

	#endregion
}
























