// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyFluid
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public VoxelBlockyFluid() : this(NativeName)
	{
	}
	protected VoxelBlockyFluid(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected VoxelBlockyFluid(Variant variant) : this((Resource) variant)
	{
	}
	protected VoxelBlockyFluid([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(VoxelBlockyFluid self) => self?._object;
	public static implicit operator Variant(VoxelBlockyFluid self) => self?._object;
	public static explicit operator VoxelBlockyFluid(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Material = "material";
		public static readonly StringName DipWhenFlowingDown = "dip_when_flowing_down";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetMaterial = "set_material";
		public static readonly StringName GetMaterial = "get_material";
		public static readonly StringName SetDipWhenFlowingDown = "set_dip_when_flowing_down";
		public static readonly StringName GetDipWhenFlowingDown = "get_dip_when_flowing_down";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyFluid";

	#region Properties

	public Material Material
	{
		get => (Material)_object.Get(PropertyName.Material);
		set => _object.Set(PropertyName.Material, value);
	}

	public bool DipWhenFlowingDown
	{
		get => (bool)_object.Get(PropertyName.DipWhenFlowingDown);
		set => _object.Set(PropertyName.DipWhenFlowingDown, value);
	}

	#endregion

	#region Inherited Properties

	public bool ResourceLocalToScene
	{
		get => _object.ResourceLocalToScene;
		set => _object.ResourceLocalToScene = value;
	}

	public string ResourcePath
	{
		get => _object.ResourcePath;
		set => _object.ResourcePath = value;
	}

	public string ResourceName
	{
		get => _object.ResourceName;
		set => _object.ResourceName = value;
	}

	public string ResourceSceneUniqueId
	{
		get => _object.ResourceSceneUniqueId;
		set => _object.ResourceSceneUniqueId = value;
	}

	#endregion

	#region Methods

	public void SetMaterial(Material @material)
	{
		_object.Call(MethodName.SetMaterial, @material);
	}

	public Material GetMaterial()
	{
		return (Material)_object.Call(MethodName.GetMaterial);
	}

	public void SetDipWhenFlowingDown(bool @enable)
	{
		_object.Call(MethodName.SetDipWhenFlowingDown, @enable);
	}

	public bool GetDipWhenFlowingDown()
	{
		return (bool)_object.Call(MethodName.GetDipWhenFlowingDown);
	}

	#endregion

	#region Inherited Methods

	public void SetPath(string @path)
	{
		_object.SetPath(@path);
	}

	public void TakeOverPath(string @path)
	{
		_object.TakeOverPath(@path);
	}

	public string GetPath()
	{
		return _object.GetPath();
	}

	public void SetPathCache(string @path)
	{
		_object.SetPathCache(@path);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public string GetName()
	{
		return _object.GetName();
	}

	public Godot.Rid GetRid()
	{
		return _object.GetRid();
	}

	public void SetLocalToScene(bool @enable)
	{
		_object.SetLocalToScene(@enable);
	}

	public bool IsLocalToScene()
	{
		return _object.IsLocalToScene();
	}

	public Node GetLocalScene()
	{
		return _object.GetLocalScene();
	}

	public void SetupLocalToScene()
	{
		_object.SetupLocalToScene();
	}

	public void ResetState()
	{
		_object.ResetState();
	}

	public void SetIdForPath(string @path, string @id)
	{
		_object.SetIdForPath(@path, @id);
	}

	public string GetIdForPath(string @path)
	{
		return _object.GetIdForPath(@path);
	}

	public bool IsBuiltIn()
	{
		return _object.IsBuiltIn();
	}

	public static string GenerateSceneUniqueId()
	{
		return Resource.GenerateSceneUniqueId();
	}

	public void SetSceneUniqueId(string @id)
	{
		_object.SetSceneUniqueId(@id);
	}

	public string GetSceneUniqueId()
	{
		return _object.GetSceneUniqueId();
	}

	public void EmitChanged()
	{
		_object.EmitChanged();
	}

	public Resource Duplicate(bool @deep = false)
	{
		return _object.Duplicate(@deep);
	}

	public Resource DuplicateDeep(Resource.DeepDuplicateMode @deep_subresources_mode = (Resource.DeepDuplicateMode)1)
	{
		return _object.DuplicateDeep(@deep_subresources_mode);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action Changed
	{
		add
		{
			Connect(SignalName.Changed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Changed, Callable.From(value));
		}
	}

	public event Action SetupLocalToSceneRequested
	{
		add
		{
			Connect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
	}

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
























