// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelToolTerrain : VoxelTool
{
	public VoxelToolTerrain() : base(NativeName)
	{
	}
	protected VoxelToolTerrain(StringName @class) : base(@class)
	{
	}
	protected VoxelToolTerrain(Variant variant) : base(variant)
	{
	}
	protected VoxelToolTerrain([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(VoxelToolTerrain self) => self?._object;
	public static implicit operator Variant(VoxelToolTerrain self) => self?._object;
	public static explicit operator VoxelToolTerrain(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelTool.PropertyName
	{

	}

	public new class MethodName : VoxelTool.MethodName
	{
		public static readonly StringName RunBlockyRandomTick = "run_blocky_random_tick";
		public static readonly StringName ForEachVoxelMetadataInArea = "for_each_voxel_metadata_in_area";
		public static readonly StringName DoHemisphere = "do_hemisphere";
	}

	public new class SignalName : VoxelTool.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelToolTerrain";

	#region Methods

	public void RunBlockyRandomTick(Godot.Aabb @area, int @voxel_count, Godot.Callable @callback, int @batch_count = 16, int @tags_mask = -1)
	{
		_object.Call(MethodName.RunBlockyRandomTick, @area, @voxel_count, @callback, @batch_count, @tags_mask);
	}

	public void ForEachVoxelMetadataInArea(Godot.Aabb @voxel_area, Godot.Callable @callback)
	{
		_object.Call(MethodName.ForEachVoxelMetadataInArea, @voxel_area, @callback);
	}

	public void DoHemisphere(Godot.Vector3 @center, float @radius, Godot.Vector3 @flat_direction, float @smoothness = 0.0f)
	{
		_object.Call(MethodName.DoHemisphere, @center, @radius, @flat_direction, @smoothness);
	}

	#endregion
}
























