// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelStreamSQLite : VoxelStream
{
	public VoxelStreamSQLite() : base(NativeName)
	{
	}
	protected VoxelStreamSQLite(StringName @class) : base(@class)
	{
	}
	protected VoxelStreamSQLite(Variant variant) : base(variant)
	{
	}
	protected VoxelStreamSQLite([NotNull] Resource @object) : base(@object)
	{
	}

	public static implicit operator Resource(VoxelStreamSQLite self) => self?._object;
	public static implicit operator Variant(VoxelStreamSQLite self) => self?._object;
	public static explicit operator VoxelStreamSQLite(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelStream.PropertyName
	{
		public static readonly StringName DatabasePath = "database_path";
		public static readonly StringName PreferredCoordinateFormat = "preferred_coordinate_format";
	}

	public new class MethodName : VoxelStream.MethodName
	{
		public static readonly StringName SetDatabasePath = "set_database_path";
		public static readonly StringName GetDatabasePath = "get_database_path";
		public static readonly StringName SetKeyCacheEnabled = "set_key_cache_enabled";
		public static readonly StringName IsKeyCacheEnabled = "is_key_cache_enabled";
		public static readonly StringName SetPreferredCoordinateFormat = "set_preferred_coordinate_format";
		public static readonly StringName GetPreferredCoordinateFormat = "get_preferred_coordinate_format";
	}

	public new class SignalName : VoxelStream.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelStreamSQLite";

	#region Enums

	public enum CoordinateFormat : long
	{
		Int64X16Y16Z16L16 = 0L,
		Int64X19Y19Z19L7 = 1L,
		StringCsd = 2L,
		Blob80X25Y25Z25L5 = 3L,
		Count = 4L,
	}

	#endregion

	#region Properties

	public string DatabasePath
	{
		get => (string)_object.Get(PropertyName.DatabasePath);
		set => _object.Set(PropertyName.DatabasePath, value);
	}

	public int PreferredCoordinateFormat
	{
		get => (int)_object.Get(PropertyName.PreferredCoordinateFormat);
		set => _object.Set(PropertyName.PreferredCoordinateFormat, value);
	}

	#endregion

	#region Methods

	public void SetDatabasePath(string @path)
	{
		_object.Call(MethodName.SetDatabasePath, @path);
	}

	public string GetDatabasePath()
	{
		return (string)_object.Call(MethodName.GetDatabasePath);
	}

	public void SetKeyCacheEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetKeyCacheEnabled, @enabled);
	}

	public bool IsKeyCacheEnabled()
	{
		return (bool)_object.Call(MethodName.IsKeyCacheEnabled);
	}

	public void SetPreferredCoordinateFormat(VoxelStreamSQLite.CoordinateFormat @format)
	{
		_object.Call(MethodName.SetPreferredCoordinateFormat, (int)@format);
	}

	public VoxelStreamSQLite.CoordinateFormat GetPreferredCoordinateFormat()
	{
		return (VoxelStreamSQLite.CoordinateFormat)(int)_object.Call(MethodName.GetPreferredCoordinateFormat);
	}

	#endregion
}
























