#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelGraphEditorIODialog
{
	// Engine object used for calling engine methods
	protected ConfirmationDialog _object;

	public VoxelGraphEditorIODialog() : this(NativeName)
	{
	}
	protected VoxelGraphEditorIODialog(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected VoxelGraphEditorIODialog(Variant variant) : this((ConfirmationDialog) variant)
	{
	}
	protected VoxelGraphEditorIODialog([NotNull] ConfirmationDialog @object)
	{
		_object = @object;
	}

	public static implicit operator ConfirmationDialog(VoxelGraphEditorIODialog self) => self?._object;
	public static implicit operator Variant(VoxelGraphEditorIODialog self) => self?._object;
	public static explicit operator VoxelGraphEditorIODialog(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : ConfirmationDialog.PropertyName
	{

	}

	public class MethodName : ConfirmationDialog.MethodName
	{
		public static readonly StringName Reshow = "reshow";
	}

	public class SignalName : ConfirmationDialog.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelGraphEditorIODialog";

	#region Inherited Properties

	public string CancelButtonText
	{
		get => _object.CancelButtonText;
		set => _object.CancelButtonText = value;
	}

	public string OkButtonText
	{
		get => _object.OkButtonText;
		set => _object.OkButtonText = value;
	}

	public string DialogText
	{
		get => _object.DialogText;
		set => _object.DialogText = value;
	}

	public bool DialogHideOnOk
	{
		get => _object.DialogHideOnOk;
		set => _object.DialogHideOnOk = value;
	}

	public bool DialogCloseOnEscape
	{
		get => _object.DialogCloseOnEscape;
		set => _object.DialogCloseOnEscape = value;
	}

	public bool DialogAutowrap
	{
		get => _object.DialogAutowrap;
		set => _object.DialogAutowrap = value;
	}

	public int Mode
	{
		get => (int)_object.Mode;
		set => _object.Mode = (Godot.Window.ModeEnum)value;
	}

	public string Title
	{
		get => _object.Title;
		set => _object.Title = value;
	}

	public int InitialPosition
	{
		get => (int)_object.InitialPosition;
		set => _object.InitialPosition = (Godot.Window.WindowInitialPosition)value;
	}

	public Godot.Vector2I Position
	{
		get => _object.Position;
		set => _object.Position = value;
	}

	public Godot.Vector2I Size
	{
		get => _object.Size;
		set => _object.Size = value;
	}

	public int CurrentScreen
	{
		get => _object.CurrentScreen;
		set => _object.CurrentScreen = value;
	}

	public Godot.Rect2I NonclientArea
	{
		get => _object.NonclientArea;
		set => _object.NonclientArea = value;
	}

	public Godot.Vector2[] MousePassthroughPolygon
	{
		get => _object.MousePassthroughPolygon;
		set => _object.MousePassthroughPolygon = value;
	}

	public bool Visible
	{
		get => _object.Visible;
		set => _object.Visible = value;
	}

	public bool WrapControls
	{
		get => _object.WrapControls;
		set => _object.WrapControls = value;
	}

	public bool Transient
	{
		get => _object.Transient;
		set => _object.Transient = value;
	}

	public bool TransientToFocused
	{
		get => _object.TransientToFocused;
		set => _object.TransientToFocused = value;
	}

	public bool Exclusive
	{
		get => _object.Exclusive;
		set => _object.Exclusive = value;
	}

	public bool Unresizable
	{
		get => _object.Unresizable;
		set => _object.Unresizable = value;
	}

	public bool Borderless
	{
		get => _object.Borderless;
		set => _object.Borderless = value;
	}

	public bool AlwaysOnTop
	{
		get => _object.AlwaysOnTop;
		set => _object.AlwaysOnTop = value;
	}

	public bool Transparent
	{
		get => _object.Transparent;
		set => _object.Transparent = value;
	}

	public bool Unfocusable
	{
		get => _object.Unfocusable;
		set => _object.Unfocusable = value;
	}

	public bool PopupWindow
	{
		get => _object.PopupWindow;
		set => _object.PopupWindow = value;
	}

	public bool ExtendToTitle
	{
		get => _object.ExtendToTitle;
		set => _object.ExtendToTitle = value;
	}

	public bool MousePassthrough
	{
		get => _object.MousePassthrough;
		set => _object.MousePassthrough = value;
	}

	public bool SharpCorners
	{
		get => _object.SharpCorners;
		set => _object.SharpCorners = value;
	}

	public bool ExcludeFromCapture
	{
		get => _object.ExcludeFromCapture;
		set => _object.ExcludeFromCapture = value;
	}

	public bool PopupWmHint
	{
		get => (bool)_object.Get("popup_window");
		set => _object.Set("popup_window", value);
	}

	public bool MinimizeDisabled
	{
		get => _object.MinimizeDisabled;
		set => _object.MinimizeDisabled = value;
	}

	public bool MaximizeDisabled
	{
		get => _object.MaximizeDisabled;
		set => _object.MaximizeDisabled = value;
	}

	public bool ForceNative
	{
		get => _object.ForceNative;
		set => _object.ForceNative = value;
	}

	public Godot.Vector2I MinSize
	{
		get => _object.MinSize;
		set => _object.MinSize = value;
	}

	public Godot.Vector2I MaxSize
	{
		get => _object.MaxSize;
		set => _object.MaxSize = value;
	}

	public bool KeepTitleVisible
	{
		get => _object.KeepTitleVisible;
		set => _object.KeepTitleVisible = value;
	}

	public Godot.Vector2I ContentScaleSize
	{
		get => _object.ContentScaleSize;
		set => _object.ContentScaleSize = value;
	}

	public int ContentScaleMode
	{
		get => (int)_object.ContentScaleMode;
		set => _object.ContentScaleMode = (Godot.Window.ContentScaleModeEnum)value;
	}

	public int ContentScaleAspect
	{
		get => (int)_object.ContentScaleAspect;
		set => _object.ContentScaleAspect = (Godot.Window.ContentScaleAspectEnum)value;
	}

	public int ContentScaleStretch
	{
		get => (int)_object.ContentScaleStretch;
		set => _object.ContentScaleStretch = (Godot.Window.ContentScaleStretchEnum)value;
	}

	public float ContentScaleFactor
	{
		get => (float)_object.ContentScaleFactor;
		set => _object.ContentScaleFactor = value;
	}

	public bool AutoTranslate
	{
		get => _object.AutoTranslate;
		set => _object.AutoTranslate = value;
	}

	public string AccessibilityName
	{
		get => _object.AccessibilityName;
		set => _object.AccessibilityName = value;
	}

	public string AccessibilityDescription
	{
		get => _object.AccessibilityDescription;
		set => _object.AccessibilityDescription = value;
	}

	public Theme Theme
	{
		get => _object.Theme;
		set => _object.Theme = value;
	}

	public string ThemeTypeVariation
	{
		get => _object.ThemeTypeVariation;
		set => _object.ThemeTypeVariation = value;
	}

	public bool Disable3d
	{
		get => _object.Disable3D;
		set => _object.Disable3D = value;
	}

	public bool UseXr
	{
		get => (bool)_object.Get("use_xr");
		set => _object.Set("use_xr", value);
	}

	public bool OwnWorld3d
	{
		get => _object.OwnWorld3D;
		set => _object.OwnWorld3D = value;
	}

	public World3D World3d
	{
		get => _object.World3D;
		set => _object.World3D = value;
	}

	public World2D World2d
	{
		get => _object.World2D;
		set => _object.World2D = value;
	}

	public bool TransparentBg
	{
		get => _object.TransparentBg;
		set => _object.TransparentBg = value;
	}

	public bool HandleInputLocally
	{
		get => _object.HandleInputLocally;
		set => _object.HandleInputLocally = value;
	}

	public bool Snap2dTransformsToPixel
	{
		get => _object.Snap2DTransformsToPixel;
		set => _object.Snap2DTransformsToPixel = value;
	}

	public bool Snap2dVerticesToPixel
	{
		get => _object.Snap2DVerticesToPixel;
		set => _object.Snap2DVerticesToPixel = value;
	}

	public int Msaa2d
	{
		get => (int)_object.Get("msaa_2d");
		set => _object.Set("msaa_2d", value);
	}

	public int Msaa3d
	{
		get => (int)_object.Get("msaa_3d");
		set => _object.Set("msaa_3d", value);
	}

	public int ScreenSpaceAa
	{
		get => (int)_object.Get("screen_space_aa");
		set => _object.Set("screen_space_aa", value);
	}

	public bool UseTaa
	{
		get => _object.UseTaa;
		set => _object.UseTaa = value;
	}

	public bool UseDebanding
	{
		get => _object.UseDebanding;
		set => _object.UseDebanding = value;
	}

	public bool UseOcclusionCulling
	{
		get => _object.UseOcclusionCulling;
		set => _object.UseOcclusionCulling = value;
	}

	public float MeshLodThreshold
	{
		get => _object.MeshLodThreshold;
		set => _object.MeshLodThreshold = value;
	}

	public int DebugDraw
	{
		get => (int)_object.DebugDraw;
		set => _object.DebugDraw = (Godot.Viewport.DebugDrawEnum)value;
	}

	public bool UseHdr2d
	{
		get => (bool)_object.Get("use_hdr_2d");
		set => _object.Set("use_hdr_2d", value);
	}

	public int Scaling3dMode
	{
		get => (int)_object.Get("scaling_3d_mode");
		set => _object.Set("scaling_3d_mode", value);
	}

	public float Scaling3dScale
	{
		get => (float)_object.Get("scaling_3d_scale");
		set => _object.Set("scaling_3d_scale", value);
	}

	public float TextureMipmapBias
	{
		get => _object.TextureMipmapBias;
		set => _object.TextureMipmapBias = value;
	}

	public int AnisotropicFilteringLevel
	{
		get => (int)_object.AnisotropicFilteringLevel;
		set => _object.AnisotropicFilteringLevel = (Godot.Viewport.AnisotropicFiltering)value;
	}

	public float FsrSharpness
	{
		get => _object.FsrSharpness;
		set => _object.FsrSharpness = value;
	}

	public int VrsMode
	{
		get => (int)_object.VrsMode;
		set => _object.VrsMode = (Godot.Viewport.VrsModeEnum)value;
	}

	public int VrsUpdateMode
	{
		get => (int)_object.VrsUpdateMode;
		set => _object.VrsUpdateMode = (Godot.Viewport.VrsUpdateModeEnum)value;
	}

	public Texture2D VrsTexture
	{
		get => _object.VrsTexture;
		set => _object.VrsTexture = value;
	}

	public int CanvasItemDefaultTextureFilter
	{
		get => (int)_object.CanvasItemDefaultTextureFilter;
		set => _object.CanvasItemDefaultTextureFilter = (Godot.Viewport.DefaultCanvasItemTextureFilter)value;
	}

	public int CanvasItemDefaultTextureRepeat
	{
		get => (int)_object.CanvasItemDefaultTextureRepeat;
		set => _object.CanvasItemDefaultTextureRepeat = (Godot.Viewport.DefaultCanvasItemTextureRepeat)value;
	}

	public bool AudioListenerEnable2d
	{
		get => (bool)_object.Get("audio_listener_enable_2d");
		set => _object.Set("audio_listener_enable_2d", value);
	}

	public bool AudioListenerEnable3d
	{
		get => (bool)_object.Get("audio_listener_enable_3d");
		set => _object.Set("audio_listener_enable_3d", value);
	}

	public bool PhysicsObjectPicking
	{
		get => _object.PhysicsObjectPicking;
		set => _object.PhysicsObjectPicking = value;
	}

	public bool PhysicsObjectPickingSort
	{
		get => _object.PhysicsObjectPickingSort;
		set => _object.PhysicsObjectPickingSort = value;
	}

	public bool PhysicsObjectPickingFirstOnly
	{
		get => _object.PhysicsObjectPickingFirstOnly;
		set => _object.PhysicsObjectPickingFirstOnly = value;
	}

	public bool GuiDisableInput
	{
		get => _object.GuiDisableInput;
		set => _object.GuiDisableInput = value;
	}

	public bool GuiSnapControlsToPixels
	{
		get => _object.GuiSnapControlsToPixels;
		set => _object.GuiSnapControlsToPixels = value;
	}

	public bool GuiEmbedSubwindows
	{
		get => _object.GuiEmbedSubwindows;
		set => _object.GuiEmbedSubwindows = value;
	}

	public int GuiDragThreshold
	{
		get => _object.GuiDragThreshold;
		set => _object.GuiDragThreshold = value;
	}

	public int SdfOversize
	{
		get => (int)_object.SdfOversize;
		set => _object.SdfOversize = (Godot.Viewport.SdfOversizeEnum)value;
	}

	public int SdfScale
	{
		get => (int)_object.SdfScale;
		set => _object.SdfScale = (Godot.Viewport.SdfScaleEnum)value;
	}

	public int PositionalShadowAtlasSize
	{
		get => _object.PositionalShadowAtlasSize;
		set => _object.PositionalShadowAtlasSize = value;
	}

	public bool PositionalShadowAtlas16Bits
	{
		get => _object.PositionalShadowAtlas16Bits;
		set => _object.PositionalShadowAtlas16Bits = value;
	}

	public int PositionalShadowAtlasQuad0
	{
		get => (int)_object.PositionalShadowAtlasQuad0;
		set => _object.PositionalShadowAtlasQuad0 = (Godot.Viewport.PositionalShadowAtlasQuadrantSubdiv)value;
	}

	public int PositionalShadowAtlasQuad1
	{
		get => (int)_object.PositionalShadowAtlasQuad1;
		set => _object.PositionalShadowAtlasQuad1 = (Godot.Viewport.PositionalShadowAtlasQuadrantSubdiv)value;
	}

	public int PositionalShadowAtlasQuad2
	{
		get => (int)_object.PositionalShadowAtlasQuad2;
		set => _object.PositionalShadowAtlasQuad2 = (Godot.Viewport.PositionalShadowAtlasQuadrantSubdiv)value;
	}

	public int PositionalShadowAtlasQuad3
	{
		get => (int)_object.PositionalShadowAtlasQuad3;
		set => _object.PositionalShadowAtlasQuad3 = (Godot.Viewport.PositionalShadowAtlasQuadrantSubdiv)value;
	}

	public Godot.Transform2D CanvasTransform
	{
		get => _object.CanvasTransform;
		set => _object.CanvasTransform = value;
	}

	public Godot.Transform2D GlobalCanvasTransform
	{
		get => _object.GlobalCanvasTransform;
		set => _object.GlobalCanvasTransform = value;
	}

	public int CanvasCullMask
	{
		get => (int)_object.CanvasCullMask;
		set => _object.CanvasCullMask = (uint)value;
	}

	public bool Oversampling
	{
		get => _object.Oversampling;
		set => _object.Oversampling = value;
	}

	public float OversamplingOverride
	{
		get => _object.OversamplingOverride;
		set => _object.OversamplingOverride = value;
	}

	public Godot.StringName Name
	{
		get => _object.Name;
		set => _object.Name = value;
	}

	public bool UniqueNameInOwner
	{
		get => _object.UniqueNameInOwner;
		set => _object.UniqueNameInOwner = value;
	}

	public string SceneFilePath
	{
		get => _object.SceneFilePath;
		set => _object.SceneFilePath = value;
	}

	public Node Owner
	{
		get => _object.Owner;
		set => _object.Owner = value;
	}

	public MultiplayerApi Multiplayer
	{
		get => _object.Multiplayer;
	}

	public int ProcessMode
	{
		get => (int)_object.ProcessMode;
		set => _object.ProcessMode = (Godot.Node.ProcessModeEnum)value;
	}

	public int ProcessPriority
	{
		get => _object.ProcessPriority;
		set => _object.ProcessPriority = value;
	}

	public int ProcessPhysicsPriority
	{
		get => _object.ProcessPhysicsPriority;
		set => _object.ProcessPhysicsPriority = value;
	}

	public int ProcessThreadGroup
	{
		get => (int)_object.ProcessThreadGroup;
		set => _object.ProcessThreadGroup = (Godot.Node.ProcessThreadGroupEnum)value;
	}

	public int ProcessThreadGroupOrder
	{
		get => _object.ProcessThreadGroupOrder;
		set => _object.ProcessThreadGroupOrder = value;
	}

	public int ProcessThreadMessages
	{
		get => (int)_object.ProcessThreadMessages;
		set => _object.ProcessThreadMessages = (Godot.Node.ProcessThreadMessagesEnum)value;
	}

	public int PhysicsInterpolationMode
	{
		get => (int)_object.PhysicsInterpolationMode;
		set => _object.PhysicsInterpolationMode = (Godot.Node.PhysicsInterpolationModeEnum)value;
	}

	public int AutoTranslateMode
	{
		get => (int)_object.AutoTranslateMode;
		set => _object.AutoTranslateMode = (Godot.Node.AutoTranslateModeEnum)value;
	}

	public string EditorDescription
	{
		get => _object.EditorDescription;
		set => _object.EditorDescription = value;
	}

	#endregion

	#region Methods

	public void Reshow(VoxelGraphFunction @_unnamed_arg0)
	{
		_object.Call(MethodName.Reshow, @_unnamed_arg0);
	}

	#endregion

	#region Inherited Methods

	public Button GetCancelButton()
	{
		return _object.GetCancelButton();
	}

	public void SetCancelButtonText(string @text)
	{
		_object.SetCancelButtonText(@text);
	}

	public string GetCancelButtonText()
	{
		return _object.GetCancelButtonText();
	}

	public Button GetOkButton()
	{
		return _object.GetOkButton();
	}

	public Label GetLabel()
	{
		return _object.GetLabel();
	}

	public void SetHideOnOk(bool @enabled)
	{
		_object.SetHideOnOk(@enabled);
	}

	public bool GetHideOnOk()
	{
		return _object.GetHideOnOk();
	}

	public void SetCloseOnEscape(bool @enabled)
	{
		_object.SetCloseOnEscape(@enabled);
	}

	public bool GetCloseOnEscape()
	{
		return _object.GetCloseOnEscape();
	}

	public Button AddButton(string @text, bool @right = false, string @action = "")
	{
		return _object.AddButton(@text, @right, @action);
	}

	public Button AddCancelButton(string @name)
	{
		return _object.AddCancelButton(@name);
	}

	public void RemoveButton(Button @button)
	{
		_object.RemoveButton(@button);
	}

	public void RegisterTextEnter(LineEdit @line_edit)
	{
		_object.RegisterTextEnter(@line_edit);
	}

	public void SetText(string @text)
	{
		_object.SetText(@text);
	}

	public string GetText()
	{
		return _object.GetText();
	}

	public void SetAutowrap(bool @autowrap)
	{
		_object.SetAutowrap(@autowrap);
	}

	public bool HasAutowrap()
	{
		return _object.HasAutowrap();
	}

	public void SetOkButtonText(string @text)
	{
		_object.SetOkButtonText(@text);
	}

	public string GetOkButtonText()
	{
		return _object.GetOkButtonText();
	}

	public void SetTitle(string @title)
	{
		_object.SetTitle(@title);
	}

	public string GetTitle()
	{
		return _object.GetTitle();
	}

	public void SetInitialPosition(Window.WindowInitialPosition @initial_position)
	{
		_object.SetInitialPosition(@initial_position);
	}

	public Window.WindowInitialPosition GetInitialPosition()
	{
		return _object.GetInitialPosition();
	}

	public void SetCurrentScreen(int @index)
	{
		_object.SetCurrentScreen(@index);
	}

	public int GetCurrentScreen()
	{
		return _object.GetCurrentScreen();
	}

	public void SetPosition(Godot.Vector2I @position)
	{
		_object.SetPosition(@position);
	}

	public Godot.Vector2I GetPosition()
	{
		return _object.GetPosition();
	}

	public void MoveToCenter()
	{
		_object.MoveToCenter();
	}

	public void SetSize(Godot.Vector2I @size)
	{
		_object.SetSize(@size);
	}

	public Godot.Vector2I GetSize()
	{
		return _object.GetSize();
	}

	public void ResetSize()
	{
		_object.ResetSize();
	}

	public Godot.Vector2I GetPositionWithDecorations()
	{
		return _object.GetPositionWithDecorations();
	}

	public Godot.Vector2I GetSizeWithDecorations()
	{
		return _object.GetSizeWithDecorations();
	}

	public void SetMaxSize(Godot.Vector2I @max_size)
	{
		_object.SetMaxSize(@max_size);
	}

	public Godot.Vector2I GetMaxSize()
	{
		return _object.GetMaxSize();
	}

	public void SetMinSize(Godot.Vector2I @min_size)
	{
		_object.SetMinSize(@min_size);
	}

	public Godot.Vector2I GetMinSize()
	{
		return _object.GetMinSize();
	}

	public void SetMode(Window.ModeEnum @mode)
	{
		_object.SetMode(@mode);
	}

	public Window.ModeEnum GetMode()
	{
		return _object.GetMode();
	}

	public void SetFlag(Window.Flags @flag, bool @enabled)
	{
		_object.SetFlag(@flag, @enabled);
	}

	public bool GetFlag(Window.Flags @flag)
	{
		return _object.GetFlag(@flag);
	}

	public bool IsMaximizeAllowed()
	{
		return _object.IsMaximizeAllowed();
	}

	public void RequestAttention()
	{
		_object.RequestAttention();
	}

	public void MoveToForeground()
	{
		_object.MoveToForeground();
	}

	public void SetVisible(bool @visible)
	{
		_object.SetVisible(@visible);
	}

	public bool IsVisible()
	{
		return _object.IsVisible();
	}

	public void Hide()
	{
		_object.Hide();
	}

	public void Show()
	{
		_object.Show();
	}

	public void SetTransient(bool @transient)
	{
		_object.SetTransient(@transient);
	}

	public bool IsTransient()
	{
		return _object.IsTransient();
	}

	public void SetTransientToFocused(bool @enable)
	{
		_object.SetTransientToFocused(@enable);
	}

	public bool IsTransientToFocused()
	{
		return _object.IsTransientToFocused();
	}

	public void SetExclusive(bool @exclusive)
	{
		_object.SetExclusive(@exclusive);
	}

	public bool IsExclusive()
	{
		return _object.IsExclusive();
	}

	public void SetUnparentWhenInvisible(bool @unparent)
	{
		_object.SetUnparentWhenInvisible(@unparent);
	}

	public bool CanDraw()
	{
		return _object.CanDraw();
	}

	public bool HasFocus()
	{
		return _object.HasFocus();
	}

	public void GrabFocus()
	{
		_object.GrabFocus();
	}

	public void StartDrag()
	{
		_object.StartDrag();
	}

	public void StartResize(DisplayServer.WindowResizeEdge @edge)
	{
		_object.StartResize(@edge);
	}

	public void SetImeActive(bool @active)
	{
		_object.SetImeActive(@active);
	}

	public void SetImePosition(Godot.Vector2I @position)
	{
		_object.SetImePosition(@position);
	}

	public bool IsEmbedded()
	{
		return _object.IsEmbedded();
	}

	public Godot.Vector2 GetContentsMinimumSize()
	{
		return _object.GetContentsMinimumSize();
	}

	public void SetForceNative(bool @force_native)
	{
		_object.SetForceNative(@force_native);
	}

	public bool GetForceNative()
	{
		return _object.GetForceNative();
	}

	public void SetContentScaleSize(Godot.Vector2I @size)
	{
		_object.SetContentScaleSize(@size);
	}

	public Godot.Vector2I GetContentScaleSize()
	{
		return _object.GetContentScaleSize();
	}

	public void SetContentScaleMode(Window.ContentScaleModeEnum @mode)
	{
		_object.SetContentScaleMode(@mode);
	}

	public Window.ContentScaleModeEnum GetContentScaleMode()
	{
		return _object.GetContentScaleMode();
	}

	public void SetContentScaleAspect(Window.ContentScaleAspectEnum @aspect)
	{
		_object.SetContentScaleAspect(@aspect);
	}

	public Window.ContentScaleAspectEnum GetContentScaleAspect()
	{
		return _object.GetContentScaleAspect();
	}

	public void SetContentScaleStretch(Window.ContentScaleStretchEnum @stretch)
	{
		_object.SetContentScaleStretch(@stretch);
	}

	public Window.ContentScaleStretchEnum GetContentScaleStretch()
	{
		return _object.GetContentScaleStretch();
	}

	public void SetNonclientArea(Godot.Rect2I @area)
	{
		_object.SetNonclientArea(@area);
	}

	public Godot.Rect2I GetNonclientArea()
	{
		return _object.GetNonclientArea();
	}

	public void SetKeepTitleVisible(bool @title_visible)
	{
		_object.SetKeepTitleVisible(@title_visible);
	}

	public bool GetKeepTitleVisible()
	{
		return _object.GetKeepTitleVisible();
	}

	public void SetContentScaleFactor(float @factor)
	{
		_object.SetContentScaleFactor(@factor);
	}

	public float GetContentScaleFactor()
	{
		return _object.GetContentScaleFactor();
	}

	public void SetMousePassthroughPolygon(Godot.Vector2[] @polygon)
	{
		_object.SetMousePassthroughPolygon(@polygon);
	}

	public Godot.Vector2[] GetMousePassthroughPolygon()
	{
		return _object.GetMousePassthroughPolygon();
	}

	public void SetWrapControls(bool @enable)
	{
		_object.SetWrapControls(@enable);
	}

	public bool IsWrappingControls()
	{
		return _object.IsWrappingControls();
	}

	public void ChildControlsChanged()
	{
		_object.ChildControlsChanged();
	}

	public void SetTheme(Theme @theme)
	{
		_object.SetTheme(@theme);
	}

	public Theme GetTheme()
	{
		return _object.GetTheme();
	}

	public void SetThemeTypeVariation(Godot.StringName @theme_type)
	{
		_object.SetThemeTypeVariation(@theme_type);
	}

	public Godot.StringName GetThemeTypeVariation()
	{
		return _object.GetThemeTypeVariation();
	}

	public void BeginBulkThemeOverride()
	{
		_object.BeginBulkThemeOverride();
	}

	public void EndBulkThemeOverride()
	{
		_object.EndBulkThemeOverride();
	}

	public void AddThemeIconOverride(Godot.StringName @name, Texture2D @texture)
	{
		_object.AddThemeIconOverride(@name, @texture);
	}

	public void AddThemeStyleboxOverride(Godot.StringName @name, StyleBox @stylebox)
	{
		_object.AddThemeStyleboxOverride(@name, @stylebox);
	}

	public void AddThemeFontOverride(Godot.StringName @name, Font @font)
	{
		_object.AddThemeFontOverride(@name, @font);
	}

	public void AddThemeFontSizeOverride(Godot.StringName @name, int @font_size)
	{
		_object.AddThemeFontSizeOverride(@name, @font_size);
	}

	public void AddThemeColorOverride(Godot.StringName @name, Godot.Color @color)
	{
		_object.AddThemeColorOverride(@name, @color);
	}

	public void AddThemeConstantOverride(Godot.StringName @name, int @constant)
	{
		_object.AddThemeConstantOverride(@name, @constant);
	}

	public void RemoveThemeIconOverride(Godot.StringName @name)
	{
		_object.RemoveThemeIconOverride(@name);
	}

	public void RemoveThemeStyleboxOverride(Godot.StringName @name)
	{
		_object.RemoveThemeStyleboxOverride(@name);
	}

	public void RemoveThemeFontOverride(Godot.StringName @name)
	{
		_object.RemoveThemeFontOverride(@name);
	}

	public void RemoveThemeFontSizeOverride(Godot.StringName @name)
	{
		_object.RemoveThemeFontSizeOverride(@name);
	}

	public void RemoveThemeColorOverride(Godot.StringName @name)
	{
		_object.RemoveThemeColorOverride(@name);
	}

	public void RemoveThemeConstantOverride(Godot.StringName @name)
	{
		_object.RemoveThemeConstantOverride(@name);
	}

	public Texture2D GetThemeIcon(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeIcon(@name, @theme_type);
	}

	public StyleBox GetThemeStylebox(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeStylebox(@name, @theme_type);
	}

	public Font GetThemeFont(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeFont(@name, @theme_type);
	}

	public int GetThemeFontSize(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeFontSize(@name, @theme_type);
	}

	public Godot.Color GetThemeColor(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeColor(@name, @theme_type);
	}

	public int GetThemeConstant(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.GetThemeConstant(@name, @theme_type);
	}

	public bool HasThemeIconOverride(Godot.StringName @name)
	{
		return _object.HasThemeIconOverride(@name);
	}

	public bool HasThemeStyleboxOverride(Godot.StringName @name)
	{
		return _object.HasThemeStyleboxOverride(@name);
	}

	public bool HasThemeFontOverride(Godot.StringName @name)
	{
		return _object.HasThemeFontOverride(@name);
	}

	public bool HasThemeFontSizeOverride(Godot.StringName @name)
	{
		return _object.HasThemeFontSizeOverride(@name);
	}

	public bool HasThemeColorOverride(Godot.StringName @name)
	{
		return _object.HasThemeColorOverride(@name);
	}

	public bool HasThemeConstantOverride(Godot.StringName @name)
	{
		return _object.HasThemeConstantOverride(@name);
	}

	public bool HasThemeIcon(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeIcon(@name, @theme_type);
	}

	public bool HasThemeStylebox(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeStylebox(@name, @theme_type);
	}

	public bool HasThemeFont(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeFont(@name, @theme_type);
	}

	public bool HasThemeFontSize(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeFontSize(@name, @theme_type);
	}

	public bool HasThemeColor(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeColor(@name, @theme_type);
	}

	public bool HasThemeConstant(Godot.StringName @name, Godot.StringName @theme_type = null)
	{
		@theme_type ??= "";
		return _object.HasThemeConstant(@name, @theme_type);
	}

	public float GetThemeDefaultBaseScale()
	{
		return _object.GetThemeDefaultBaseScale();
	}

	public Font GetThemeDefaultFont()
	{
		return _object.GetThemeDefaultFont();
	}

	public int GetThemeDefaultFontSize()
	{
		return _object.GetThemeDefaultFontSize();
	}

	public int GetWindowId()
	{
		return _object.GetWindowId();
	}

	public void SetAccessibilityName(string @name)
	{
		_object.SetAccessibilityName(@name);
	}

	public string GetAccessibilityName()
	{
		return _object.GetAccessibilityName();
	}

	public void SetAccessibilityDescription(string @description)
	{
		_object.SetAccessibilityDescription(@description);
	}

	public string GetAccessibilityDescription()
	{
		return _object.GetAccessibilityDescription();
	}

	public static Window GetFocusedWindow()
	{
		return Window.GetFocusedWindow();
	}

	public void SetLayoutDirection(Window.LayoutDirection @direction)
	{
		_object.SetLayoutDirection(@direction);
	}

	public Window.LayoutDirection GetLayoutDirection()
	{
		return _object.GetLayoutDirection();
	}

	public bool IsLayoutRtl()
	{
		return _object.IsLayoutRtl();
	}

	public void SetAutoTranslate(bool @enable)
	{
		_object.SetAutoTranslate(@enable);
	}

	public bool IsAutoTranslating()
	{
		return _object.IsAutoTranslating();
	}

	public void SetUseFontOversampling(bool @enable)
	{
		_object.SetUseFontOversampling(@enable);
	}

	public bool IsUsingFontOversampling()
	{
		return _object.IsUsingFontOversampling();
	}

	public void Popup(Godot.Rect2I @rect = default)
	{
		_object.Popup(@rect);
	}

	public void PopupOnParent(Godot.Rect2I @parent_rect)
	{
		_object.PopupOnParent(@parent_rect);
	}

	public void PopupCentered(Godot.Vector2I @minsize = default)
	{
		_object.PopupCentered(@minsize);
	}

	public void PopupCenteredRatio(float @ratio = 0.8f)
	{
		_object.PopupCenteredRatio(@ratio);
	}

	public void PopupCenteredClamped(Godot.Vector2I @minsize = default, float @fallback_ratio = 0.75f)
	{
		_object.PopupCenteredClamped(@minsize, @fallback_ratio);
	}

	public void PopupExclusive(Node @from_node, Godot.Rect2I @rect = default)
	{
		_object.PopupExclusive(@from_node, @rect);
	}

	public void PopupExclusiveOnParent(Node @from_node, Godot.Rect2I @parent_rect)
	{
		_object.PopupExclusiveOnParent(@from_node, @parent_rect);
	}

	public void PopupExclusiveCentered(Node @from_node, Godot.Vector2I @minsize = default)
	{
		_object.PopupExclusiveCentered(@from_node, @minsize);
	}

	public void PopupExclusiveCenteredRatio(Node @from_node, float @ratio = 0.8f)
	{
		_object.PopupExclusiveCenteredRatio(@from_node, @ratio);
	}

	public void PopupExclusiveCenteredClamped(Node @from_node, Godot.Vector2I @minsize = default, float @fallback_ratio = 0.75f)
	{
		_object.PopupExclusiveCenteredClamped(@from_node, @minsize, @fallback_ratio);
	}

	public void SetWorld2d(World2D @world_2d)
	{
		_object.Call("set_world_2d", @world_2d);
	}

	public World2D GetWorld2d()
	{
		return (Godot.World2D)_object.Get("world_2d");
	}

	public World2D FindWorld2d()
	{
		return (Godot.World2D)_object.Call("find_world_2d");
	}

	public void SetCanvasTransform(Godot.Transform2D @xform)
	{
		_object.SetCanvasTransform(@xform);
	}

	public Godot.Transform2D GetCanvasTransform()
	{
		return _object.GetCanvasTransform();
	}

	public void SetGlobalCanvasTransform(Godot.Transform2D @xform)
	{
		_object.SetGlobalCanvasTransform(@xform);
	}

	public Godot.Transform2D GetGlobalCanvasTransform()
	{
		return _object.GetGlobalCanvasTransform();
	}

	public Godot.Transform2D GetStretchTransform()
	{
		return _object.GetStretchTransform();
	}

	public Godot.Transform2D GetFinalTransform()
	{
		return _object.GetFinalTransform();
	}

	public Godot.Transform2D GetScreenTransform()
	{
		return _object.GetScreenTransform();
	}

	public Godot.Rect2 GetVisibleRect()
	{
		return _object.GetVisibleRect();
	}

	public void SetTransparentBackground(bool @enable)
	{
		_object.SetTransparentBackground(@enable);
	}

	public bool HasTransparentBackground()
	{
		return _object.HasTransparentBackground();
	}

	public void SetUseHdr2d(bool @enable)
	{
		_object.SetUseHdr2D(@enable);
	}

	public bool IsUsingHdr2d()
	{
		return (bool)_object.Call("is_using_hdr_2d");
	}

	public void SetMsaa2d(Viewport.Msaa @msaa)
	{
		_object.Call("set_msaa_2d", (int)@msaa);
	}

	public Viewport.Msaa GetMsaa2d()
	{
		return (Godot.Viewport.Msaa)(int)_object.Call("get_msaa_2d");
	}

	public void SetMsaa3d(Viewport.Msaa @msaa)
	{
		_object.Call("set_msaa_3d", (int)@msaa);
	}

	public Viewport.Msaa GetMsaa3d()
	{
		return (Godot.Viewport.Msaa)(int)_object.Call("get_msaa_3d");
	}

	public void SetScreenSpaceAa(Viewport.ScreenSpaceAAEnum @screen_space_aa)
	{
		_object.Call("set_screen_space_aa", (int)@screen_space_aa);
	}

	public Viewport.ScreenSpaceAAEnum GetScreenSpaceAa()
	{
		return (Godot.Viewport.ScreenSpaceAAEnum)(int)_object.Call("get_screen_space_aa");
	}

	public void SetUseTaa(bool @enable)
	{
		_object.SetUseTaa(@enable);
	}

	public bool IsUsingTaa()
	{
		return _object.IsUsingTaa();
	}

	public void SetUseDebanding(bool @enable)
	{
		_object.SetUseDebanding(@enable);
	}

	public bool IsUsingDebanding()
	{
		return _object.IsUsingDebanding();
	}

	public void SetUseOcclusionCulling(bool @enable)
	{
		_object.SetUseOcclusionCulling(@enable);
	}

	public bool IsUsingOcclusionCulling()
	{
		return _object.IsUsingOcclusionCulling();
	}

	public void SetDebugDraw(Viewport.DebugDrawEnum @debug_draw)
	{
		_object.SetDebugDraw(@debug_draw);
	}

	public Viewport.DebugDrawEnum GetDebugDraw()
	{
		return _object.GetDebugDraw();
	}

	public void SetUseOversampling(bool @enable)
	{
		_object.SetUseOversampling(@enable);
	}

	public bool IsUsingOversampling()
	{
		return _object.IsUsingOversampling();
	}

	public void SetOversamplingOverride(float @oversampling)
	{
		_object.SetOversamplingOverride(@oversampling);
	}

	public float GetOversamplingOverride()
	{
		return _object.GetOversamplingOverride();
	}

	public float GetOversampling()
	{
		return _object.GetOversampling();
	}

	public int GetRenderInfo(Viewport.RenderInfoType @type, Viewport.RenderInfo @info)
	{
		return _object.GetRenderInfo(@type, @info);
	}

	public ViewportTexture GetTexture()
	{
		return _object.GetTexture();
	}

	public void SetPhysicsObjectPicking(bool @enable)
	{
		_object.SetPhysicsObjectPicking(@enable);
	}

	public bool GetPhysicsObjectPicking()
	{
		return _object.GetPhysicsObjectPicking();
	}

	public void SetPhysicsObjectPickingSort(bool @enable)
	{
		_object.SetPhysicsObjectPickingSort(@enable);
	}

	public bool GetPhysicsObjectPickingSort()
	{
		return _object.GetPhysicsObjectPickingSort();
	}

	public void SetPhysicsObjectPickingFirstOnly(bool @enable)
	{
		_object.SetPhysicsObjectPickingFirstOnly(@enable);
	}

	public bool GetPhysicsObjectPickingFirstOnly()
	{
		return _object.GetPhysicsObjectPickingFirstOnly();
	}

	public Godot.Rid GetViewportRid()
	{
		return _object.GetViewportRid();
	}

	public void PushTextInput(string @text)
	{
		_object.PushTextInput(@text);
	}

	public void PushInput(InputEvent @event, bool @in_local_coords = false)
	{
		_object.PushInput(@event, @in_local_coords);
	}

	public void PushUnhandledInput(InputEvent @event, bool @in_local_coords = false)
	{
		_object.PushUnhandledInput(@event, @in_local_coords);
	}

	public void NotifyMouseEntered()
	{
		_object.NotifyMouseEntered();
	}

	public void NotifyMouseExited()
	{
		_object.NotifyMouseExited();
	}

	public Godot.Vector2 GetMousePosition()
	{
		return _object.GetMousePosition();
	}

	public void WarpMouse(Godot.Vector2 @position)
	{
		_object.WarpMouse(@position);
	}

	public void UpdateMouseCursorState()
	{
		_object.UpdateMouseCursorState();
	}

	public void GuiCancelDrag()
	{
		_object.GuiCancelDrag();
	}

	public Variant GuiGetDragData()
	{
		return _object.GuiGetDragData();
	}

	public string GuiGetDragDescription()
	{
		return _object.GuiGetDragDescription();
	}

	public void GuiSetDragDescription(string @description)
	{
		_object.GuiSetDragDescription(@description);
	}

	public bool GuiIsDragging()
	{
		return _object.GuiIsDragging();
	}

	public bool GuiIsDragSuccessful()
	{
		return _object.GuiIsDragSuccessful();
	}

	public void GuiReleaseFocus()
	{
		_object.GuiReleaseFocus();
	}

	public Control GuiGetFocusOwner()
	{
		return _object.GuiGetFocusOwner();
	}

	public Control GuiGetHoveredControl()
	{
		return _object.GuiGetHoveredControl();
	}

	public void SetDisableInput(bool @disable)
	{
		_object.SetDisableInput(@disable);
	}

	public bool IsInputDisabled()
	{
		return _object.IsInputDisabled();
	}

	public void SetPositionalShadowAtlasSize(int @size)
	{
		_object.SetPositionalShadowAtlasSize(@size);
	}

	public int GetPositionalShadowAtlasSize()
	{
		return _object.GetPositionalShadowAtlasSize();
	}

	public void SetPositionalShadowAtlas16Bits(bool @enable)
	{
		_object.SetPositionalShadowAtlas16Bits(@enable);
	}

	public bool GetPositionalShadowAtlas16Bits()
	{
		return _object.GetPositionalShadowAtlas16Bits();
	}

	public void SetSnapControlsToPixels(bool @enabled)
	{
		_object.SetSnapControlsToPixels(@enabled);
	}

	public bool IsSnapControlsToPixelsEnabled()
	{
		return _object.IsSnapControlsToPixelsEnabled();
	}

	public void SetSnap2dTransformsToPixel(bool @enabled)
	{
		_object.SetSnap2DTransformsToPixel(@enabled);
	}

	public bool IsSnap2dTransformsToPixelEnabled()
	{
		return (bool)_object.Call("is_snap_2d_transforms_to_pixel_enabled");
	}

	public void SetSnap2dVerticesToPixel(bool @enabled)
	{
		_object.SetSnap2DVerticesToPixel(@enabled);
	}

	public bool IsSnap2dVerticesToPixelEnabled()
	{
		return (bool)_object.Call("is_snap_2d_vertices_to_pixel_enabled");
	}

	public void SetPositionalShadowAtlasQuadrantSubdiv(int @quadrant, Viewport.PositionalShadowAtlasQuadrantSubdiv @subdiv)
	{
		_object.SetPositionalShadowAtlasQuadrantSubdiv(@quadrant, (Godot.Viewport.PositionalShadowAtlasQuadrantSubdiv)@subdiv);
	}

	public Viewport.PositionalShadowAtlasQuadrantSubdiv GetPositionalShadowAtlasQuadrantSubdiv(int @quadrant)
	{
		return _object.GetPositionalShadowAtlasQuadrantSubdiv(@quadrant);
	}

	public void SetInputAsHandled()
	{
		_object.SetInputAsHandled();
	}

	public bool IsInputHandled()
	{
		return _object.IsInputHandled();
	}

	public void SetHandleInputLocally(bool @enable)
	{
		_object.SetHandleInputLocally(@enable);
	}

	public bool IsHandlingInputLocally()
	{
		return _object.IsHandlingInputLocally();
	}

	public void SetDefaultCanvasItemTextureFilter(Viewport.DefaultCanvasItemTextureFilter @mode)
	{
		_object.SetDefaultCanvasItemTextureFilter(@mode);
	}

	public Viewport.DefaultCanvasItemTextureFilter GetDefaultCanvasItemTextureFilter()
	{
		return _object.GetDefaultCanvasItemTextureFilter();
	}

	public void SetEmbeddingSubwindows(bool @enable)
	{
		_object.SetEmbeddingSubwindows(@enable);
	}

	public bool IsEmbeddingSubwindows()
	{
		return _object.IsEmbeddingSubwindows();
	}

	public Godot.Collections.Array<Godot.Window> GetEmbeddedSubwindows()
	{
		return _object.GetEmbeddedSubwindows();
	}

	public void SetDragThreshold(int @threshold)
	{
		_object.SetDragThreshold(@threshold);
	}

	public int GetDragThreshold()
	{
		return _object.GetDragThreshold();
	}

	public void SetCanvasCullMask(uint @mask)
	{
		_object.SetCanvasCullMask(@mask);
	}

	public uint GetCanvasCullMask()
	{
		return _object.GetCanvasCullMask();
	}

	public void SetCanvasCullMaskBit(uint @layer, bool @enable)
	{
		_object.SetCanvasCullMaskBit(@layer, @enable);
	}

	public bool GetCanvasCullMaskBit(uint @layer)
	{
		return _object.GetCanvasCullMaskBit(@layer);
	}

	public void SetDefaultCanvasItemTextureRepeat(Viewport.DefaultCanvasItemTextureRepeat @mode)
	{
		_object.SetDefaultCanvasItemTextureRepeat(@mode);
	}

	public Viewport.DefaultCanvasItemTextureRepeat GetDefaultCanvasItemTextureRepeat()
	{
		return _object.GetDefaultCanvasItemTextureRepeat();
	}

	public void SetSdfOversize(Viewport.SdfOversizeEnum @oversize)
	{
		_object.SetSdfOversize((Godot.Viewport.SdfOversizeEnum)@oversize);
	}

	public Viewport.SdfOversizeEnum GetSdfOversize()
	{
		return _object.GetSdfOversize();
	}

	public void SetSdfScale(Viewport.SdfScaleEnum @scale)
	{
		_object.SetSdfScale((Godot.Viewport.SdfScaleEnum)@scale);
	}

	public Viewport.SdfScaleEnum GetSdfScale()
	{
		return _object.GetSdfScale();
	}

	public void SetMeshLodThreshold(float @pixels)
	{
		_object.SetMeshLodThreshold(@pixels);
	}

	public float GetMeshLodThreshold()
	{
		return _object.GetMeshLodThreshold();
	}

	public void SetAsAudioListener2d(bool @enable)
	{
		_object.Call("set_as_audio_listener_2d", @enable);
	}

	public bool IsAudioListener2d()
	{
		return (bool)_object.Call("is_audio_listener_2d");
	}

	public AudioListener2D GetAudioListener2d()
	{
		return (Godot.AudioListener2D)_object.Call("get_audio_listener_2d");
	}

	public Camera2D GetCamera2d()
	{
		return (Godot.Camera2D)_object.Call("get_camera_2d");
	}

	public void SetWorld3d(World3D @world_3d)
	{
		_object.SetWorld3D(@world_3d);
	}

	public World3D GetWorld3d()
	{
		return (Godot.World3D)_object.Call("get_world_3d");
	}

	public World3D FindWorld3d()
	{
		return (Godot.World3D)_object.Call("find_world_3d");
	}

	public void SetUseOwnWorld3d(bool @enable)
	{
		_object.Call("set_use_own_world_3d", @enable);
	}

	public bool IsUsingOwnWorld3d()
	{
		return (bool)_object.Call("is_using_own_world_3d");
	}

	public AudioListener3D GetAudioListener3d()
	{
		return (Godot.AudioListener3D)_object.Call("get_audio_listener_3d");
	}

	public Camera3D GetCamera3d()
	{
		return (Godot.Camera3D)_object.Call("get_camera_3d");
	}

	public void SetAsAudioListener3d(bool @enable)
	{
		_object.Call("set_as_audio_listener_3d", @enable);
	}

	public bool IsAudioListener3d()
	{
		return (bool)_object.Call("is_audio_listener_3d");
	}

	public void SetDisable3d(bool @disable)
	{
		_object.Call("set_disable_3d", @disable);
	}

	public bool Is3dDisabled()
	{
		return (bool)_object.Call("is_3d_disabled");
	}

	public void SetUseXr(bool @use)
	{
		_object.SetUseXR(@use);
	}

	public bool IsUsingXr()
	{
		return (bool)_object.Call("is_using_xr");
	}

	public void SetScaling3dMode(Viewport.Scaling3DModeEnum @scaling_3d_mode)
	{
		_object.SetScaling3DMode(@scaling_3d_mode);
	}

	public Viewport.Scaling3DModeEnum GetScaling3dMode()
	{
		return (Viewport.Scaling3DModeEnum)(int)_object.Call("get_scaling_3d_mode");
	}

	public void SetScaling3dScale(float @scale)
	{
		_object.Call("set_scaling_3d_scale", @scale);
	}

	public float GetScaling3dScale()
	{
		return (float)_object.Call("get_scaling_3d_scale");
	}

	public void SetFsrSharpness(float @fsr_sharpness)
	{
		_object.SetFsrSharpness(@fsr_sharpness);
	}

	public float GetFsrSharpness()
	{
		return _object.GetFsrSharpness();
	}

	public void SetTextureMipmapBias(float @texture_mipmap_bias)
	{
		_object.SetTextureMipmapBias(@texture_mipmap_bias);
	}

	public float GetTextureMipmapBias()
	{
		return _object.GetTextureMipmapBias();
	}

	public void SetAnisotropicFilteringLevel(Viewport.AnisotropicFiltering @anisotropic_filtering_level)
	{
		_object.SetAnisotropicFilteringLevel(@anisotropic_filtering_level);
	}

	public Viewport.AnisotropicFiltering GetAnisotropicFilteringLevel()
	{
		return _object.GetAnisotropicFilteringLevel();
	}

	public void SetVrsMode(Viewport.VrsModeEnum @mode)
	{
		_object.SetVrsMode((Godot.Viewport.VrsModeEnum)@mode);
	}

	public Viewport.VrsModeEnum GetVrsMode()
	{
		return _object.GetVrsMode();
	}

	public void SetVrsUpdateMode(Viewport.VrsUpdateModeEnum @mode)
	{
		_object.SetVrsUpdateMode((Godot.Viewport.VrsUpdateModeEnum)@mode);
	}

	public Viewport.VrsUpdateModeEnum GetVrsUpdateMode()
	{
		return _object.GetVrsUpdateMode();
	}

	public void SetVrsTexture(Texture2D @texture)
	{
		_object.SetVrsTexture(@texture);
	}

	public Texture2D GetVrsTexture()
	{
		return _object.GetVrsTexture();
	}

	public static void PrintOrphanNodes()
	{
		Node.PrintOrphanNodes();
	}

	public static Godot.Collections.Array<int> GetOrphanNodeIds()
	{
		return Node.GetOrphanNodeIds();
	}

	public void AddSibling(Node @sibling, bool @force_readable_name = false)
	{
		_object.AddSibling(@sibling, @force_readable_name);
	}

	public void SetName(Godot.StringName @name)
	{
		_object.SetName(@name);
	}

	public Godot.StringName GetName()
	{
		return _object.GetName();
	}

	public void AddChild(Node @node, bool @force_readable_name = false, Node.InternalMode @internal = (Node.InternalMode)0)
	{
		_object.AddChild(@node, @force_readable_name, @internal);
	}

	public void RemoveChild(Node @node)
	{
		_object.RemoveChild(@node);
	}

	public void Reparent(Node @new_parent, bool @keep_global_transform = true)
	{
		_object.Reparent(@new_parent, @keep_global_transform);
	}

	public int GetChildCount(bool @include_internal = false)
	{
		return _object.GetChildCount(@include_internal);
	}

	public Godot.Collections.Array<Godot.Node> GetChildren(bool @include_internal = false)
	{
		return _object.GetChildren(@include_internal);
	}

	public Node GetChild(int @idx, bool @include_internal = false)
	{
		return _object.GetChild(@idx, @include_internal);
	}

	public bool HasNode(Godot.NodePath @path)
	{
		return _object.HasNode(@path);
	}

	public Node GetNode(Godot.NodePath @path)
	{
		return _object.GetNode(@path);
	}

	public Node GetNodeOrNull(Godot.NodePath @path)
	{
		return _object.GetNodeOrNull(@path);
	}

	public Node GetParent()
	{
		return _object.GetParent();
	}

	public Node FindChild(string @pattern, bool @recursive = true, bool @owned = true)
	{
		return _object.FindChild(@pattern, @recursive, @owned);
	}

	public Godot.Collections.Array<Godot.Node> FindChildren(string @pattern, string @type = "", bool @recursive = true, bool @owned = true)
	{
		return _object.FindChildren(@pattern, @type, @recursive, @owned);
	}

	public Node FindParent(string @pattern)
	{
		return _object.FindParent(@pattern);
	}

	public bool HasNodeAndResource(Godot.NodePath @path)
	{
		return _object.HasNodeAndResource(@path);
	}

	public Godot.Collections.Array GetNodeAndResource(Godot.NodePath @path)
	{
		return _object.GetNodeAndResource(@path);
	}

	public bool IsInsideTree()
	{
		return _object.IsInsideTree();
	}

	public bool IsPartOfEditedScene()
	{
		return _object.IsPartOfEditedScene();
	}

	public bool IsAncestorOf(Node @node)
	{
		return _object.IsAncestorOf(@node);
	}

	public bool IsGreaterThan(Node @node)
	{
		return _object.IsGreaterThan(@node);
	}

	public Godot.NodePath GetPath()
	{
		return _object.GetPath();
	}

	public Godot.NodePath GetPathTo(Node @node, bool @use_unique_path = false)
	{
		return _object.GetPathTo(@node, @use_unique_path);
	}

	public void AddToGroup(Godot.StringName @group, bool @persistent = false)
	{
		_object.AddToGroup(@group, @persistent);
	}

	public void RemoveFromGroup(Godot.StringName @group)
	{
		_object.RemoveFromGroup(@group);
	}

	public bool IsInGroup(Godot.StringName @group)
	{
		return _object.IsInGroup(@group);
	}

	public void MoveChild(Node @child_node, int @to_index)
	{
		_object.MoveChild(@child_node, @to_index);
	}

	public Godot.Collections.Array<StringName> GetGroups()
	{
		return _object.GetGroups();
	}

	public void SetOwner(Node @owner)
	{
		_object.SetOwner(@owner);
	}

	public Node GetOwner()
	{
		return _object.GetOwner();
	}

	public int GetIndex(bool @include_internal = false)
	{
		return _object.GetIndex(@include_internal);
	}

	public void PrintTree()
	{
		_object.PrintTree();
	}

	public void PrintTreePretty()
	{
		_object.PrintTreePretty();
	}

	public string GetTreeString()
	{
		return _object.GetTreeString();
	}

	public string GetTreeStringPretty()
	{
		return _object.GetTreeStringPretty();
	}

	public void SetSceneFilePath(string @scene_file_path)
	{
		_object.SetSceneFilePath(@scene_file_path);
	}

	public string GetSceneFilePath()
	{
		return _object.GetSceneFilePath();
	}

	public void PropagateNotification(int @what)
	{
		_object.PropagateNotification(@what);
	}

	public void PropagateCall(Godot.StringName @method, Godot.Collections.Array @args = null, bool @parent_first = false)
	{
		@args ??= new();
		_object.PropagateCall(@method, @args, @parent_first);
	}

	public void SetPhysicsProcess(bool @enable)
	{
		_object.SetPhysicsProcess(@enable);
	}

	public float GetPhysicsProcessDeltaTime()
	{
		return (float)_object.GetPhysicsProcessDeltaTime();
	}

	public bool IsPhysicsProcessing()
	{
		return _object.IsPhysicsProcessing();
	}

	public float GetProcessDeltaTime()
	{
		return (float)_object.GetProcessDeltaTime();
	}

	public void SetProcess(bool @enable)
	{
		_object.SetProcess(@enable);
	}

	public void SetProcessPriority(int @priority)
	{
		_object.SetProcessPriority(@priority);
	}

	public int GetProcessPriority()
	{
		return _object.GetProcessPriority();
	}

	public void SetPhysicsProcessPriority(int @priority)
	{
		_object.SetPhysicsProcessPriority(@priority);
	}

	public int GetPhysicsProcessPriority()
	{
		return _object.GetPhysicsProcessPriority();
	}

	public bool IsProcessing()
	{
		return _object.IsProcessing();
	}

	public void SetProcessInput(bool @enable)
	{
		_object.SetProcessInput(@enable);
	}

	public bool IsProcessingInput()
	{
		return _object.IsProcessingInput();
	}

	public void SetProcessShortcutInput(bool @enable)
	{
		_object.SetProcessShortcutInput(@enable);
	}

	public bool IsProcessingShortcutInput()
	{
		return _object.IsProcessingShortcutInput();
	}

	public void SetProcessUnhandledInput(bool @enable)
	{
		_object.SetProcessUnhandledInput(@enable);
	}

	public bool IsProcessingUnhandledInput()
	{
		return _object.IsProcessingUnhandledInput();
	}

	public void SetProcessUnhandledKeyInput(bool @enable)
	{
		_object.SetProcessUnhandledKeyInput(@enable);
	}

	public bool IsProcessingUnhandledKeyInput()
	{
		return _object.IsProcessingUnhandledKeyInput();
	}

	public void SetProcessMode(Node.ProcessModeEnum @mode)
	{
		_object.SetProcessMode(@mode);
	}

	public Node.ProcessModeEnum GetProcessMode()
	{
		return _object.GetProcessMode();
	}

	public bool CanProcess()
	{
		return _object.CanProcess();
	}

	public void SetProcessThreadGroup(Node.ProcessThreadGroupEnum @mode)
	{
		_object.SetProcessThreadGroup(@mode);
	}

	public Node.ProcessThreadGroupEnum GetProcessThreadGroup()
	{
		return _object.GetProcessThreadGroup();
	}

	public void SetProcessThreadMessages(Node.ProcessThreadMessagesEnum @flags)
	{
		_object.SetProcessThreadMessages(@flags);
	}

	public Node.ProcessThreadMessagesEnum GetProcessThreadMessages()
	{
		return _object.GetProcessThreadMessages();
	}

	public void SetProcessThreadGroupOrder(int @order)
	{
		_object.SetProcessThreadGroupOrder(@order);
	}

	public int GetProcessThreadGroupOrder()
	{
		return _object.GetProcessThreadGroupOrder();
	}

	public void QueueAccessibilityUpdate()
	{
		_object.QueueAccessibilityUpdate();
	}

	public Godot.Rid GetAccessibilityElement()
	{
		return _object.GetAccessibilityElement();
	}

	public void SetDisplayFolded(bool @fold)
	{
		_object.SetDisplayFolded(@fold);
	}

	public bool IsDisplayedFolded()
	{
		return _object.IsDisplayedFolded();
	}

	public void SetProcessInternal(bool @enable)
	{
		_object.SetProcessInternal(@enable);
	}

	public bool IsProcessingInternal()
	{
		return _object.IsProcessingInternal();
	}

	public void SetPhysicsProcessInternal(bool @enable)
	{
		_object.SetPhysicsProcessInternal(@enable);
	}

	public bool IsPhysicsProcessingInternal()
	{
		return _object.IsPhysicsProcessingInternal();
	}

	public void SetPhysicsInterpolationMode(Node.PhysicsInterpolationModeEnum @mode)
	{
		_object.SetPhysicsInterpolationMode(@mode);
	}

	public Node.PhysicsInterpolationModeEnum GetPhysicsInterpolationMode()
	{
		return _object.GetPhysicsInterpolationMode();
	}

	public bool IsPhysicsInterpolated()
	{
		return _object.IsPhysicsInterpolated();
	}

	public bool IsPhysicsInterpolatedAndEnabled()
	{
		return _object.IsPhysicsInterpolatedAndEnabled();
	}

	public void ResetPhysicsInterpolation()
	{
		_object.ResetPhysicsInterpolation();
	}

	public void SetAutoTranslateMode(Node.AutoTranslateModeEnum @mode)
	{
		_object.SetAutoTranslateMode(@mode);
	}

	public Node.AutoTranslateModeEnum GetAutoTranslateMode()
	{
		return _object.GetAutoTranslateMode();
	}

	public bool CanAutoTranslate()
	{
		return _object.CanAutoTranslate();
	}

	public void SetTranslationDomainInherited()
	{
		_object.SetTranslationDomainInherited();
	}

	public Window GetWindow()
	{
		return _object.GetWindow();
	}

	public Window GetLastExclusiveWindow()
	{
		return _object.GetLastExclusiveWindow();
	}

	public SceneTree GetTree()
	{
		return _object.GetTree();
	}

	public Tween CreateTween()
	{
		return _object.CreateTween();
	}

	public Node Duplicate(int @flags = 15)
	{
		return _object.Duplicate(@flags);
	}

	public void ReplaceBy(Node @node, bool @keep_groups = false)
	{
		_object.ReplaceBy(@node, @keep_groups);
	}

	public void SetSceneInstanceLoadPlaceholder(bool @load_placeholder)
	{
		_object.SetSceneInstanceLoadPlaceholder(@load_placeholder);
	}

	public bool GetSceneInstanceLoadPlaceholder()
	{
		return _object.GetSceneInstanceLoadPlaceholder();
	}

	public void SetEditableInstance(Node @node, bool @is_editable)
	{
		_object.SetEditableInstance(@node, @is_editable);
	}

	public bool IsEditableInstance(Node @node)
	{
		return _object.IsEditableInstance(@node);
	}

	public Viewport GetViewport()
	{
		return _object.GetViewport();
	}

	public void QueueFree()
	{
		_object.QueueFree();
	}

	public void RequestReady()
	{
		_object.RequestReady();
	}

	public bool IsNodeReady()
	{
		return _object.IsNodeReady();
	}

	public void SetMultiplayerAuthority(int @id, bool @recursive = true)
	{
		_object.SetMultiplayerAuthority(@id, @recursive);
	}

	public int GetMultiplayerAuthority()
	{
		return _object.GetMultiplayerAuthority();
	}

	public bool IsMultiplayerAuthority()
	{
		return _object.IsMultiplayerAuthority();
	}

	public MultiplayerApi GetMultiplayer()
	{
		return _object.GetMultiplayer();
	}

	public void RpcConfig(Godot.StringName @method, Variant @config)
	{
		_object.RpcConfig(@method, @config);
	}

	public Variant GetNodeRpcConfig()
	{
		return _object.GetNodeRpcConfig();
	}

	public void SetEditorDescription(string @editor_description)
	{
		_object.SetEditorDescription(@editor_description);
	}

	public string GetEditorDescription()
	{
		return _object.GetEditorDescription();
	}

	public void SetUniqueNameInOwner(bool @enable)
	{
		_object.SetUniqueNameInOwner(@enable);
	}

	public bool IsUniqueNameInOwner()
	{
		return _object.IsUniqueNameInOwner();
	}

	public string Atr(string @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Atr(@message, @context);
	}

	public string AtrN(string @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.AtrN(@message, @plural_message, @n, @context);
	}

	public Godot.Error Rpc(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Rpc(@method, varargs);
	}

	public Godot.Error RpcId(int @peer_id, Godot.StringName @method, params Variant[] varargs)
	{
		return _object.RpcId(@peer_id, @method, varargs);
	}

	public void UpdateConfigurationWarnings()
	{
		_object.UpdateConfigurationWarnings();
	}

	public Variant CallDeferredThreadGroup(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferredThreadGroup(@method, varargs);
	}

	public void SetDeferredThreadGroup(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferredThreadGroup(@property, @value);
	}

	public void NotifyDeferredThreadGroup(int @what)
	{
		_object.NotifyDeferredThreadGroup(@what);
	}

	public Variant CallThreadSafe(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallThreadSafe(@method, varargs);
	}

	public void SetThreadSafe(Godot.StringName @property, Variant @value)
	{
		_object.SetThreadSafe(@property, @value);
	}

	public void NotifyThreadSafe(int @what)
	{
		_object.NotifyThreadSafe(@what);
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action Confirmed
	{
		add
		{
			Connect(SignalName.Confirmed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Confirmed, Callable.From(value));
		}
	}

	public event Action Canceled
	{
		add
		{
			Connect(SignalName.Canceled, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Canceled, Callable.From(value));
		}
	}

	public event Action<Godot.StringName> CustomAction
	{
		add
		{
			Connect(SignalName.CustomAction, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.CustomAction, Callable.From(value));
		}
	}

	public event Action<InputEvent> WindowInput
	{
		add
		{
			Connect(SignalName.WindowInput, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.WindowInput, Callable.From(value));
		}
	}

	public event Action<InputEvent> NonclientWindowInput
	{
		add
		{
			Connect(SignalName.NonclientWindowInput, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.NonclientWindowInput, Callable.From(value));
		}
	}

	public event Action<string[]> FilesDropped
	{
		add
		{
			Connect(SignalName.FilesDropped, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.FilesDropped, Callable.From(value));
		}
	}

	public event Action MouseEntered
	{
		add
		{
			Connect(SignalName.MouseEntered, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.MouseEntered, Callable.From(value));
		}
	}

	public event Action MouseExited
	{
		add
		{
			Connect(SignalName.MouseExited, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.MouseExited, Callable.From(value));
		}
	}

	public event Action FocusEntered
	{
		add
		{
			Connect(SignalName.FocusEntered, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.FocusEntered, Callable.From(value));
		}
	}

	public event Action FocusExited
	{
		add
		{
			Connect(SignalName.FocusExited, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.FocusExited, Callable.From(value));
		}
	}

	public event Action CloseRequested
	{
		add
		{
			Connect(SignalName.CloseRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.CloseRequested, Callable.From(value));
		}
	}

	public event Action GoBackRequested
	{
		add
		{
			Connect(SignalName.GoBackRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.GoBackRequested, Callable.From(value));
		}
	}

	public event Action VisibilityChanged
	{
		add
		{
			Connect(SignalName.VisibilityChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.VisibilityChanged, Callable.From(value));
		}
	}

	public event Action AboutToPopup
	{
		add
		{
			Connect(SignalName.AboutToPopup, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.AboutToPopup, Callable.From(value));
		}
	}

	public event Action ThemeChanged
	{
		add
		{
			Connect(SignalName.ThemeChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ThemeChanged, Callable.From(value));
		}
	}

	public event Action DpiChanged
	{
		add
		{
			Connect(SignalName.DpiChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.DpiChanged, Callable.From(value));
		}
	}

	public event Action TitlebarChanged
	{
		add
		{
			Connect(SignalName.TitlebarChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TitlebarChanged, Callable.From(value));
		}
	}

	public event Action TitleChanged
	{
		add
		{
			Connect(SignalName.TitleChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TitleChanged, Callable.From(value));
		}
	}

	public event Action SizeChanged
	{
		add
		{
			Connect(SignalName.SizeChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SizeChanged, Callable.From(value));
		}
	}

	public event Action<Control> GuiFocusChanged
	{
		add
		{
			Connect(SignalName.GuiFocusChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.GuiFocusChanged, Callable.From(value));
		}
	}

	public event Action Ready
	{
		add
		{
			Connect(SignalName.Ready, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Ready, Callable.From(value));
		}
	}

	public event Action Renamed
	{
		add
		{
			Connect(SignalName.Renamed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Renamed, Callable.From(value));
		}
	}

	public event Action TreeEntered
	{
		add
		{
			Connect(SignalName.TreeEntered, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeEntered, Callable.From(value));
		}
	}

	public event Action TreeExiting
	{
		add
		{
			Connect(SignalName.TreeExiting, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeExiting, Callable.From(value));
		}
	}

	public event Action TreeExited
	{
		add
		{
			Connect(SignalName.TreeExited, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.TreeExited, Callable.From(value));
		}
	}

	public event Action<Node> ChildEnteredTree
	{
		add
		{
			Connect(SignalName.ChildEnteredTree, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildEnteredTree, Callable.From(value));
		}
	}

	public event Action<Node> ChildExitingTree
	{
		add
		{
			Connect(SignalName.ChildExitingTree, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildExitingTree, Callable.From(value));
		}
	}

	public event Action ChildOrderChanged
	{
		add
		{
			Connect(SignalName.ChildOrderChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ChildOrderChanged, Callable.From(value));
		}
	}

	public event Action<Node> ReplacingBy
	{
		add
		{
			Connect(SignalName.ReplacingBy, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ReplacingBy, Callable.From(value));
		}
	}

	public event Action<Node> EditorDescriptionChanged
	{
		add
		{
			Connect(SignalName.EditorDescriptionChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.EditorDescriptionChanged, Callable.From(value));
		}
	}

	public event Action EditorStateChanged
	{
		add
		{
			Connect(SignalName.EditorStateChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.EditorStateChanged, Callable.From(value));
		}
	}

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
#endif
























