// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelLodTerrain : VoxelNode
{
	public VoxelLodTerrain() : base(NativeName)
	{
	}
	protected VoxelLodTerrain(StringName @class) : base(@class)
	{
	}
	protected VoxelLodTerrain(Variant variant) : base(variant)
	{
	}
	protected VoxelLodTerrain([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(VoxelLodTerrain self) => self?._object;
	public static implicit operator Variant(VoxelLodTerrain self) => self?._object;
	public static explicit operator VoxelLodTerrain(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : VoxelNode.PropertyName
	{
		public static readonly StringName ViewDistance = "view_distance";
		public static readonly StringName VoxelBounds = "voxel_bounds";
		public static readonly StringName LodCount = "lod_count";
		public static readonly StringName LodDistance = "lod_distance";
		public static readonly StringName SecondaryLodDistance = "secondary_lod_distance";
		public static readonly StringName LodFadeDuration = "lod_fade_duration";
		public static readonly StringName Material = "material";
		public static readonly StringName NormalmapEnabled = "normalmap_enabled";
		public static readonly StringName NormalmapTileResolutionMin = "normalmap_tile_resolution_min";
		public static readonly StringName NormalmapTileResolutionMax = "normalmap_tile_resolution_max";
		public static readonly StringName NormalmapBeginLodIndex = "normalmap_begin_lod_index";
		public static readonly StringName NormalmapMaxDeviationDegrees = "normalmap_max_deviation_degrees";
		public static readonly StringName NormalmapOctahedralEncodingEnabled = "normalmap_octahedral_encoding_enabled";
		public static readonly StringName NormalmapUseGpu = "normalmap_use_gpu";
		public static readonly StringName GenerateCollisions = "generate_collisions";
		public static readonly StringName CollisionLayer = "collision_layer";
		public static readonly StringName CollisionMask = "collision_mask";
		public static readonly StringName CollisionLodCount = "collision_lod_count";
		public static readonly StringName CollisionUpdateDelay = "collision_update_delay";
		public static readonly StringName CollisionMargin = "collision_margin";
		public static readonly StringName RunStreamInEditor = "run_stream_in_editor";
		public static readonly StringName MeshBlockSize = "mesh_block_size";
		public static readonly StringName FullLoadModeEnabled = "full_load_mode_enabled";
		public static readonly StringName CacheGeneratedBlocks = "cache_generated_blocks";
		public static readonly StringName ThreadedUpdateEnabled = "threaded_update_enabled";
		public static readonly StringName UseGpuGeneration = "use_gpu_generation";
		public static readonly StringName StreamingSystem = "streaming_system";
		public static readonly StringName DebugDrawEnabled = "debug_draw_enabled";
		public static readonly StringName DebugDrawOctreeNodes = "debug_draw_octree_nodes";
		public static readonly StringName DebugDrawOctreeBounds = "debug_draw_octree_bounds";
		public static readonly StringName DebugDrawMeshUpdates = "debug_draw_mesh_updates";
		public static readonly StringName DebugDrawEditBoxes = "debug_draw_edit_boxes";
		public static readonly StringName DebugDrawVolumeBounds = "debug_draw_volume_bounds";
		public static readonly StringName DebugDrawEditedBlocks = "debug_draw_edited_blocks";
		public static readonly StringName DebugDrawModifierBounds = "debug_draw_modifier_bounds";
		public static readonly StringName DebugDrawActiveMeshBlocks = "debug_draw_active_mesh_blocks";
		public static readonly StringName DebugDrawViewerClipboxes = "debug_draw_viewer_clipboxes";
		public static readonly StringName DebugDrawLoadedVisualAndCollisionBlocks = "debug_draw_loaded_visual_and_collision_blocks";
		public static readonly StringName DebugDrawActiveVisualAndCollisionBlocks = "debug_draw_active_visual_and_collision_blocks";
		public static readonly StringName DebugDrawVoxelMetadata = "debug_draw_voxel_metadata";
		public static readonly StringName DebugDrawShadowOccluders = "debug_draw_shadow_occluders";
	}

	public new class MethodName : VoxelNode.MethodName
	{
		public static readonly StringName SetMaterial = "set_material";
		public static readonly StringName GetMaterial = "get_material";
		public static readonly StringName SetViewDistance = "set_view_distance";
		public static readonly StringName GetViewDistance = "get_view_distance";
		public static readonly StringName SetVoxelBounds = "set_voxel_bounds";
		public static readonly StringName GetVoxelBounds = "get_voxel_bounds";
		public static readonly StringName GetGenerateCollisions = "get_generate_collisions";
		public static readonly StringName SetGenerateCollisions = "set_generate_collisions";
		public static readonly StringName GetCollisionLodCount = "get_collision_lod_count";
		public static readonly StringName SetCollisionLodCount = "set_collision_lod_count";
		public static readonly StringName GetCollisionLayer = "get_collision_layer";
		public static readonly StringName SetCollisionLayer = "set_collision_layer";
		public static readonly StringName GetCollisionMask = "get_collision_mask";
		public static readonly StringName SetCollisionMask = "set_collision_mask";
		public static readonly StringName GetCollisionMargin = "get_collision_margin";
		public static readonly StringName SetCollisionMargin = "set_collision_margin";
		public static readonly StringName GetCollisionUpdateDelay = "get_collision_update_delay";
		public static readonly StringName SetCollisionUpdateDelay = "set_collision_update_delay";
		public static readonly StringName GetLodFadeDuration = "get_lod_fade_duration";
		public static readonly StringName SetLodFadeDuration = "set_lod_fade_duration";
		public static readonly StringName SetLodCount = "set_lod_count";
		public static readonly StringName GetLodCount = "get_lod_count";
		public static readonly StringName SetLodDistance = "set_lod_distance";
		public static readonly StringName GetLodDistance = "get_lod_distance";
		public static readonly StringName SetSecondaryLodDistance = "set_secondary_lod_distance";
		public static readonly StringName GetSecondaryLodDistance = "get_secondary_lod_distance";
		public static readonly StringName VoxelToDataBlockPosition = "voxel_to_data_block_position";
		public static readonly StringName VoxelToMeshBlockPosition = "voxel_to_mesh_block_position";
		public static readonly StringName GetVoxelTool = "get_voxel_tool";
		public static readonly StringName SaveModifiedBlocks = "save_modified_blocks";
		public static readonly StringName SetRunStreamInEditor = "set_run_stream_in_editor";
		public static readonly StringName IsStreamRunningInEditor = "is_stream_running_in_editor";
		public static readonly StringName IsAreaMeshed = "is_area_meshed";
		public static readonly StringName SetNormalmapEnabled = "set_normalmap_enabled";
		public static readonly StringName IsNormalmapEnabled = "is_normalmap_enabled";
		public static readonly StringName SetNormalmapTileResolutionMin = "set_normalmap_tile_resolution_min";
		public static readonly StringName GetNormalmapTileResolutionMin = "get_normalmap_tile_resolution_min";
		public static readonly StringName SetNormalmapTileResolutionMax = "set_normalmap_tile_resolution_max";
		public static readonly StringName GetNormalmapTileResolutionMax = "get_normalmap_tile_resolution_max";
		public static readonly StringName SetNormalmapBeginLodIndex = "set_normalmap_begin_lod_index";
		public static readonly StringName GetNormalmapBeginLodIndex = "get_normalmap_begin_lod_index";
		public static readonly StringName SetNormalmapMaxDeviationDegrees = "set_normalmap_max_deviation_degrees";
		public static readonly StringName GetNormalmapMaxDeviationDegrees = "get_normalmap_max_deviation_degrees";
		public static readonly StringName SetOctahedralNormalEncoding = "set_octahedral_normal_encoding";
		public static readonly StringName GetOctahedralNormalEncoding = "get_octahedral_normal_encoding";
		public static readonly StringName SetNormalmapGeneratorOverride = "set_normalmap_generator_override";
		public static readonly StringName GetNormalmapGeneratorOverride = "get_normalmap_generator_override";
		public static readonly StringName SetNormalmapGeneratorOverrideBeginLodIndex = "set_normalmap_generator_override_begin_lod_index";
		public static readonly StringName GetNormalmapGeneratorOverrideBeginLodIndex = "get_normalmap_generator_override_begin_lod_index";
		public static readonly StringName SetNormalmapUseGpu = "set_normalmap_use_gpu";
		public static readonly StringName GetNormalmapUseGpu = "get_normalmap_use_gpu";
		public static readonly StringName GetMeshBlockSize = "get_mesh_block_size";
		public static readonly StringName SetMeshBlockSize = "set_mesh_block_size";
		public static readonly StringName GetDataBlockSize = "get_data_block_size";
		public static readonly StringName GetDataBlockRegionExtent = "get_data_block_region_extent";
		public static readonly StringName SetFullLoadModeEnabled = "set_full_load_mode_enabled";
		public static readonly StringName IsFullLoadModeEnabled = "is_full_load_mode_enabled";
		public static readonly StringName SetThreadedUpdateEnabled = "set_threaded_update_enabled";
		public static readonly StringName IsThreadedUpdateEnabled = "is_threaded_update_enabled";
		public static readonly StringName SetProcessCallback = "set_process_callback";
		public static readonly StringName GetProcessCallback = "get_process_callback";
		public static readonly StringName SetGeneratorUseGpu = "set_generator_use_gpu";
		public static readonly StringName GetGeneratorUseGpu = "get_generator_use_gpu";
		public static readonly StringName SetStreamingSystem = "set_streaming_system";
		public static readonly StringName GetStreamingSystem = "get_streaming_system";
		public static readonly StringName SetCacheGeneratedBlocks = "set_cache_generated_blocks";
		public static readonly StringName GetCacheGeneratedBlocks = "get_cache_generated_blocks";
		public static readonly StringName GetStatistics = "get_statistics";
		public static readonly StringName DebugRaycastMeshBlock = "debug_raycast_mesh_block";
		public static readonly StringName DebugGetDataBlockInfo = "debug_get_data_block_info";
		public static readonly StringName DebugGetMeshBlockInfo = "debug_get_mesh_block_info";
		public static readonly StringName DebugGetOctreesDetailed = "debug_get_octrees_detailed";
		public static readonly StringName DebugPrintSdfTopDown = "debug_print_sdf_top_down";
		public static readonly StringName DebugGetMeshBlockCount = "debug_get_mesh_block_count";
		public static readonly StringName DebugGetDataBlockCount = "debug_get_data_block_count";
		public static readonly StringName DebugDumpAsScene = "debug_dump_as_scene";
		public static readonly StringName DebugIsDrawEnabled = "debug_is_draw_enabled";
		public static readonly StringName DebugSetDrawEnabled = "debug_set_draw_enabled";
		public static readonly StringName DebugSetDrawFlag = "debug_set_draw_flag";
		public static readonly StringName DebugGetDrawFlag = "debug_get_draw_flag";
		public static readonly StringName DebugSetDrawShadowOccluders = "debug_set_draw_shadow_occluders";
		public static readonly StringName DebugGetDrawShadowOccluders = "debug_get_draw_shadow_occluders";
	}

	public new class SignalName : VoxelNode.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelLodTerrain";

	#region Enums

	public enum ProcessCallback : long
	{
		Idle = 0L,
		Physics = 1L,
		Disabled = 2L,
	}

	public enum DebugDrawFlag : long
	{
		OctreeNodes = 0L,
		OctreeBounds = 1L,
		MeshUpdates = 2L,
		EditBoxes = 3L,
		VolumeBounds = 4L,
		EditedBlocks = 5L,
		ModifierBounds = 6L,
		ActiveMeshBlocks = 7L,
		ViewerClipboxes = 8L,
		LoadedVisualAndCollisionBlocks = 9L,
		ActiveVisualAndCollisionBlocks = 10L,
		FlagsCount = 12L,
	}

	public enum StreamingSystemEnum : long
	{
		LegacyOctree = 0L,
		Clipbox = 1L,
	}

	#endregion

	#region Properties

	public int ViewDistance
	{
		get => (int)_object.Get(PropertyName.ViewDistance);
		set => _object.Set(PropertyName.ViewDistance, value);
	}

	public Godot.Aabb VoxelBounds
	{
		get => (Godot.Aabb)_object.Get(PropertyName.VoxelBounds);
		set => _object.Set(PropertyName.VoxelBounds, value);
	}

	public int LodCount
	{
		get => (int)_object.Get(PropertyName.LodCount);
		set => _object.Set(PropertyName.LodCount, value);
	}

	public float LodDistance
	{
		get => (float)_object.Get(PropertyName.LodDistance);
		set => _object.Set(PropertyName.LodDistance, value);
	}

	public float SecondaryLodDistance
	{
		get => (float)_object.Get(PropertyName.SecondaryLodDistance);
		set => _object.Set(PropertyName.SecondaryLodDistance, value);
	}

	public float LodFadeDuration
	{
		get => (float)_object.Get(PropertyName.LodFadeDuration);
		set => _object.Set(PropertyName.LodFadeDuration, value);
	}

	public Material Material
	{
		get => (Material)_object.Get(PropertyName.Material);
		set => _object.Set(PropertyName.Material, value);
	}

	public bool NormalmapEnabled
	{
		get => (bool)_object.Get(PropertyName.NormalmapEnabled);
		set => _object.Set(PropertyName.NormalmapEnabled, value);
	}

	public int NormalmapTileResolutionMin
	{
		get => (int)_object.Get(PropertyName.NormalmapTileResolutionMin);
		set => _object.Set(PropertyName.NormalmapTileResolutionMin, value);
	}

	public int NormalmapTileResolutionMax
	{
		get => (int)_object.Get(PropertyName.NormalmapTileResolutionMax);
		set => _object.Set(PropertyName.NormalmapTileResolutionMax, value);
	}

	public int NormalmapBeginLodIndex
	{
		get => (int)_object.Get(PropertyName.NormalmapBeginLodIndex);
		set => _object.Set(PropertyName.NormalmapBeginLodIndex, value);
	}

	public int NormalmapMaxDeviationDegrees
	{
		get => (int)_object.Get(PropertyName.NormalmapMaxDeviationDegrees);
		set => _object.Set(PropertyName.NormalmapMaxDeviationDegrees, value);
	}

	public bool NormalmapOctahedralEncodingEnabled
	{
		get => (bool)_object.Get(PropertyName.NormalmapOctahedralEncodingEnabled);
		set => _object.Set(PropertyName.NormalmapOctahedralEncodingEnabled, value);
	}

	public bool NormalmapUseGpu
	{
		get => (bool)_object.Get(PropertyName.NormalmapUseGpu);
		set => _object.Set(PropertyName.NormalmapUseGpu, value);
	}

	public bool GenerateCollisions
	{
		get => (bool)_object.Get(PropertyName.GenerateCollisions);
		set => _object.Set(PropertyName.GenerateCollisions, value);
	}

	public int CollisionLayer
	{
		get => (int)_object.Get(PropertyName.CollisionLayer);
		set => _object.Set(PropertyName.CollisionLayer, value);
	}

	public int CollisionMask
	{
		get => (int)_object.Get(PropertyName.CollisionMask);
		set => _object.Set(PropertyName.CollisionMask, value);
	}

	public int CollisionLodCount
	{
		get => (int)_object.Get(PropertyName.CollisionLodCount);
		set => _object.Set(PropertyName.CollisionLodCount, value);
	}

	public int CollisionUpdateDelay
	{
		get => (int)_object.Get(PropertyName.CollisionUpdateDelay);
		set => _object.Set(PropertyName.CollisionUpdateDelay, value);
	}

	public float CollisionMargin
	{
		get => (float)_object.Get(PropertyName.CollisionMargin);
		set => _object.Set(PropertyName.CollisionMargin, value);
	}

	public bool RunStreamInEditor
	{
		get => (bool)_object.Get(PropertyName.RunStreamInEditor);
		set => _object.Set(PropertyName.RunStreamInEditor, value);
	}

	public int MeshBlockSize
	{
		get => (int)_object.Get(PropertyName.MeshBlockSize);
		set => _object.Set(PropertyName.MeshBlockSize, value);
	}

	public bool FullLoadModeEnabled
	{
		get => (bool)_object.Get(PropertyName.FullLoadModeEnabled);
		set => _object.Set(PropertyName.FullLoadModeEnabled, value);
	}

	public bool CacheGeneratedBlocks
	{
		get => (bool)_object.Get(PropertyName.CacheGeneratedBlocks);
		set => _object.Set(PropertyName.CacheGeneratedBlocks, value);
	}

	public bool ThreadedUpdateEnabled
	{
		get => (bool)_object.Get(PropertyName.ThreadedUpdateEnabled);
		set => _object.Set(PropertyName.ThreadedUpdateEnabled, value);
	}

	public bool UseGpuGeneration
	{
		get => (bool)_object.Get(PropertyName.UseGpuGeneration);
		set => _object.Set(PropertyName.UseGpuGeneration, value);
	}

	public int StreamingSystem
	{
		get => (int)_object.Get(PropertyName.StreamingSystem);
		set => _object.Set(PropertyName.StreamingSystem, value);
	}

	public bool DebugDrawEnabled
	{
		get => (bool)_object.Get(PropertyName.DebugDrawEnabled);
		set => _object.Set(PropertyName.DebugDrawEnabled, value);
	}

	public bool DebugDrawOctreeNodes
	{
		get => (bool)_object.Get(PropertyName.DebugDrawOctreeNodes);
		set => _object.Set(PropertyName.DebugDrawOctreeNodes, value);
	}

	public bool DebugDrawOctreeBounds
	{
		get => (bool)_object.Get(PropertyName.DebugDrawOctreeBounds);
		set => _object.Set(PropertyName.DebugDrawOctreeBounds, value);
	}

	public bool DebugDrawMeshUpdates
	{
		get => (bool)_object.Get(PropertyName.DebugDrawMeshUpdates);
		set => _object.Set(PropertyName.DebugDrawMeshUpdates, value);
	}

	public bool DebugDrawEditBoxes
	{
		get => (bool)_object.Get(PropertyName.DebugDrawEditBoxes);
		set => _object.Set(PropertyName.DebugDrawEditBoxes, value);
	}

	public bool DebugDrawVolumeBounds
	{
		get => (bool)_object.Get(PropertyName.DebugDrawVolumeBounds);
		set => _object.Set(PropertyName.DebugDrawVolumeBounds, value);
	}

	public bool DebugDrawEditedBlocks
	{
		get => (bool)_object.Get(PropertyName.DebugDrawEditedBlocks);
		set => _object.Set(PropertyName.DebugDrawEditedBlocks, value);
	}

	public bool DebugDrawModifierBounds
	{
		get => (bool)_object.Get(PropertyName.DebugDrawModifierBounds);
		set => _object.Set(PropertyName.DebugDrawModifierBounds, value);
	}

	public bool DebugDrawActiveMeshBlocks
	{
		get => (bool)_object.Get(PropertyName.DebugDrawActiveMeshBlocks);
		set => _object.Set(PropertyName.DebugDrawActiveMeshBlocks, value);
	}

	public bool DebugDrawViewerClipboxes
	{
		get => (bool)_object.Get(PropertyName.DebugDrawViewerClipboxes);
		set => _object.Set(PropertyName.DebugDrawViewerClipboxes, value);
	}

	public bool DebugDrawLoadedVisualAndCollisionBlocks
	{
		get => (bool)_object.Get(PropertyName.DebugDrawLoadedVisualAndCollisionBlocks);
		set => _object.Set(PropertyName.DebugDrawLoadedVisualAndCollisionBlocks, value);
	}

	public bool DebugDrawActiveVisualAndCollisionBlocks
	{
		get => (bool)_object.Get(PropertyName.DebugDrawActiveVisualAndCollisionBlocks);
		set => _object.Set(PropertyName.DebugDrawActiveVisualAndCollisionBlocks, value);
	}

	public bool DebugDrawVoxelMetadata
	{
		get => (bool)_object.Get(PropertyName.DebugDrawVoxelMetadata);
		set => _object.Set(PropertyName.DebugDrawVoxelMetadata, value);
	}

	public bool DebugDrawShadowOccluders
	{
		get => (bool)_object.Get(PropertyName.DebugDrawShadowOccluders);
		set => _object.Set(PropertyName.DebugDrawShadowOccluders, value);
	}

	#endregion

	#region Methods

	public void SetMaterial(Material @material)
	{
		_object.Call(MethodName.SetMaterial, @material);
	}

	public Material GetMaterial()
	{
		return (Material)_object.Call(MethodName.GetMaterial);
	}

	public void SetViewDistance(int @distance_in_voxels)
	{
		_object.Call(MethodName.SetViewDistance, @distance_in_voxels);
	}

	public int GetViewDistance()
	{
		return (int)_object.Call(MethodName.GetViewDistance);
	}

	public void SetVoxelBounds(Godot.Aabb @_unnamed_arg0)
	{
		_object.Call(MethodName.SetVoxelBounds, @_unnamed_arg0);
	}

	public Godot.Aabb GetVoxelBounds()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetVoxelBounds);
	}

	public bool GetGenerateCollisions()
	{
		return (bool)_object.Call(MethodName.GetGenerateCollisions);
	}

	public void SetGenerateCollisions(bool @enabled)
	{
		_object.Call(MethodName.SetGenerateCollisions, @enabled);
	}

	public int GetCollisionLodCount()
	{
		return (int)_object.Call(MethodName.GetCollisionLodCount);
	}

	public void SetCollisionLodCount(int @count)
	{
		_object.Call(MethodName.SetCollisionLodCount, @count);
	}

	public int GetCollisionLayer()
	{
		return (int)_object.Call(MethodName.GetCollisionLayer);
	}

	public void SetCollisionLayer(int @layer)
	{
		_object.Call(MethodName.SetCollisionLayer, @layer);
	}

	public int GetCollisionMask()
	{
		return (int)_object.Call(MethodName.GetCollisionMask);
	}

	public void SetCollisionMask(int @mask)
	{
		_object.Call(MethodName.SetCollisionMask, @mask);
	}

	public float GetCollisionMargin()
	{
		return (float)_object.Call(MethodName.GetCollisionMargin);
	}

	public void SetCollisionMargin(float @margin)
	{
		_object.Call(MethodName.SetCollisionMargin, @margin);
	}

	public int GetCollisionUpdateDelay()
	{
		return (int)_object.Call(MethodName.GetCollisionUpdateDelay);
	}

	public void SetCollisionUpdateDelay(int @delay_msec)
	{
		_object.Call(MethodName.SetCollisionUpdateDelay, @delay_msec);
	}

	public float GetLodFadeDuration()
	{
		return (float)_object.Call(MethodName.GetLodFadeDuration);
	}

	public void SetLodFadeDuration(float @seconds)
	{
		_object.Call(MethodName.SetLodFadeDuration, @seconds);
	}

	public void SetLodCount(int @lod_count)
	{
		_object.Call(MethodName.SetLodCount, @lod_count);
	}

	public int GetLodCount()
	{
		return (int)_object.Call(MethodName.GetLodCount);
	}

	public void SetLodDistance(float @lod_distance)
	{
		_object.Call(MethodName.SetLodDistance, @lod_distance);
	}

	public float GetLodDistance()
	{
		return (float)_object.Call(MethodName.GetLodDistance);
	}

	public void SetSecondaryLodDistance(float @lod_distance)
	{
		_object.Call(MethodName.SetSecondaryLodDistance, @lod_distance);
	}

	public float GetSecondaryLodDistance()
	{
		return (float)_object.Call(MethodName.GetSecondaryLodDistance);
	}

	public Godot.Vector3I VoxelToDataBlockPosition(Godot.Vector3 @voxel_position, int @lod_index)
	{
		return (Godot.Vector3I)_object.Call(MethodName.VoxelToDataBlockPosition, @voxel_position, @lod_index);
	}

	public Godot.Vector3I VoxelToMeshBlockPosition(Godot.Vector3 @voxel_position, int @lod_index)
	{
		return (Godot.Vector3I)_object.Call(MethodName.VoxelToMeshBlockPosition, @voxel_position, @lod_index);
	}

	public VoxelTool GetVoxelTool()
	{
		return (VoxelTool)_object.Call(MethodName.GetVoxelTool);
	}

	public VoxelSaveCompletionTracker SaveModifiedBlocks()
	{
		return (VoxelSaveCompletionTracker)_object.Call(MethodName.SaveModifiedBlocks);
	}

	public void SetRunStreamInEditor(bool @_unnamed_arg0)
	{
		_object.Call(MethodName.SetRunStreamInEditor, @_unnamed_arg0);
	}

	public bool IsStreamRunningInEditor()
	{
		return (bool)_object.Call(MethodName.IsStreamRunningInEditor);
	}

	public bool IsAreaMeshed(Godot.Aabb @area_in_voxels, int @lod_index)
	{
		return (bool)_object.Call(MethodName.IsAreaMeshed, @area_in_voxels, @lod_index);
	}

	public void SetNormalmapEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetNormalmapEnabled, @enabled);
	}

	public bool IsNormalmapEnabled()
	{
		return (bool)_object.Call(MethodName.IsNormalmapEnabled);
	}

	public void SetNormalmapTileResolutionMin(int @resolution)
	{
		_object.Call(MethodName.SetNormalmapTileResolutionMin, @resolution);
	}

	public int GetNormalmapTileResolutionMin()
	{
		return (int)_object.Call(MethodName.GetNormalmapTileResolutionMin);
	}

	public void SetNormalmapTileResolutionMax(int @resolution)
	{
		_object.Call(MethodName.SetNormalmapTileResolutionMax, @resolution);
	}

	public int GetNormalmapTileResolutionMax()
	{
		return (int)_object.Call(MethodName.GetNormalmapTileResolutionMax);
	}

	public void SetNormalmapBeginLodIndex(int @lod_index)
	{
		_object.Call(MethodName.SetNormalmapBeginLodIndex, @lod_index);
	}

	public int GetNormalmapBeginLodIndex()
	{
		return (int)_object.Call(MethodName.GetNormalmapBeginLodIndex);
	}

	public void SetNormalmapMaxDeviationDegrees(int @angle)
	{
		_object.Call(MethodName.SetNormalmapMaxDeviationDegrees, @angle);
	}

	public int GetNormalmapMaxDeviationDegrees()
	{
		return (int)_object.Call(MethodName.GetNormalmapMaxDeviationDegrees);
	}

	public void SetOctahedralNormalEncoding(bool @enabled)
	{
		_object.Call(MethodName.SetOctahedralNormalEncoding, @enabled);
	}

	public bool GetOctahedralNormalEncoding()
	{
		return (bool)_object.Call(MethodName.GetOctahedralNormalEncoding);
	}

	public void SetNormalmapGeneratorOverride(VoxelGenerator @generator_override)
	{
		_object.Call(MethodName.SetNormalmapGeneratorOverride, @generator_override);
	}

	public VoxelGenerator GetNormalmapGeneratorOverride()
	{
		return (VoxelGenerator)_object.Call(MethodName.GetNormalmapGeneratorOverride);
	}

	public void SetNormalmapGeneratorOverrideBeginLodIndex(int @lod_index)
	{
		_object.Call(MethodName.SetNormalmapGeneratorOverrideBeginLodIndex, @lod_index);
	}

	public int GetNormalmapGeneratorOverrideBeginLodIndex()
	{
		return (int)_object.Call(MethodName.GetNormalmapGeneratorOverrideBeginLodIndex);
	}

	public void SetNormalmapUseGpu(bool @enabled)
	{
		_object.Call(MethodName.SetNormalmapUseGpu, @enabled);
	}

	public bool GetNormalmapUseGpu()
	{
		return (bool)_object.Call(MethodName.GetNormalmapUseGpu);
	}

	public int GetMeshBlockSize()
	{
		return (int)_object.Call(MethodName.GetMeshBlockSize);
	}

	public void SetMeshBlockSize(int @_unnamed_arg0)
	{
		_object.Call(MethodName.SetMeshBlockSize, @_unnamed_arg0);
	}

	public int GetDataBlockSize()
	{
		return (int)_object.Call(MethodName.GetDataBlockSize);
	}

	public int GetDataBlockRegionExtent()
	{
		return (int)_object.Call(MethodName.GetDataBlockRegionExtent);
	}

	public void SetFullLoadModeEnabled(bool @_unnamed_arg0)
	{
		_object.Call(MethodName.SetFullLoadModeEnabled, @_unnamed_arg0);
	}

	public bool IsFullLoadModeEnabled()
	{
		return (bool)_object.Call(MethodName.IsFullLoadModeEnabled);
	}

	public void SetThreadedUpdateEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetThreadedUpdateEnabled, @enabled);
	}

	public bool IsThreadedUpdateEnabled()
	{
		return (bool)_object.Call(MethodName.IsThreadedUpdateEnabled);
	}

	public void SetProcessCallback(VoxelLodTerrain.ProcessCallback @mode)
	{
		_object.Call(MethodName.SetProcessCallback, (int)@mode);
	}

	public VoxelLodTerrain.ProcessCallback GetProcessCallback()
	{
		return (VoxelLodTerrain.ProcessCallback)(int)_object.Call(MethodName.GetProcessCallback);
	}

	public void SetGeneratorUseGpu(bool @enabled)
	{
		_object.Call(MethodName.SetGeneratorUseGpu, @enabled);
	}

	public bool GetGeneratorUseGpu()
	{
		return (bool)_object.Call(MethodName.GetGeneratorUseGpu);
	}

	public void SetStreamingSystem(VoxelLodTerrain.StreamingSystemEnum @system)
	{
		_object.Call(MethodName.SetStreamingSystem, (int)@system);
	}

	public VoxelLodTerrain.StreamingSystemEnum GetStreamingSystem()
	{
		return (VoxelLodTerrain.StreamingSystemEnum)(int)_object.Call(MethodName.GetStreamingSystem);
	}

	public void SetCacheGeneratedBlocks(bool @enabled)
	{
		_object.Call(MethodName.SetCacheGeneratedBlocks, @enabled);
	}

	public bool GetCacheGeneratedBlocks()
	{
		return (bool)_object.Call(MethodName.GetCacheGeneratedBlocks);
	}

	public Godot.Collections.Dictionary GetStatistics()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetStatistics);
	}

	public Godot.Collections.Array DebugRaycastMeshBlock(Godot.Vector3 @origin, Godot.Vector3 @dir)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.DebugRaycastMeshBlock, @origin, @dir);
	}

	public Godot.Collections.Dictionary DebugGetDataBlockInfo(Godot.Vector3 @block_pos, int @lod)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.DebugGetDataBlockInfo, @block_pos, @lod);
	}

	public Godot.Collections.Dictionary DebugGetMeshBlockInfo(Godot.Vector3 @block_pos, int @lod)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.DebugGetMeshBlockInfo, @block_pos, @lod);
	}

	public Godot.Collections.Array DebugGetOctreesDetailed()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.DebugGetOctreesDetailed);
	}

	public Godot.Collections.Array DebugPrintSdfTopDown(Godot.Vector3I @center, Godot.Vector3I @extents)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.DebugPrintSdfTopDown, @center, @extents);
	}

	public int DebugGetMeshBlockCount()
	{
		return (int)_object.Call(MethodName.DebugGetMeshBlockCount);
	}

	public int DebugGetDataBlockCount()
	{
		return (int)_object.Call(MethodName.DebugGetDataBlockCount);
	}

	public int DebugDumpAsScene(string @path, bool @include_instancer)
	{
		return (int)_object.Call(MethodName.DebugDumpAsScene, @path, @include_instancer);
	}

	public bool DebugIsDrawEnabled()
	{
		return (bool)_object.Call(MethodName.DebugIsDrawEnabled);
	}

	public void DebugSetDrawEnabled(bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawEnabled, @enabled);
	}

	public void DebugSetDrawFlag(VoxelLodTerrain.DebugDrawFlag @flag_index, bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawFlag, (int)@flag_index, @enabled);
	}

	public bool DebugGetDrawFlag(VoxelLodTerrain.DebugDrawFlag @flag_index)
	{
		return (bool)_object.Call(MethodName.DebugGetDrawFlag, (int)@flag_index);
	}

	public void DebugSetDrawShadowOccluders(bool @enabled)
	{
		_object.Call(MethodName.DebugSetDrawShadowOccluders, @enabled);
	}

	public bool DebugGetDrawShadowOccluders()
	{
		return (bool)_object.Call(MethodName.DebugGetDrawShadowOccluders);
	}

	#endregion
}
























