// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelTool
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public VoxelTool() : this(NativeName)
	{
	}
	protected VoxelTool(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected VoxelTool(Variant variant) : this((RefCounted) variant)
	{
	}
	protected VoxelTool([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(VoxelTool self) => self?._object;
	public static implicit operator Variant(VoxelTool self) => self?._object;
	public static explicit operator VoxelTool(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Value = "value";
		public static readonly StringName Channel = "channel";
		public static readonly StringName EraserValue = "eraser_value";
		public static readonly StringName Mode = "mode";
		public static readonly StringName SdfScale = "sdf_scale";
		public static readonly StringName SdfStrength = "sdf_strength";
		public static readonly StringName TextureIndex = "texture_index";
		public static readonly StringName TextureOpacity = "texture_opacity";
		public static readonly StringName TextureFalloff = "texture_falloff";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName SetValue = "set_value";
		public static readonly StringName GetValue = "get_value";
		public static readonly StringName SetChannel = "set_channel";
		public static readonly StringName GetChannel = "get_channel";
		public static readonly StringName SetMode = "set_mode";
		public static readonly StringName GetMode = "get_mode";
		public static readonly StringName SetEraserValue = "set_eraser_value";
		public static readonly StringName GetEraserValue = "get_eraser_value";
		public static readonly StringName SetSdfScale = "set_sdf_scale";
		public static readonly StringName GetSdfScale = "get_sdf_scale";
		public static readonly StringName SetSdfStrength = "set_sdf_strength";
		public static readonly StringName GetSdfStrength = "get_sdf_strength";
		public static readonly StringName SetTextureIndex = "set_texture_index";
		public static readonly StringName GetTextureIndex = "get_texture_index";
		public static readonly StringName SetTextureOpacity = "set_texture_opacity";
		public static readonly StringName GetTextureOpacity = "get_texture_opacity";
		public static readonly StringName SetTextureFalloff = "set_texture_falloff";
		public static readonly StringName GetTextureFalloff = "get_texture_falloff";
		public static readonly StringName GetVoxel = "get_voxel";
		public static readonly StringName GetVoxelF = "get_voxel_f";
		public static readonly StringName SetVoxel = "set_voxel";
		public static readonly StringName SetVoxelF = "set_voxel_f";
		public static readonly StringName DoPoint = "do_point";
		public static readonly StringName DoSphere = "do_sphere";
		public static readonly StringName DoBox = "do_box";
		public static readonly StringName DoPath = "do_path";
		public static readonly StringName DoMesh = "do_mesh";
		public static readonly StringName SmoothSphere = "smooth_sphere";
		public static readonly StringName GrowSphere = "grow_sphere";
		public static readonly StringName SetVoxelMetadata = "set_voxel_metadata";
		public static readonly StringName GetVoxelMetadata = "get_voxel_metadata";
		public static readonly StringName Copy = "copy";
		public static readonly StringName Paste = "paste";
		public static readonly StringName PasteMasked = "paste_masked";
		public static readonly StringName PasteMaskedWritableList = "paste_masked_writable_list";
		public static readonly StringName Raycast = "raycast";
		public static readonly StringName SetRaycastNormalEnabled = "set_raycast_normal_enabled";
		public static readonly StringName IsAreaEditable = "is_area_editable";
		public static readonly StringName ColorToU16 = "color_to_u16";
		public static readonly StringName ColorToU32 = "color_to_u32";
		public static readonly StringName Vec4iToU16Indices = "vec4i_to_u16_indices";
		public static readonly StringName ColorToU16Weights = "color_to_u16_weights";
		public static readonly StringName U16IndicesToVec4i = "u16_indices_to_vec4i";
		public static readonly StringName U16WeightsToColor = "u16_weights_to_color";
		public static readonly StringName NormalizeColor = "normalize_color";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelTool";

	#region Enums

	public enum ModeEnum : long
	{
		Add = 0L,
		Remove = 1L,
		Set = 2L,
		TexturePaint = 3L,
	}

	#endregion

	#region Properties

	public int Value
	{
		get => (int)_object.Get(PropertyName.Value);
		set => _object.Set(PropertyName.Value, value);
	}

	public int Channel
	{
		get => (int)_object.Get(PropertyName.Channel);
		set => _object.Set(PropertyName.Channel, value);
	}

	public int EraserValue
	{
		get => (int)_object.Get(PropertyName.EraserValue);
		set => _object.Set(PropertyName.EraserValue, value);
	}

	public int Mode
	{
		get => (int)_object.Get(PropertyName.Mode);
		set => _object.Set(PropertyName.Mode, value);
	}

	public float SdfScale
	{
		get => (float)_object.Get(PropertyName.SdfScale);
		set => _object.Set(PropertyName.SdfScale, value);
	}

	public float SdfStrength
	{
		get => (float)_object.Get(PropertyName.SdfStrength);
		set => _object.Set(PropertyName.SdfStrength, value);
	}

	public int TextureIndex
	{
		get => (int)_object.Get(PropertyName.TextureIndex);
		set => _object.Set(PropertyName.TextureIndex, value);
	}

	public float TextureOpacity
	{
		get => (float)_object.Get(PropertyName.TextureOpacity);
		set => _object.Set(PropertyName.TextureOpacity, value);
	}

	public float TextureFalloff
	{
		get => (float)_object.Get(PropertyName.TextureFalloff);
		set => _object.Set(PropertyName.TextureFalloff, value);
	}

	#endregion

	#region Methods

	public void SetValue(int @v)
	{
		_object.Call(MethodName.SetValue, @v);
	}

	public int GetValue()
	{
		return (int)_object.Call(MethodName.GetValue);
	}

	public void SetChannel(VoxelBuffer.ChannelId @v)
	{
		_object.Call(MethodName.SetChannel, (int)@v);
	}

	public VoxelBuffer.ChannelId GetChannel()
	{
		return (VoxelBuffer.ChannelId)(int)_object.Call(MethodName.GetChannel);
	}

	public void SetMode(VoxelTool.ModeEnum @m)
	{
		_object.Call(MethodName.SetMode, (int)@m);
	}

	public VoxelTool.ModeEnum GetMode()
	{
		return (VoxelTool.ModeEnum)(int)_object.Call(MethodName.GetMode);
	}

	public void SetEraserValue(int @v)
	{
		_object.Call(MethodName.SetEraserValue, @v);
	}

	public int GetEraserValue()
	{
		return (int)_object.Call(MethodName.GetEraserValue);
	}

	public void SetSdfScale(float @scale)
	{
		_object.Call(MethodName.SetSdfScale, @scale);
	}

	public float GetSdfScale()
	{
		return (float)_object.Call(MethodName.GetSdfScale);
	}

	public void SetSdfStrength(float @strength)
	{
		_object.Call(MethodName.SetSdfStrength, @strength);
	}

	public float GetSdfStrength()
	{
		return (float)_object.Call(MethodName.GetSdfStrength);
	}

	public void SetTextureIndex(int @index)
	{
		_object.Call(MethodName.SetTextureIndex, @index);
	}

	public int GetTextureIndex()
	{
		return (int)_object.Call(MethodName.GetTextureIndex);
	}

	public void SetTextureOpacity(float @opacity)
	{
		_object.Call(MethodName.SetTextureOpacity, @opacity);
	}

	public float GetTextureOpacity()
	{
		return (float)_object.Call(MethodName.GetTextureOpacity);
	}

	public void SetTextureFalloff(float @falloff)
	{
		_object.Call(MethodName.SetTextureFalloff, @falloff);
	}

	public float GetTextureFalloff()
	{
		return (float)_object.Call(MethodName.GetTextureFalloff);
	}

	public int GetVoxel(Godot.Vector3I @pos)
	{
		return (int)_object.Call(MethodName.GetVoxel, @pos);
	}

	public float GetVoxelF(Godot.Vector3I @pos)
	{
		return (float)_object.Call(MethodName.GetVoxelF, @pos);
	}

	public void SetVoxel(Godot.Vector3I @pos, int @v)
	{
		_object.Call(MethodName.SetVoxel, @pos, @v);
	}

	public void SetVoxelF(Godot.Vector3I @pos, float @v)
	{
		_object.Call(MethodName.SetVoxelF, @pos, @v);
	}

	public void DoPoint(Godot.Vector3I @pos)
	{
		_object.Call(MethodName.DoPoint, @pos);
	}

	public void DoSphere(Godot.Vector3 @center, float @radius)
	{
		_object.Call(MethodName.DoSphere, @center, @radius);
	}

	public void DoBox(Godot.Vector3I @begin, Godot.Vector3I @end)
	{
		_object.Call(MethodName.DoBox, @begin, @end);
	}

	public void DoPath(Godot.Vector3[] @points, float[] @radii)
	{
		_object.Call(MethodName.DoPath, @points, @radii);
	}

	public void DoMesh(VoxelMeshSDF @mesh_sdf, Godot.Transform3D @transform, float @isolevel = 0.0f)
	{
		_object.Call(MethodName.DoMesh, @mesh_sdf, @transform, @isolevel);
	}

	public void SmoothSphere(Godot.Vector3 @sphere_center, float @sphere_radius, int @blur_radius)
	{
		_object.Call(MethodName.SmoothSphere, @sphere_center, @sphere_radius, @blur_radius);
	}

	public void GrowSphere(Godot.Vector3 @sphere_center, float @sphere_radius, float @strength)
	{
		_object.Call(MethodName.GrowSphere, @sphere_center, @sphere_radius, @strength);
	}

	public void SetVoxelMetadata(Godot.Vector3I @pos, Variant @meta)
	{
		_object.Call(MethodName.SetVoxelMetadata, @pos, @meta);
	}

	public Variant GetVoxelMetadata(Godot.Vector3I @pos)
	{
		return (Variant)_object.Call(MethodName.GetVoxelMetadata, @pos);
	}

	public void Copy(Godot.Vector3I @src_pos, VoxelBuffer @dst_buffer, int @channels_mask = 255, bool @with_metadata = true)
	{
		_object.Call(MethodName.Copy, @src_pos, @dst_buffer, @channels_mask, @with_metadata);
	}

	public void Paste(Godot.Vector3I @dst_pos, VoxelBuffer @src_buffer, int @channels_mask = 255)
	{
		_object.Call(MethodName.Paste, @dst_pos, @src_buffer, @channels_mask);
	}

	public void PasteMasked(Godot.Vector3I @dst_pos, VoxelBuffer @src_buffer, int @channels_mask, int @mask_channel, int @mask_value)
	{
		_object.Call(MethodName.PasteMasked, @dst_pos, @src_buffer, @channels_mask, @mask_channel, @mask_value);
	}

	public void PasteMaskedWritableList(Godot.Vector3I @position, VoxelBuffer @voxels, int @channels_mask, int @src_mask_channel, int @src_mask_value, int @dst_mask_channel, int[] @dst_writable_list)
	{
		_object.Call(MethodName.PasteMaskedWritableList, @position, @voxels, @channels_mask, @src_mask_channel, @src_mask_value, @dst_mask_channel, @dst_writable_list);
	}

	public VoxelRaycastResult Raycast(Godot.Vector3 @origin, Godot.Vector3 @direction, float @max_distance = 10.0f, int @collision_mask = -1)
	{
		return (VoxelRaycastResult)_object.Call(MethodName.Raycast, @origin, @direction, @max_distance, @collision_mask);
	}

	public void SetRaycastNormalEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetRaycastNormalEnabled, @enabled);
	}

	public bool IsAreaEditable(Godot.Aabb @box)
	{
		return (bool)_object.Call(MethodName.IsAreaEditable, @box);
	}

	public static int ColorToU16(Godot.Color @color)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.ColorToU16, @color);
	}

	public static int ColorToU32(Godot.Color @color)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.ColorToU32, @color);
	}

	public static int Vec4iToU16Indices(Godot.Vector4I @_unnamed_arg0)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.Vec4iToU16Indices, @_unnamed_arg0);
	}

	public static int ColorToU16Weights(Godot.Color @_unnamed_arg0)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.ColorToU16Weights, @_unnamed_arg0);
	}

	public static Godot.Vector4I U16IndicesToVec4i(int @_unnamed_arg0)
	{
		return (Godot.Vector4I)ClassDB.ClassCallStatic(NativeName, MethodName.U16IndicesToVec4i, @_unnamed_arg0);
	}

	public static Godot.Color U16WeightsToColor(int @_unnamed_arg0)
	{
		return (Godot.Color)ClassDB.ClassCallStatic(NativeName, MethodName.U16WeightsToColor, @_unnamed_arg0);
	}

	public static Godot.Color NormalizeColor(Godot.Color @_unnamed_arg0)
	{
		return (Godot.Color)ClassDB.ClassCallStatic(NativeName, MethodName.NormalizeColor, @_unnamed_arg0);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
























