#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class VoxelBlockyModelEditorInspectorPlugin : ZN_EditorInspectorPlugin
{
	public VoxelBlockyModelEditorInspectorPlugin() : base(NativeName)
	{
	}
	protected VoxelBlockyModelEditorInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected VoxelBlockyModelEditorInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected VoxelBlockyModelEditorInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(VoxelBlockyModelEditorInspectorPlugin self) => self?._object;
	public static implicit operator Variant(VoxelBlockyModelEditorInspectorPlugin self) => self?._object;
	public static explicit operator VoxelBlockyModelEditorInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "VoxelBlockyModelEditorInspectorPlugin";
}
#endif
























