#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class ZN_EditorPropertyTextChangeOnSubmit : ZN_EditorProperty
{
	public ZN_EditorPropertyTextChangeOnSubmit() : base(NativeName)
	{
	}
	protected ZN_EditorPropertyTextChangeOnSubmit(StringName @class) : base(@class)
	{
	}
	protected ZN_EditorPropertyTextChangeOnSubmit(Variant variant) : base(variant)
	{
	}
	protected ZN_EditorPropertyTextChangeOnSubmit([NotNull] EditorProperty @object) : base(@object)
	{
	}

	public static implicit operator EditorProperty(ZN_EditorPropertyTextChangeOnSubmit self) => self?._object;
	public static implicit operator Variant(ZN_EditorPropertyTextChangeOnSubmit self) => self?._object;
	public static explicit operator ZN_EditorPropertyTextChangeOnSubmit(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorProperty.PropertyName
	{

	}

	public new class MethodName : ZN_EditorProperty.MethodName
	{

	}

	public new class SignalName : ZN_EditorProperty.SignalName
	{

	}

	private static readonly StringName NativeName = "ZN_EditorPropertyTextChangeOnSubmit";
}
#endif
























