#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class ZN_FastNoiseLiteEditorPlugin : ZN_EditorPlugin
{
	public ZN_FastNoiseLiteEditorPlugin() : base(NativeName)
	{
	}
	protected ZN_FastNoiseLiteEditorPlugin(StringName @class) : base(@class)
	{
	}
	protected ZN_FastNoiseLiteEditorPlugin(Variant variant) : base(variant)
	{
	}
	protected ZN_FastNoiseLiteEditorPlugin([NotNull] EditorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorPlugin(ZN_FastNoiseLiteEditorPlugin self) => self?._object;
	public static implicit operator Variant(ZN_FastNoiseLiteEditorPlugin self) => self?._object;
	public static explicit operator ZN_FastNoiseLiteEditorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "ZN_FastNoiseLiteEditorPlugin";
}
#endif
























