#if TOOLS
// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class ZN_FastNoiseLiteEditorInspectorPlugin : ZN_EditorInspectorPlugin
{
	public ZN_FastNoiseLiteEditorInspectorPlugin() : base(NativeName)
	{
	}
	protected ZN_FastNoiseLiteEditorInspectorPlugin(StringName @class) : base(@class)
	{
	}
	protected ZN_FastNoiseLiteEditorInspectorPlugin(Variant variant) : base(variant)
	{
	}
	protected ZN_FastNoiseLiteEditorInspectorPlugin([NotNull] EditorInspectorPlugin @object) : base(@object)
	{
	}

	public static implicit operator EditorInspectorPlugin(ZN_FastNoiseLiteEditorInspectorPlugin self) => self?._object;
	public static implicit operator Variant(ZN_FastNoiseLiteEditorInspectorPlugin self) => self?._object;
	public static explicit operator ZN_FastNoiseLiteEditorInspectorPlugin(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : ZN_EditorInspectorPlugin.PropertyName
	{

	}

	public new class MethodName : ZN_EditorInspectorPlugin.MethodName
	{

	}

	public new class SignalName : ZN_EditorInspectorPlugin.SignalName
	{

	}

	private static readonly StringName NativeName = "ZN_FastNoiseLiteEditorInspectorPlugin";
}
#endif
























