// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class ZN_FastNoiseLite
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public ZN_FastNoiseLite() : this(NativeName)
	{
	}
	protected ZN_FastNoiseLite(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected ZN_FastNoiseLite(Variant variant) : this((Resource) variant)
	{
	}
	protected ZN_FastNoiseLite([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(ZN_FastNoiseLite self) => self?._object;
	public static implicit operator Variant(ZN_FastNoiseLite self) => self?._object;
	public static explicit operator ZN_FastNoiseLite(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName NoiseType = "noise_type";
		public static readonly StringName Seed = "seed";
		public static readonly StringName Period = "period";
		public static readonly StringName WarpNoise = "warp_noise";
		public static readonly StringName FractalType = "fractal_type";
		public static readonly StringName FractalOctaves = "fractal_octaves";
		public static readonly StringName FractalLacunarity = "fractal_lacunarity";
		public static readonly StringName FractalGain = "fractal_gain";
		public static readonly StringName FractalPingPongStrength = "fractal_ping_pong_strength";
		public static readonly StringName FractalWeightedStrength = "fractal_weighted_strength";
		public static readonly StringName CellularDistanceFunction = "cellular_distance_function";
		public static readonly StringName CellularReturnType = "cellular_return_type";
		public static readonly StringName CellularJitter = "cellular_jitter";
		public static readonly StringName RotationType3d = "rotation_type_3d";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetNoiseType = "set_noise_type";
		public static readonly StringName GetNoiseType = "get_noise_type";
		public static readonly StringName SetSeed = "set_seed";
		public static readonly StringName GetSeed = "get_seed";
		public static readonly StringName SetPeriod = "set_period";
		public static readonly StringName GetPeriod = "get_period";
		public static readonly StringName SetWarpNoise = "set_warp_noise";
		public static readonly StringName GetWarpNoise = "get_warp_noise";
		public static readonly StringName SetFractalType = "set_fractal_type";
		public static readonly StringName GetFractalType = "get_fractal_type";
		public static readonly StringName SetFractalOctaves = "set_fractal_octaves";
		public static readonly StringName GetFractalOctaves = "get_fractal_octaves";
		public static readonly StringName SetFractalLacunarity = "set_fractal_lacunarity";
		public static readonly StringName GetFractalLacunarity = "get_fractal_lacunarity";
		public static readonly StringName SetFractalGain = "set_fractal_gain";
		public static readonly StringName GetFractalGain = "get_fractal_gain";
		public static readonly StringName SetFractalPingPongStrength = "set_fractal_ping_pong_strength";
		public static readonly StringName GetFractalPingPongStrength = "get_fractal_ping_pong_strength";
		public static readonly StringName SetFractalWeightedStrength = "set_fractal_weighted_strength";
		public static readonly StringName GetFractalWeightedStrength = "get_fractal_weighted_strength";
		public static readonly StringName SetCellularDistanceFunction = "set_cellular_distance_function";
		public static readonly StringName GetCellularDistanceFunction = "get_cellular_distance_function";
		public static readonly StringName SetCellularReturnType = "set_cellular_return_type";
		public static readonly StringName GetCellularReturnType = "get_cellular_return_type";
		public static readonly StringName SetCellularJitter = "set_cellular_jitter";
		public static readonly StringName GetCellularJitter = "get_cellular_jitter";
		public static readonly StringName SetRotationType3d = "set_rotation_type_3d";
		public static readonly StringName GetRotationType3d = "get_rotation_type_3d";
		public static readonly StringName GetNoise2d = "get_noise_2d";
		public static readonly StringName GetNoise3d = "get_noise_3d";
		public static readonly StringName GetNoise2Dv = "get_noise_2dv";
		public static readonly StringName GetNoise3Dv = "get_noise_3dv";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "ZN_FastNoiseLite";

	#region Enums

	public enum NoiseTypeEnum : long
	{
		OpenSimplex2 = 0L,
		OpenSimplex2s = 1L,
		Cellular = 2L,
		Perlin = 3L,
		ValueCubic = 4L,
		Value = 5L,
	}

	public enum FractalTypeEnum : long
	{
		None = 0L,
		Fbm = 1L,
		Ridged = 2L,
		PingPong = 3L,
	}

	public enum RotationType3DEnum : long
	{
		None = 0L,
		ImproveXyPlanes = 1L,
		ImproveXzPlanes = 2L,
	}

	public enum CellularDistanceFunctionEnum : long
	{
		Euclidean = 0L,
		EuclideanSq = 1L,
		Manhattan = 2L,
		Hybrid = 3L,
	}

	public enum CellularReturnTypeEnum : long
	{
		CellValue = 0L,
		Distance = 1L,
		Distance2 = 2L,
		Distance2Add = 3L,
		Distance2Sub = 4L,
		Distance2Mul = 5L,
		Distance2Div = 6L,
	}

	#endregion

	#region Properties

	public int NoiseType
	{
		get => (int)_object.Get(PropertyName.NoiseType);
		set => _object.Set(PropertyName.NoiseType, value);
	}

	public int Seed
	{
		get => (int)_object.Get(PropertyName.Seed);
		set => _object.Set(PropertyName.Seed, value);
	}

	public float Period
	{
		get => (float)_object.Get(PropertyName.Period);
		set => _object.Set(PropertyName.Period, value);
	}

	public ZN_FastNoiseLiteGradient WarpNoise
	{
		get => (ZN_FastNoiseLiteGradient)_object.Get(PropertyName.WarpNoise);
		set => _object.Set(PropertyName.WarpNoise, value);
	}

	public int FractalType
	{
		get => (int)_object.Get(PropertyName.FractalType);
		set => _object.Set(PropertyName.FractalType, value);
	}

	public int FractalOctaves
	{
		get => (int)_object.Get(PropertyName.FractalOctaves);
		set => _object.Set(PropertyName.FractalOctaves, value);
	}

	public float FractalLacunarity
	{
		get => (float)_object.Get(PropertyName.FractalLacunarity);
		set => _object.Set(PropertyName.FractalLacunarity, value);
	}

	public float FractalGain
	{
		get => (float)_object.Get(PropertyName.FractalGain);
		set => _object.Set(PropertyName.FractalGain, value);
	}

	public float FractalPingPongStrength
	{
		get => (float)_object.Get(PropertyName.FractalPingPongStrength);
		set => _object.Set(PropertyName.FractalPingPongStrength, value);
	}

	public float FractalWeightedStrength
	{
		get => (float)_object.Get(PropertyName.FractalWeightedStrength);
		set => _object.Set(PropertyName.FractalWeightedStrength, value);
	}

	public int CellularDistanceFunction
	{
		get => (int)_object.Get(PropertyName.CellularDistanceFunction);
		set => _object.Set(PropertyName.CellularDistanceFunction, value);
	}

	public int CellularReturnType
	{
		get => (int)_object.Get(PropertyName.CellularReturnType);
		set => _object.Set(PropertyName.CellularReturnType, value);
	}

	public float CellularJitter
	{
		get => (float)_object.Get(PropertyName.CellularJitter);
		set => _object.Set(PropertyName.CellularJitter, value);
	}

	public int RotationType3d
	{
		get => (int)_object.Get(PropertyName.RotationType3d);
		set => _object.Set(PropertyName.RotationType3d, value);
	}

	#endregion

	#region Inherited Properties

	public bool ResourceLocalToScene
	{
		get => _object.ResourceLocalToScene;
		set => _object.ResourceLocalToScene = value;
	}

	public string ResourcePath
	{
		get => _object.ResourcePath;
		set => _object.ResourcePath = value;
	}

	public string ResourceName
	{
		get => _object.ResourceName;
		set => _object.ResourceName = value;
	}

	public string ResourceSceneUniqueId
	{
		get => _object.ResourceSceneUniqueId;
		set => _object.ResourceSceneUniqueId = value;
	}

	#endregion

	#region Methods

	public void SetNoiseType(ZN_FastNoiseLite.NoiseTypeEnum @type)
	{
		_object.Call(MethodName.SetNoiseType, (int)@type);
	}

	public ZN_FastNoiseLite.NoiseTypeEnum GetNoiseType()
	{
		return (ZN_FastNoiseLite.NoiseTypeEnum)(int)_object.Call(MethodName.GetNoiseType);
	}

	public void SetSeed(int @seed)
	{
		_object.Call(MethodName.SetSeed, @seed);
	}

	public int GetSeed()
	{
		return (int)_object.Call(MethodName.GetSeed);
	}

	public void SetPeriod(float @period)
	{
		_object.Call(MethodName.SetPeriod, @period);
	}

	public float GetPeriod()
	{
		return (float)_object.Call(MethodName.GetPeriod);
	}

	public void SetWarpNoise(ZN_FastNoiseLiteGradient @gradient_noise)
	{
		_object.Call(MethodName.SetWarpNoise, @gradient_noise);
	}

	public ZN_FastNoiseLiteGradient GetWarpNoise()
	{
		return (ZN_FastNoiseLiteGradient)_object.Call(MethodName.GetWarpNoise);
	}

	public void SetFractalType(ZN_FastNoiseLite.FractalTypeEnum @type)
	{
		_object.Call(MethodName.SetFractalType, (int)@type);
	}

	public ZN_FastNoiseLite.FractalTypeEnum GetFractalType()
	{
		return (ZN_FastNoiseLite.FractalTypeEnum)(int)_object.Call(MethodName.GetFractalType);
	}

	public void SetFractalOctaves(int @octaves)
	{
		_object.Call(MethodName.SetFractalOctaves, @octaves);
	}

	public int GetFractalOctaves()
	{
		return (int)_object.Call(MethodName.GetFractalOctaves);
	}

	public void SetFractalLacunarity(float @lacunarity)
	{
		_object.Call(MethodName.SetFractalLacunarity, @lacunarity);
	}

	public float GetFractalLacunarity()
	{
		return (float)_object.Call(MethodName.GetFractalLacunarity);
	}

	public void SetFractalGain(float @gain)
	{
		_object.Call(MethodName.SetFractalGain, @gain);
	}

	public float GetFractalGain()
	{
		return (float)_object.Call(MethodName.GetFractalGain);
	}

	public void SetFractalPingPongStrength(float @strength)
	{
		_object.Call(MethodName.SetFractalPingPongStrength, @strength);
	}

	public float GetFractalPingPongStrength()
	{
		return (float)_object.Call(MethodName.GetFractalPingPongStrength);
	}

	public void SetFractalWeightedStrength(float @strength)
	{
		_object.Call(MethodName.SetFractalWeightedStrength, @strength);
	}

	public float GetFractalWeightedStrength()
	{
		return (float)_object.Call(MethodName.GetFractalWeightedStrength);
	}

	public void SetCellularDistanceFunction(ZN_FastNoiseLite.CellularDistanceFunctionEnum @cell_distance_func)
	{
		_object.Call(MethodName.SetCellularDistanceFunction, (int)@cell_distance_func);
	}

	public ZN_FastNoiseLite.CellularDistanceFunctionEnum GetCellularDistanceFunction()
	{
		return (ZN_FastNoiseLite.CellularDistanceFunctionEnum)(int)_object.Call(MethodName.GetCellularDistanceFunction);
	}

	public void SetCellularReturnType(ZN_FastNoiseLite.CellularReturnTypeEnum @return_type)
	{
		_object.Call(MethodName.SetCellularReturnType, (int)@return_type);
	}

	public ZN_FastNoiseLite.CellularReturnTypeEnum GetCellularReturnType()
	{
		return (ZN_FastNoiseLite.CellularReturnTypeEnum)(int)_object.Call(MethodName.GetCellularReturnType);
	}

	public void SetCellularJitter(float @return_type)
	{
		_object.Call(MethodName.SetCellularJitter, @return_type);
	}

	public float GetCellularJitter()
	{
		return (float)_object.Call(MethodName.GetCellularJitter);
	}

	public void SetRotationType3d(ZN_FastNoiseLite.RotationType3DEnum @type)
	{
		_object.Call(MethodName.SetRotationType3d, (int)@type);
	}

	public ZN_FastNoiseLite.RotationType3DEnum GetRotationType3d()
	{
		return (ZN_FastNoiseLite.RotationType3DEnum)(int)_object.Call(MethodName.GetRotationType3d);
	}

	public float GetNoise2d(float @x, float @y)
	{
		return (float)_object.Call(MethodName.GetNoise2d, @x, @y);
	}

	public float GetNoise3d(float @x, float @y, float @z)
	{
		return (float)_object.Call(MethodName.GetNoise3d, @x, @y, @z);
	}

	public float GetNoise2Dv(Godot.Vector2 @position)
	{
		return (float)_object.Call(MethodName.GetNoise2Dv, @position);
	}

	public float GetNoise3Dv(Godot.Vector3 @position)
	{
		return (float)_object.Call(MethodName.GetNoise3Dv, @position);
	}

	#endregion

	#region Inherited Methods

	public void SetPath(string @path)
	{
		_object.SetPath(@path);
	}

	public void TakeOverPath(string @path)
	{
		_object.TakeOverPath(@path);
	}

	public string GetPath()
	{
		return _object.GetPath();
	}

	public void SetPathCache(string @path)
	{
		_object.SetPathCache(@path);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public string GetName()
	{
		return _object.GetName();
	}

	public Godot.Rid GetRid()
	{
		return _object.GetRid();
	}

	public void SetLocalToScene(bool @enable)
	{
		_object.SetLocalToScene(@enable);
	}

	public bool IsLocalToScene()
	{
		return _object.IsLocalToScene();
	}

	public Node GetLocalScene()
	{
		return _object.GetLocalScene();
	}

	public void SetupLocalToScene()
	{
		_object.SetupLocalToScene();
	}

	public void ResetState()
	{
		_object.ResetState();
	}

	public void SetIdForPath(string @path, string @id)
	{
		_object.SetIdForPath(@path, @id);
	}

	public string GetIdForPath(string @path)
	{
		return _object.GetIdForPath(@path);
	}

	public bool IsBuiltIn()
	{
		return _object.IsBuiltIn();
	}

	public static string GenerateSceneUniqueId()
	{
		return Resource.GenerateSceneUniqueId();
	}

	public void SetSceneUniqueId(string @id)
	{
		_object.SetSceneUniqueId(@id);
	}

	public string GetSceneUniqueId()
	{
		return _object.GetSceneUniqueId();
	}

	public void EmitChanged()
	{
		_object.EmitChanged();
	}

	public Resource Duplicate(bool @deep = false)
	{
		return _object.Duplicate(@deep);
	}

	public Resource DuplicateDeep(Resource.DeepDuplicateMode @deep_subresources_mode = (Resource.DeepDuplicateMode)1)
	{
		return _object.DuplicateDeep(@deep_subresources_mode);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action Changed
	{
		add
		{
			Connect(SignalName.Changed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Changed, Callable.From(value));
		}
	}

	public event Action SetupLocalToSceneRequested
	{
		add
		{
			Connect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
	}

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
























