// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class ZN_FastNoiseLiteGradient
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public ZN_FastNoiseLiteGradient() : this(NativeName)
	{
	}
	protected ZN_FastNoiseLiteGradient(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected ZN_FastNoiseLiteGradient(Variant variant) : this((Resource) variant)
	{
	}
	protected ZN_FastNoiseLiteGradient([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(ZN_FastNoiseLiteGradient self) => self?._object;
	public static implicit operator Variant(ZN_FastNoiseLiteGradient self) => self?._object;
	public static explicit operator ZN_FastNoiseLiteGradient(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName NoiseType = "noise_type";
		public static readonly StringName Seed = "seed";
		public static readonly StringName Period = "period";
		public static readonly StringName Amplitude = "amplitude";
		public static readonly StringName FractalType = "fractal_type";
		public static readonly StringName FractalOctaves = "fractal_octaves";
		public static readonly StringName FractalLacunarity = "fractal_lacunarity";
		public static readonly StringName FractalGain = "fractal_gain";
		public static readonly StringName RotationType3d = "rotation_type_3d";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetNoiseType = "set_noise_type";
		public static readonly StringName GetNoiseType = "get_noise_type";
		public static readonly StringName SetSeed = "set_seed";
		public static readonly StringName GetSeed = "get_seed";
		public static readonly StringName SetPeriod = "set_period";
		public static readonly StringName GetPeriod = "get_period";
		public static readonly StringName SetAmplitude = "set_amplitude";
		public static readonly StringName GetAmplitude = "get_amplitude";
		public static readonly StringName SetFractalType = "set_fractal_type";
		public static readonly StringName GetFractalType = "get_fractal_type";
		public static readonly StringName SetFractalOctaves = "set_fractal_octaves";
		public static readonly StringName GetFractalOctaves = "get_fractal_octaves";
		public static readonly StringName SetFractalLacunarity = "set_fractal_lacunarity";
		public static readonly StringName GetFractalLacunarity = "get_fractal_lacunarity";
		public static readonly StringName SetFractalGain = "set_fractal_gain";
		public static readonly StringName GetFractalGain = "get_fractal_gain";
		public static readonly StringName SetRotationType3d = "set_rotation_type_3d";
		public static readonly StringName GetRotationType3d = "get_rotation_type_3d";
		public static readonly StringName Warp2d = "warp_2d";
		public static readonly StringName Warp3d = "warp_3d";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "ZN_FastNoiseLiteGradient";

	#region Enums

	public enum NoiseTypeEnum : long
	{
		OpenSimplex2 = 0L,
		OpenSimplex2Reduced = 1L,
		Value = 2L,
	}

	public enum FractalTypeEnum : long
	{
		None = 0L,
		DomainWarpProgressive = 1L,
		DomainWarpIndependent = 2L,
	}

	public enum RotationType3DEnum : long
	{
		None = 0L,
		ImproveXyPlanes = 1L,
		ImproveXzPlanes = 2L,
	}

	#endregion

	#region Properties

	public int NoiseType
	{
		get => (int)_object.Get(PropertyName.NoiseType);
		set => _object.Set(PropertyName.NoiseType, value);
	}

	public int Seed
	{
		get => (int)_object.Get(PropertyName.Seed);
		set => _object.Set(PropertyName.Seed, value);
	}

	public float Period
	{
		get => (float)_object.Get(PropertyName.Period);
		set => _object.Set(PropertyName.Period, value);
	}

	public float Amplitude
	{
		get => (float)_object.Get(PropertyName.Amplitude);
		set => _object.Set(PropertyName.Amplitude, value);
	}

	public int FractalType
	{
		get => (int)_object.Get(PropertyName.FractalType);
		set => _object.Set(PropertyName.FractalType, value);
	}

	public int FractalOctaves
	{
		get => (int)_object.Get(PropertyName.FractalOctaves);
		set => _object.Set(PropertyName.FractalOctaves, value);
	}

	public float FractalLacunarity
	{
		get => (float)_object.Get(PropertyName.FractalLacunarity);
		set => _object.Set(PropertyName.FractalLacunarity, value);
	}

	public float FractalGain
	{
		get => (float)_object.Get(PropertyName.FractalGain);
		set => _object.Set(PropertyName.FractalGain, value);
	}

	public int RotationType3d
	{
		get => (int)_object.Get(PropertyName.RotationType3d);
		set => _object.Set(PropertyName.RotationType3d, value);
	}

	#endregion

	#region Inherited Properties

	public bool ResourceLocalToScene
	{
		get => _object.ResourceLocalToScene;
		set => _object.ResourceLocalToScene = value;
	}

	public string ResourcePath
	{
		get => _object.ResourcePath;
		set => _object.ResourcePath = value;
	}

	public string ResourceName
	{
		get => _object.ResourceName;
		set => _object.ResourceName = value;
	}

	public string ResourceSceneUniqueId
	{
		get => _object.ResourceSceneUniqueId;
		set => _object.ResourceSceneUniqueId = value;
	}

	#endregion

	#region Methods

	public void SetNoiseType(ZN_FastNoiseLiteGradient.NoiseTypeEnum @type)
	{
		_object.Call(MethodName.SetNoiseType, (int)@type);
	}

	public ZN_FastNoiseLiteGradient.NoiseTypeEnum GetNoiseType()
	{
		return (ZN_FastNoiseLiteGradient.NoiseTypeEnum)(int)_object.Call(MethodName.GetNoiseType);
	}

	public void SetSeed(int @seed)
	{
		_object.Call(MethodName.SetSeed, @seed);
	}

	public int GetSeed()
	{
		return (int)_object.Call(MethodName.GetSeed);
	}

	public void SetPeriod(float @period)
	{
		_object.Call(MethodName.SetPeriod, @period);
	}

	public float GetPeriod()
	{
		return (float)_object.Call(MethodName.GetPeriod);
	}

	public void SetAmplitude(float @amplitude)
	{
		_object.Call(MethodName.SetAmplitude, @amplitude);
	}

	public float GetAmplitude()
	{
		return (float)_object.Call(MethodName.GetAmplitude);
	}

	public void SetFractalType(ZN_FastNoiseLiteGradient.FractalTypeEnum @type)
	{
		_object.Call(MethodName.SetFractalType, (int)@type);
	}

	public ZN_FastNoiseLiteGradient.FractalTypeEnum GetFractalType()
	{
		return (ZN_FastNoiseLiteGradient.FractalTypeEnum)(int)_object.Call(MethodName.GetFractalType);
	}

	public void SetFractalOctaves(int @octaves)
	{
		_object.Call(MethodName.SetFractalOctaves, @octaves);
	}

	public int GetFractalOctaves()
	{
		return (int)_object.Call(MethodName.GetFractalOctaves);
	}

	public void SetFractalLacunarity(float @lacunarity)
	{
		_object.Call(MethodName.SetFractalLacunarity, @lacunarity);
	}

	public float GetFractalLacunarity()
	{
		return (float)_object.Call(MethodName.GetFractalLacunarity);
	}

	public void SetFractalGain(float @gain)
	{
		_object.Call(MethodName.SetFractalGain, @gain);
	}

	public float GetFractalGain()
	{
		return (float)_object.Call(MethodName.GetFractalGain);
	}

	public void SetRotationType3d(ZN_FastNoiseLiteGradient.RotationType3DEnum @type)
	{
		_object.Call(MethodName.SetRotationType3d, (int)@type);
	}

	public ZN_FastNoiseLiteGradient.RotationType3DEnum GetRotationType3d()
	{
		return (ZN_FastNoiseLiteGradient.RotationType3DEnum)(int)_object.Call(MethodName.GetRotationType3d);
	}

	public Godot.Vector2 Warp2d(Godot.Vector2 @position)
	{
		return (Godot.Vector2)_object.Call(MethodName.Warp2d, @position);
	}

	public Godot.Vector3 Warp3d(Godot.Vector3 @position)
	{
		return (Godot.Vector3)_object.Call(MethodName.Warp3d, @position);
	}

	#endregion

	#region Inherited Methods

	public void SetPath(string @path)
	{
		_object.SetPath(@path);
	}

	public void TakeOverPath(string @path)
	{
		_object.TakeOverPath(@path);
	}

	public string GetPath()
	{
		return _object.GetPath();
	}

	public void SetPathCache(string @path)
	{
		_object.SetPathCache(@path);
	}

	public void SetName(string @name)
	{
		_object.SetName(@name);
	}

	public string GetName()
	{
		return _object.GetName();
	}

	public Godot.Rid GetRid()
	{
		return _object.GetRid();
	}

	public void SetLocalToScene(bool @enable)
	{
		_object.SetLocalToScene(@enable);
	}

	public bool IsLocalToScene()
	{
		return _object.IsLocalToScene();
	}

	public Node GetLocalScene()
	{
		return _object.GetLocalScene();
	}

	public void SetupLocalToScene()
	{
		_object.SetupLocalToScene();
	}

	public void ResetState()
	{
		_object.ResetState();
	}

	public void SetIdForPath(string @path, string @id)
	{
		_object.SetIdForPath(@path, @id);
	}

	public string GetIdForPath(string @path)
	{
		return _object.GetIdForPath(@path);
	}

	public bool IsBuiltIn()
	{
		return _object.IsBuiltIn();
	}

	public static string GenerateSceneUniqueId()
	{
		return Resource.GenerateSceneUniqueId();
	}

	public void SetSceneUniqueId(string @id)
	{
		_object.SetSceneUniqueId(@id);
	}

	public string GetSceneUniqueId()
	{
		return _object.GetSceneUniqueId();
	}

	public void EmitChanged()
	{
		_object.EmitChanged();
	}

	public Resource Duplicate(bool @deep = false)
	{
		return _object.Duplicate(@deep);
	}

	public Resource DuplicateDeep(Resource.DeepDuplicateMode @deep_subresources_mode = (Resource.DeepDuplicateMode)1)
	{
		return _object.DuplicateDeep(@deep_subresources_mode);
	}

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action Changed
	{
		add
		{
			Connect(SignalName.Changed, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.Changed, Callable.From(value));
		}
	}

	public event Action SetupLocalToSceneRequested
	{
		add
		{
			Connect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.SetupLocalToSceneRequested, Callable.From(value));
		}
	}

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
























